// This file is auto-generated by @hey-api/openapi-ts

export const BilingualTextSchema = {
    properties: {
        en: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'En',
            description: 'The English text verbatim. Leave as null if not present.'
        },
        fr: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Fr',
            description: 'The French text verbatim. Leave as null if not present.'
        }
    },
    type: 'object',
    title: 'BilingualText'
} as const;

export const Body_login_login_access_tokenSchema = {
    properties: {
        grant_type: {
            anyOf: [
                {
                    type: 'string',
                    pattern: '^password$'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Grant Type'
        },
        username: {
            type: 'string',
            title: 'Username'
        },
        password: {
            type: 'string',
            format: 'password',
            title: 'Password'
        },
        scope: {
            type: 'string',
            title: 'Scope',
            default: ''
        },
        client_id: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Client Id'
        },
        client_secret: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            format: 'password',
            title: 'Client Secret'
        }
    },
    type: 'object',
    required: [
        'username',
        'password'
    ],
    title: 'Body_login_login_access_token'
} as const;

export const ComplianceResultSchema = {
    properties: {
        status: {
            $ref: '#/components/schemas/ComplianceStatus',
            description: 'Outcome of the check: compliant, non_compliant, not_applicable, or inconclusive (requires human review).'
        },
        explanation: {
            $ref: '#/components/schemas/BilingualText',
            description: 'Concise step-by-step reasoning citing specific evidence from the Label Data that supports or contradicts the regulation\'s requirements.'
        }
    },
    type: 'object',
    required: [
        'status',
        'explanation'
    ],
    title: 'ComplianceResult'
} as const;

export const ComplianceStatusSchema = {
    type: 'string',
    enum: [
        'compliant',
        'non_compliant',
        'not_applicable',
        'inconclusive'
    ],
    title: 'ComplianceStatus'
} as const;

export const ContactSchema = {
    properties: {
        type: {
            type: 'string',
            title: 'Type',
            description: 'Type of contact',
            examples: [
                'manufacturer',
                'distributor',
                'importer'
            ]
        },
        name: {
            type: 'string',
            title: 'Name',
            description: 'Company or organization name'
        },
        address: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Address',
            description: 'Full mailing address'
        },
        phone: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Phone',
            description: 'Phone number in any format'
        },
        email: {
            anyOf: [
                {
                    type: 'string',
                    format: 'email'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Email',
            description: 'Email address'
        },
        website: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Website',
            description: 'Website URL'
        }
    },
    type: 'object',
    required: [
        'type',
        'name'
    ],
    title: 'Contact'
} as const;

export const ExtractFertilizerFieldsOutputSchema = {
    properties: {
        brand_name: {
            anyOf: [
                {
                    $ref: '#/components/schemas/BilingualText'
                },
                {
                    type: 'null'
                }
            ],
            description: 'Brand name verbatim',
            examples: [
                {
                    en: 'GreenGrow'
                }
            ]
        },
        product_name: {
            anyOf: [
                {
                    $ref: '#/components/schemas/BilingualText'
                },
                {
                    type: 'null'
                }
            ],
            description: 'Product name verbatim',
            examples: [
                {
                    en: 'Premium All-Purpose Fertilizer'
                }
            ]
        },
        contacts: {
            anyOf: [
                {
                    items: {
                        $ref: '#/components/schemas/Contact'
                    },
                    type: 'array'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Contacts',
            description: 'List of contact information (manufacturer, distributor, etc.)'
        },
        registration_number: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Registration Number',
            description: 'Registration number of the product itself (not its individual ingredients).',
            examples: [
                '1234567F'
            ]
        },
        registration_claim: {
            anyOf: [
                {
                    $ref: '#/components/schemas/BilingualText'
                },
                {
                    type: 'null'
                }
            ],
            description: 'Verbatim text where the product claims to be registered, even if no registration number is present.'
        },
        lot_number: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Lot Number',
            description: 'Lot or batch number',
            examples: [
                'LOT-2024-001'
            ]
        },
        net_weight: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Net Weight',
            description: 'Net weight with unit',
            examples: [
                '10 kg'
            ]
        },
        volume: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Volume',
            description: 'Volume with unit',
            examples: [
                '1 L'
            ]
        },
        exemption_claim: {
            anyOf: [
                {
                    $ref: '#/components/schemas/BilingualText'
                },
                {
                    type: 'null'
                }
            ],
            description: 'Verbatim claim of registration exemption (e.g., Section 18 mixture claims).',
            examples: [
                {
                    en: 'All ingredients in this mixture are registered'
                }
            ]
        },
        country_of_origin: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Country Of Origin',
            description: 'Country where the product was manufactured or from which it was imported.',
            examples: [
                'Canada',
                'United States'
            ]
        },
        product_classification: {
            anyOf: [
                {
                    $ref: '#/components/schemas/ProductClassification'
                },
                {
                    type: 'null'
                }
            ],
            description: 'Classify the product. \'fertilizer\': contains N/P/K or plant food, sold as plant nutrient. \'supplement\': improves soil or aids growth, but is not a fertilizer. \'growing_medium\': a medium (e.g., potting mix) containing fertilizers/supplements. \'treated_seed\': seeds treated with fertilizers/supplements.'
        },
        customer_formula_statements: {
            anyOf: [
                {
                    items: {
                        $ref: '#/components/schemas/BilingualText'
                    },
                    type: 'array'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Customer Formula Statements',
            description: 'A \'customer formula fertilizer\' is a fertilizer prepared to the specifications of the purchaser and sold only to that purchaser. Extract verbatim text identifying the product as such, including the purchaser\'s name or any signature references.'
        },
        intended_use_statements: {
            anyOf: [
                {
                    items: {
                        $ref: '#/components/schemas/BilingualText'
                    },
                    type: 'array'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Intended Use Statements',
            description: 'Verbatim statements indicating intended use or target audience.',
            examples: [
                [
                    {
                        en: 'For industrial use only'
                    },
                    {
                        en: 'Not for retail sale'
                    }
                ]
            ]
        },
        processing_instruction_statements: {
            anyOf: [
                {
                    items: {
                        $ref: '#/components/schemas/BilingualText'
                    },
                    type: 'array'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Processing Instruction Statements',
            description: 'Verbatim statements indicating the product requires further treatment, other than simple mixing or repackaging.',
            examples: [
                [
                    {
                        en: 'Requires further chemical processing'
                    },
                    {
                        en: 'For use as an ingredient in XYZ manufacture'
                    }
                ]
            ]
        },
        experimental_statements: {
            anyOf: [
                {
                    items: {
                        $ref: '#/components/schemas/BilingualText'
                    },
                    type: 'array'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Experimental Statements',
            description: 'Verbatim statements indicating the product is for experimental, research, or trial purposes, including instructions to destroy the product or plants upon completion.',
            examples: [
                [
                    {
                        en: 'For experimental purposes only'
                    },
                    {
                        en: 'Residual product and plants must be destroyed after trial'
                    }
                ]
            ]
        },
        export_statements: {
            anyOf: [
                {
                    items: {
                        $ref: '#/components/schemas/BilingualText'
                    },
                    type: 'array'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Export Statements',
            description: 'Verbatim statements indicating that the product is not intended for sale or use in Canada and is intended for export only.',
            examples: [
                [
                    {
                        en: 'For export only'
                    },
                    {
                        en: 'Not for sale or use in Canada'
                    }
                ]
            ]
        },
        n: {
            anyOf: [
                {
                    type: 'string',
                    pattern: '^(?!^[-+.]*$)[+-]?0*\\d*\\.?\\d*$'
                },
                {
                    type: 'null'
                }
            ],
            title: 'N',
            description: 'Nitrogen percentage (NPK analysis)',
            examples: [
                '10.0'
            ]
        },
        p: {
            anyOf: [
                {
                    type: 'string',
                    pattern: '^(?!^[-+.]*$)[+-]?0*\\d*\\.?\\d*$'
                },
                {
                    type: 'null'
                }
            ],
            title: 'P',
            description: 'Phosphorus percentage (NPK analysis)',
            examples: [
                '5.0'
            ]
        },
        k: {
            anyOf: [
                {
                    type: 'string',
                    pattern: '^(?!^[-+.]*$)[+-]?0*\\d*\\.?\\d*$'
                },
                {
                    type: 'null'
                }
            ],
            title: 'K',
            description: 'Potassium percentage (NPK analysis)',
            examples: [
                '5.0'
            ]
        },
        ingredients: {
            anyOf: [
                {
                    items: {
                        $ref: '#/components/schemas/Ingredient'
                    },
                    type: 'array'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Ingredients',
            description: 'Source materials or compounds the product is made from. This is NOT the guaranteed analysis section.'
        },
        guaranteed_analysis: {
            anyOf: [
                {
                    $ref: '#/components/schemas/GuaranteedAnalysis-Output'
                },
                {
                    type: 'null'
                }
            ],
            description: 'The guaranteed nutrient declaration section, usually under a header like \'Guaranteed Analysis\' or \'Analyse Garantie\'. This is NOT the ingredient list.'
        },
        precaution_statements: {
            anyOf: [
                {
                    items: {
                        $ref: '#/components/schemas/BilingualText'
                    },
                    type: 'array'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Precaution Statements',
            description: 'Precaution statements verbatim',
            examples: [
                [
                    {
                        en: 'Keep out of reach of children'
                    }
                ]
            ]
        },
        directions_for_use_statements: {
            anyOf: [
                {
                    items: {
                        $ref: '#/components/schemas/BilingualText'
                    },
                    type: 'array'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Directions For Use Statements',
            description: 'Directions for use verbatim',
            examples: [
                [
                    {
                        en: 'Apply 2-3 cups per 100 square feet'
                    }
                ]
            ]
        }
    },
    type: 'object',
    title: 'ExtractFertilizerFieldsOutput'
} as const;

export const ExtractFieldsRequestSchema = {
    properties: {
        field_names: {
            anyOf: [
                {
                    items: {
                        anyOf: [
                            {
                                $ref: '#/components/schemas/LabelDataFieldName'
                            },
                            {
                                $ref: '#/components/schemas/FertilizerLabelDataFieldName'
                            }
                        ]
                    },
                    type: 'array'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Field Names',
            description: 'List of field names to extract. If None or empty, extract all fields.'
        }
    },
    type: 'object',
    title: 'ExtractFieldsRequest'
} as const;

export const FertilizerLabelDataSchema = {
    properties: {
        n: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'N'
        },
        p: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'P'
        },
        k: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'K'
        },
        ingredients: {
            anyOf: [
                {
                    items: {
                        $ref: '#/components/schemas/Ingredient'
                    },
                    type: 'array'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Ingredients'
        },
        guaranteed_analysis: {
            anyOf: [
                {
                    $ref: '#/components/schemas/GuaranteedAnalysis-Output'
                },
                {
                    type: 'null'
                }
            ]
        },
        precaution_statements: {
            anyOf: [
                {
                    items: {
                        $ref: '#/components/schemas/BilingualText'
                    },
                    type: 'array'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Precaution Statements'
        },
        directions_for_use_statements: {
            anyOf: [
                {
                    items: {
                        $ref: '#/components/schemas/BilingualText'
                    },
                    type: 'array'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Directions For Use Statements'
        },
        customer_formula_statements: {
            anyOf: [
                {
                    items: {
                        $ref: '#/components/schemas/BilingualText'
                    },
                    type: 'array'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Customer Formula Statements'
        },
        intended_use_statements: {
            anyOf: [
                {
                    items: {
                        $ref: '#/components/schemas/BilingualText'
                    },
                    type: 'array'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Intended Use Statements'
        },
        processing_instruction_statements: {
            anyOf: [
                {
                    items: {
                        $ref: '#/components/schemas/BilingualText'
                    },
                    type: 'array'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Processing Instruction Statements'
        },
        experimental_statements: {
            anyOf: [
                {
                    items: {
                        $ref: '#/components/schemas/BilingualText'
                    },
                    type: 'array'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Experimental Statements'
        },
        export_statements: {
            anyOf: [
                {
                    items: {
                        $ref: '#/components/schemas/BilingualText'
                    },
                    type: 'array'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Export Statements'
        },
        product_classification: {
            anyOf: [
                {
                    $ref: '#/components/schemas/ProductClassification'
                },
                {
                    type: 'null'
                }
            ]
        }
    },
    type: 'object',
    title: 'FertilizerLabelData'
} as const;

export const FertilizerLabelDataCreateSchema = {
    properties: {
        n: {
            anyOf: [
                {
                    type: 'number',
                    minimum: 0
                },
                {
                    type: 'string',
                    pattern: '^(?!^[-+.]*$)[+-]?0*\\d*\\.?\\d*$'
                },
                {
                    type: 'null'
                }
            ],
            title: 'N'
        },
        p: {
            anyOf: [
                {
                    type: 'number',
                    minimum: 0
                },
                {
                    type: 'string',
                    pattern: '^(?!^[-+.]*$)[+-]?0*\\d*\\.?\\d*$'
                },
                {
                    type: 'null'
                }
            ],
            title: 'P'
        },
        k: {
            anyOf: [
                {
                    type: 'number',
                    minimum: 0
                },
                {
                    type: 'string',
                    pattern: '^(?!^[-+.]*$)[+-]?0*\\d*\\.?\\d*$'
                },
                {
                    type: 'null'
                }
            ],
            title: 'K'
        },
        ingredients: {
            anyOf: [
                {
                    items: {
                        $ref: '#/components/schemas/Ingredient'
                    },
                    type: 'array'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Ingredients'
        },
        guaranteed_analysis: {
            anyOf: [
                {
                    $ref: '#/components/schemas/GuaranteedAnalysis-Input'
                },
                {
                    type: 'null'
                }
            ]
        },
        precaution_statements: {
            anyOf: [
                {
                    items: {
                        $ref: '#/components/schemas/BilingualText'
                    },
                    type: 'array'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Precaution Statements'
        },
        directions_for_use_statements: {
            anyOf: [
                {
                    items: {
                        $ref: '#/components/schemas/BilingualText'
                    },
                    type: 'array'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Directions For Use Statements'
        },
        customer_formula_statements: {
            anyOf: [
                {
                    items: {
                        $ref: '#/components/schemas/BilingualText'
                    },
                    type: 'array'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Customer Formula Statements'
        },
        intended_use_statements: {
            anyOf: [
                {
                    items: {
                        $ref: '#/components/schemas/BilingualText'
                    },
                    type: 'array'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Intended Use Statements'
        },
        processing_instruction_statements: {
            anyOf: [
                {
                    items: {
                        $ref: '#/components/schemas/BilingualText'
                    },
                    type: 'array'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Processing Instruction Statements'
        },
        experimental_statements: {
            anyOf: [
                {
                    items: {
                        $ref: '#/components/schemas/BilingualText'
                    },
                    type: 'array'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Experimental Statements'
        },
        export_statements: {
            anyOf: [
                {
                    items: {
                        $ref: '#/components/schemas/BilingualText'
                    },
                    type: 'array'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Export Statements'
        },
        product_classification: {
            anyOf: [
                {
                    $ref: '#/components/schemas/ProductClassification'
                },
                {
                    type: 'null'
                }
            ]
        }
    },
    type: 'object',
    title: 'FertilizerLabelDataCreate'
} as const;

export const FertilizerLabelDataFieldNameSchema = {
    type: 'string',
    enum: [
        'n',
        'p',
        'k',
        'ingredients',
        'guaranteed_analysis',
        'precaution_statements',
        'directions_for_use_statements',
        'customer_formula_statements',
        'intended_use_statements',
        'processing_instruction_statements',
        'experimental_statements',
        'export_statements',
        'product_classification'
    ],
    title: 'FertilizerLabelDataFieldName',
    description: 'Valid field names for FertilizerLabelDataMeta.'
} as const;

export const FertilizerLabelDataMetaResponseSchema = {
    properties: {
        field_name: {
            type: 'string',
            title: 'Field Name'
        },
        needs_review: {
            type: 'boolean',
            title: 'Needs Review'
        },
        note: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Note'
        },
        ai_generated: {
            type: 'boolean',
            title: 'Ai Generated'
        }
    },
    type: 'object',
    required: [
        'field_name',
        'needs_review',
        'note',
        'ai_generated'
    ],
    title: 'FertilizerLabelDataMetaResponse'
} as const;

export const FertilizerLabelDataMetaUpdateSchema = {
    properties: {
        field_name: {
            $ref: '#/components/schemas/FertilizerLabelDataFieldName'
        },
        needs_review: {
            anyOf: [
                {
                    type: 'boolean'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Needs Review'
        },
        note: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Note'
        },
        ai_generated: {
            anyOf: [
                {
                    type: 'boolean'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Ai Generated'
        }
    },
    type: 'object',
    required: [
        'field_name'
    ],
    title: 'FertilizerLabelDataMetaUpdate'
} as const;

export const FertilizerLabelDataUpdateSchema = {
    properties: {
        n: {
            anyOf: [
                {
                    type: 'number',
                    minimum: 0
                },
                {
                    type: 'string',
                    pattern: '^(?!^[-+.]*$)[+-]?0*\\d*\\.?\\d*$'
                },
                {
                    type: 'null'
                }
            ],
            title: 'N'
        },
        p: {
            anyOf: [
                {
                    type: 'number',
                    minimum: 0
                },
                {
                    type: 'string',
                    pattern: '^(?!^[-+.]*$)[+-]?0*\\d*\\.?\\d*$'
                },
                {
                    type: 'null'
                }
            ],
            title: 'P'
        },
        k: {
            anyOf: [
                {
                    type: 'number',
                    minimum: 0
                },
                {
                    type: 'string',
                    pattern: '^(?!^[-+.]*$)[+-]?0*\\d*\\.?\\d*$'
                },
                {
                    type: 'null'
                }
            ],
            title: 'K'
        },
        ingredients: {
            anyOf: [
                {
                    items: {
                        $ref: '#/components/schemas/Ingredient'
                    },
                    type: 'array'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Ingredients'
        },
        guaranteed_analysis: {
            anyOf: [
                {
                    $ref: '#/components/schemas/GuaranteedAnalysis-Input'
                },
                {
                    type: 'null'
                }
            ]
        },
        precaution_statements: {
            anyOf: [
                {
                    items: {
                        $ref: '#/components/schemas/BilingualText'
                    },
                    type: 'array'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Precaution Statements'
        },
        directions_for_use_statements: {
            anyOf: [
                {
                    items: {
                        $ref: '#/components/schemas/BilingualText'
                    },
                    type: 'array'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Directions For Use Statements'
        },
        customer_formula_statements: {
            anyOf: [
                {
                    items: {
                        $ref: '#/components/schemas/BilingualText'
                    },
                    type: 'array'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Customer Formula Statements'
        },
        intended_use_statements: {
            anyOf: [
                {
                    items: {
                        $ref: '#/components/schemas/BilingualText'
                    },
                    type: 'array'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Intended Use Statements'
        },
        processing_instruction_statements: {
            anyOf: [
                {
                    items: {
                        $ref: '#/components/schemas/BilingualText'
                    },
                    type: 'array'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Processing Instruction Statements'
        },
        experimental_statements: {
            anyOf: [
                {
                    items: {
                        $ref: '#/components/schemas/BilingualText'
                    },
                    type: 'array'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Experimental Statements'
        },
        export_statements: {
            anyOf: [
                {
                    items: {
                        $ref: '#/components/schemas/BilingualText'
                    },
                    type: 'array'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Export Statements'
        },
        product_classification: {
            anyOf: [
                {
                    $ref: '#/components/schemas/ProductClassification'
                },
                {
                    type: 'null'
                }
            ]
        }
    },
    type: 'object',
    title: 'FertilizerLabelDataUpdate'
} as const;

export const GuaranteedAnalysis_InputSchema = {
    properties: {
        title: {
            $ref: '#/components/schemas/BilingualText',
            examples: [
                {
                    en: 'Minimum Guaranteed Analysis'
                }
            ]
        },
        is_minimum: {
            type: 'boolean',
            title: 'Is Minimum',
            description: 'True if title contains \'Minimum\', false otherwise'
        },
        nutrients: {
            items: {
                $ref: '#/components/schemas/Nutrient-Input'
            },
            type: 'array',
            title: 'Nutrients',
            description: 'List of nutrients with bilingual names, values and units'
        }
    },
    type: 'object',
    required: [
        'title',
        'is_minimum',
        'nutrients'
    ],
    title: 'GuaranteedAnalysis'
} as const;

export const GuaranteedAnalysis_OutputSchema = {
    properties: {
        title: {
            $ref: '#/components/schemas/BilingualText',
            examples: [
                {
                    en: 'Minimum Guaranteed Analysis'
                }
            ]
        },
        is_minimum: {
            type: 'boolean',
            title: 'Is Minimum',
            description: 'True if title contains \'Minimum\', false otherwise'
        },
        nutrients: {
            items: {
                $ref: '#/components/schemas/Nutrient-Output'
            },
            type: 'array',
            title: 'Nutrients',
            description: 'List of nutrients with bilingual names, values and units'
        }
    },
    type: 'object',
    required: [
        'title',
        'is_minimum',
        'nutrients'
    ],
    title: 'GuaranteedAnalysis'
} as const;

export const HTTPValidationErrorSchema = {
    properties: {
        detail: {
            items: {
                $ref: '#/components/schemas/ValidationError'
            },
            type: 'array',
            title: 'Detail'
        }
    },
    type: 'object',
    title: 'HTTPValidationError'
} as const;

export const HealthSchema = {
    properties: {
        status: {
            type: 'string',
            title: 'Status'
        }
    },
    type: 'object',
    required: [
        'status'
    ],
    title: 'Health'
} as const;

export const IngredientSchema = {
    properties: {
        name: {
            $ref: '#/components/schemas/BilingualText',
            description: 'Ingredient name verbatim'
        },
        value: {
            type: 'string',
            title: 'Value',
            description: 'Ingredient percentage or amount.'
        },
        unit: {
            type: 'string',
            title: 'Unit',
            description: 'Unit of measurement',
            examples: [
                '%',
                'ppm',
                'mg/kg',
                'g/kg',
                'mm'
            ]
        },
        registration_number: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Registration Number',
            description: 'Registration number of the product itself (not its individual ingredients).',
            examples: [
                '1234567F'
            ]
        }
    },
    type: 'object',
    required: [
        'name',
        'value',
        'unit'
    ],
    title: 'Ingredient'
} as const;

export const LabelCreateSchema = {
    properties: {
        product_type: {
            type: 'string',
            title: 'Product Type'
        },
        product_id: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Product Id'
        }
    },
    type: 'object',
    required: [
        'product_type'
    ],
    title: 'LabelCreate'
} as const;

export const LabelCreatedSchema = {
    properties: {
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        }
    },
    type: 'object',
    required: [
        'id'
    ],
    title: 'LabelCreated',
    description: 'Response schema for label creation.'
} as const;

export const LabelDataSchema = {
    properties: {
        brand_name: {
            anyOf: [
                {
                    $ref: '#/components/schemas/BilingualText'
                },
                {
                    type: 'null'
                }
            ]
        },
        product_name: {
            anyOf: [
                {
                    $ref: '#/components/schemas/BilingualText'
                },
                {
                    type: 'null'
                }
            ]
        },
        contacts: {
            anyOf: [
                {
                    items: {
                        $ref: '#/components/schemas/Contact'
                    },
                    type: 'array'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Contacts'
        },
        registration_number: {
            anyOf: [
                {
                    type: 'string',
                    pattern: '^([0-9]{7}[FfPpGgHhMmSs])?$'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Registration Number'
        },
        registration_claim: {
            anyOf: [
                {
                    $ref: '#/components/schemas/BilingualText'
                },
                {
                    type: 'null'
                }
            ]
        },
        lot_number: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Lot Number'
        },
        net_weight: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Net Weight'
        },
        volume: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Volume'
        },
        exemption_claim: {
            anyOf: [
                {
                    $ref: '#/components/schemas/BilingualText'
                },
                {
                    type: 'null'
                }
            ]
        },
        country_of_origin: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Country Of Origin'
        }
    },
    type: 'object',
    title: 'LabelData'
} as const;

export const LabelDataCreateSchema = {
    properties: {
        brand_name: {
            anyOf: [
                {
                    $ref: '#/components/schemas/BilingualText'
                },
                {
                    type: 'null'
                }
            ]
        },
        product_name: {
            anyOf: [
                {
                    $ref: '#/components/schemas/BilingualText'
                },
                {
                    type: 'null'
                }
            ]
        },
        contacts: {
            anyOf: [
                {
                    items: {
                        $ref: '#/components/schemas/Contact'
                    },
                    type: 'array'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Contacts'
        },
        registration_number: {
            anyOf: [
                {
                    type: 'string',
                    pattern: '^([0-9]{7}[FfPpGgHhMmSs])?$'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Registration Number'
        },
        registration_claim: {
            anyOf: [
                {
                    $ref: '#/components/schemas/BilingualText'
                },
                {
                    type: 'null'
                }
            ]
        },
        lot_number: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Lot Number'
        },
        net_weight: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Net Weight'
        },
        volume: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Volume'
        },
        exemption_claim: {
            anyOf: [
                {
                    $ref: '#/components/schemas/BilingualText'
                },
                {
                    type: 'null'
                }
            ]
        },
        country_of_origin: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Country Of Origin'
        }
    },
    type: 'object',
    title: 'LabelDataCreate'
} as const;

export const LabelDataFieldMetaResponseSchema = {
    properties: {
        field_name: {
            type: 'string',
            title: 'Field Name'
        },
        needs_review: {
            type: 'boolean',
            title: 'Needs Review'
        },
        note: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Note'
        },
        ai_generated: {
            type: 'boolean',
            title: 'Ai Generated'
        }
    },
    type: 'object',
    required: [
        'field_name',
        'needs_review',
        'note',
        'ai_generated'
    ],
    title: 'LabelDataFieldMetaResponse'
} as const;

export const LabelDataFieldMetaUpdateSchema = {
    properties: {
        field_name: {
            $ref: '#/components/schemas/LabelDataFieldName'
        },
        needs_review: {
            anyOf: [
                {
                    type: 'boolean'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Needs Review'
        },
        note: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Note'
        },
        ai_generated: {
            anyOf: [
                {
                    type: 'boolean'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Ai Generated'
        }
    },
    type: 'object',
    required: [
        'field_name'
    ],
    title: 'LabelDataFieldMetaUpdate'
} as const;

export const LabelDataFieldNameSchema = {
    type: 'string',
    enum: [
        'brand_name',
        'product_name',
        'contacts',
        'registration_number',
        'registration_claim',
        'lot_number',
        'net_weight',
        'volume',
        'exemption_claim',
        'country_of_origin'
    ],
    title: 'LabelDataFieldName',
    description: 'Valid field names for LabelDataFieldMeta.'
} as const;

export const LabelDataLiteSchema = {
    properties: {
        brand_name: {
            anyOf: [
                {
                    $ref: '#/components/schemas/BilingualText'
                },
                {
                    type: 'null'
                }
            ]
        },
        product_name: {
            anyOf: [
                {
                    $ref: '#/components/schemas/BilingualText'
                },
                {
                    type: 'null'
                }
            ]
        },
        registration_number: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Registration Number'
        }
    },
    type: 'object',
    title: 'LabelDataLite'
} as const;

export const LabelDataUpdateSchema = {
    properties: {
        brand_name: {
            anyOf: [
                {
                    $ref: '#/components/schemas/BilingualText'
                },
                {
                    type: 'null'
                }
            ]
        },
        product_name: {
            anyOf: [
                {
                    $ref: '#/components/schemas/BilingualText'
                },
                {
                    type: 'null'
                }
            ]
        },
        contacts: {
            anyOf: [
                {
                    items: {
                        $ref: '#/components/schemas/Contact'
                    },
                    type: 'array'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Contacts'
        },
        registration_number: {
            anyOf: [
                {
                    type: 'string',
                    pattern: '^([0-9]{7}[FfPpGgHhMmSs])?$'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Registration Number'
        },
        registration_claim: {
            anyOf: [
                {
                    $ref: '#/components/schemas/BilingualText'
                },
                {
                    type: 'null'
                }
            ]
        },
        lot_number: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Lot Number'
        },
        net_weight: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Net Weight'
        },
        volume: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Volume'
        },
        exemption_claim: {
            anyOf: [
                {
                    $ref: '#/components/schemas/BilingualText'
                },
                {
                    type: 'null'
                }
            ]
        },
        country_of_origin: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Country Of Origin'
        }
    },
    type: 'object',
    title: 'LabelDataUpdate'
} as const;

export const LabelDetailSchema = {
    properties: {
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        product_id: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Product Id'
        },
        created_by_id: {
            type: 'string',
            format: 'uuid',
            title: 'Created By Id'
        },
        review_status: {
            $ref: '#/components/schemas/ReviewStatus'
        },
        created_at: {
            type: 'string',
            format: 'date-time',
            title: 'Created At'
        },
        updated_at: {
            type: 'string',
            format: 'date-time',
            title: 'Updated At'
        },
        product_type: {
            $ref: '#/components/schemas/ProductTypePublic'
        },
        created_by: {
            $ref: '#/components/schemas/UserPublic'
        },
        images: {
            items: {
                $ref: '#/components/schemas/LabelImageDetail'
            },
            type: 'array',
            title: 'Images'
        }
    },
    type: 'object',
    required: [
        'id',
        'created_by_id',
        'review_status',
        'created_at',
        'updated_at',
        'product_type',
        'created_by'
    ],
    title: 'LabelDetail'
} as const;

export const LabelImageDetailSchema = {
    properties: {
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        label_id: {
            type: 'string',
            format: 'uuid',
            title: 'Label Id'
        },
        display_filename: {
            type: 'string',
            title: 'Display Filename'
        },
        file_path: {
            type: 'string',
            title: 'File Path'
        },
        sequence_order: {
            type: 'integer',
            title: 'Sequence Order'
        },
        status: {
            $ref: '#/components/schemas/UploadStatus'
        },
        created_at: {
            type: 'string',
            format: 'date-time',
            title: 'Created At'
        },
        updated_at: {
            type: 'string',
            format: 'date-time',
            title: 'Updated At'
        },
        current_image_count: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Current Image Count'
        }
    },
    type: 'object',
    required: [
        'id',
        'label_id',
        'display_filename',
        'file_path',
        'sequence_order',
        'status',
        'created_at',
        'updated_at'
    ],
    title: 'LabelImageDetail'
} as const;

export const LabelListItemSchema = {
    properties: {
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        review_status: {
            $ref: '#/components/schemas/ReviewStatus'
        },
        created_at: {
            type: 'string',
            format: 'date-time',
            title: 'Created At'
        },
        updated_at: {
            type: 'string',
            format: 'date-time',
            title: 'Updated At'
        },
        label_data: {
            anyOf: [
                {
                    $ref: '#/components/schemas/LabelDataLite'
                },
                {
                    type: 'null'
                }
            ]
        }
    },
    type: 'object',
    required: [
        'id',
        'review_status',
        'created_at',
        'updated_at'
    ],
    title: 'LabelListItem',
    description: 'Schema for label list items.'
} as const;

export const LabelReviewStatusUpdateSchema = {
    properties: {
        review_status: {
            $ref: '#/components/schemas/ReviewStatus'
        }
    },
    type: 'object',
    required: [
        'review_status'
    ],
    title: 'LabelReviewStatusUpdate'
} as const;

export const LabelUpdateSchema = {
    properties: {
        product_id: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Product Id'
        }
    },
    type: 'object',
    title: 'LabelUpdate'
} as const;

export const LegislationPublicSchema = {
    properties: {
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        citation_reference: {
            type: 'string',
            title: 'Citation Reference'
        },
        legislation_type: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Legislation Type'
        },
        product_type_id: {
            type: 'string',
            format: 'uuid',
            title: 'Product Type Id'
        },
        title_en: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Title En'
        },
        title_fr: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Title Fr'
        },
        description_en: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description En'
        },
        description_fr: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description Fr'
        },
        guidance_en: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Guidance En'
        },
        guidance_fr: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Guidance Fr'
        },
        source_url_en: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Source Url En'
        },
        source_url_fr: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Source Url Fr'
        },
        last_amended_date: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Last Amended Date'
        },
        created_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Created At'
        },
        updated_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Updated At'
        }
    },
    type: 'object',
    required: [
        'id',
        'citation_reference',
        'product_type_id'
    ],
    title: 'LegislationPublic'
} as const;

export const LimitOffsetPage_LabelListItem_Schema = {
    properties: {
        items: {
            items: {
                $ref: '#/components/schemas/LabelListItem'
            },
            type: 'array',
            title: 'Items'
        },
        total: {
            type: 'integer',
            minimum: 0,
            title: 'Total'
        },
        limit: {
            type: 'integer',
            minimum: 1,
            title: 'Limit'
        },
        offset: {
            type: 'integer',
            minimum: 0,
            title: 'Offset'
        }
    },
    type: 'object',
    required: [
        'items',
        'total',
        'limit',
        'offset'
    ],
    title: 'LimitOffsetPage[LabelListItem]'
} as const;

export const LimitOffsetPage_NonComplianceDataItemPublic_Schema = {
    properties: {
        items: {
            items: {
                $ref: '#/components/schemas/NonComplianceDataItemPublic'
            },
            type: 'array',
            title: 'Items'
        },
        total: {
            type: 'integer',
            minimum: 0,
            title: 'Total'
        },
        limit: {
            type: 'integer',
            minimum: 1,
            title: 'Limit'
        },
        offset: {
            type: 'integer',
            minimum: 0,
            title: 'Offset'
        }
    },
    type: 'object',
    required: [
        'items',
        'total',
        'limit',
        'offset'
    ],
    title: 'LimitOffsetPage[NonComplianceDataItemPublic]'
} as const;

export const LimitOffsetPage_ProductPublic_Schema = {
    properties: {
        items: {
            items: {
                $ref: '#/components/schemas/ProductPublic'
            },
            type: 'array',
            title: 'Items'
        },
        total: {
            type: 'integer',
            minimum: 0,
            title: 'Total'
        },
        limit: {
            type: 'integer',
            minimum: 1,
            title: 'Limit'
        },
        offset: {
            type: 'integer',
            minimum: 0,
            title: 'Offset'
        }
    },
    type: 'object',
    required: [
        'items',
        'total',
        'limit',
        'offset'
    ],
    title: 'LimitOffsetPage[ProductPublic]'
} as const;

export const LimitOffsetPage_RequirementPublic_Schema = {
    properties: {
        items: {
            items: {
                $ref: '#/components/schemas/RequirementPublic'
            },
            type: 'array',
            title: 'Items'
        },
        total: {
            type: 'integer',
            minimum: 0,
            title: 'Total'
        },
        limit: {
            type: 'integer',
            minimum: 1,
            title: 'Limit'
        },
        offset: {
            type: 'integer',
            minimum: 0,
            title: 'Offset'
        }
    },
    type: 'object',
    required: [
        'items',
        'total',
        'limit',
        'offset'
    ],
    title: 'LimitOffsetPage[RequirementPublic]'
} as const;

export const MessageSchema = {
    properties: {
        message: {
            type: 'string',
            title: 'Message'
        }
    },
    type: 'object',
    required: [
        'message'
    ],
    title: 'Message'
} as const;

export const NewPasswordSchema = {
    properties: {
        token: {
            type: 'string',
            title: 'Token'
        },
        new_password: {
            type: 'string',
            title: 'New Password'
        }
    },
    type: 'object',
    required: [
        'token',
        'new_password'
    ],
    title: 'NewPassword'
} as const;

export const NonComplianceDataItemPayloadSchema = {
    properties: {
        requirement_id: {
            type: 'string',
            format: 'uuid',
            title: 'Requirement Id'
        },
        note: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Note'
        },
        description_en: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description En'
        },
        description_fr: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description Fr'
        },
        status: {
            $ref: '#/components/schemas/ComplianceStatus',
            default: 'inconclusive'
        }
    },
    type: 'object',
    required: [
        'requirement_id'
    ],
    title: 'NonComplianceDataItemPayload'
} as const;

export const NonComplianceDataItemPublicSchema = {
    properties: {
        label_id: {
            type: 'string',
            format: 'uuid',
            title: 'Label Id'
        },
        requirement_id: {
            type: 'string',
            format: 'uuid',
            title: 'Requirement Id'
        },
        note: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Note'
        },
        description_en: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description En'
        },
        description_fr: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description Fr'
        },
        status: {
            $ref: '#/components/schemas/ComplianceStatus',
            default: 'inconclusive'
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        }
    },
    type: 'object',
    required: [
        'label_id',
        'requirement_id',
        'id'
    ],
    title: 'NonComplianceDataItemPublic'
} as const;

export const Nutrient_InputSchema = {
    properties: {
        name: {
            $ref: '#/components/schemas/BilingualText',
            description: 'Nutrient name verbatim',
            examples: [
                {
                    en: 'Total Nitrogen (N)'
                }
            ]
        },
        value: {
            anyOf: [
                {
                    type: 'number',
                    minimum: 0
                },
                {
                    type: 'string',
                    pattern: '^(?!^[-+.]*$)[+-]?0*\\d*\\.?\\d*$'
                }
            ],
            title: 'Value',
            description: 'Nutrient percentage value'
        },
        unit: {
            type: 'string',
            title: 'Unit',
            description: 'Unit of measurement',
            examples: [
                '%',
                'ppm',
                'mg/kg',
                'g/kg'
            ]
        }
    },
    type: 'object',
    required: [
        'name',
        'value',
        'unit'
    ],
    title: 'Nutrient'
} as const;

export const Nutrient_OutputSchema = {
    properties: {
        name: {
            $ref: '#/components/schemas/BilingualText',
            description: 'Nutrient name verbatim',
            examples: [
                {
                    en: 'Total Nitrogen (N)'
                }
            ]
        },
        value: {
            type: 'string',
            pattern: '^(?!^[-+.]*$)[+-]?0*\\d*\\.?\\d*$',
            title: 'Value',
            description: 'Nutrient percentage value'
        },
        unit: {
            type: 'string',
            title: 'Unit',
            description: 'Unit of measurement',
            examples: [
                '%',
                'ppm',
                'mg/kg',
                'g/kg'
            ]
        }
    },
    type: 'object',
    required: [
        'name',
        'value',
        'unit'
    ],
    title: 'Nutrient'
} as const;

export const PresignedDownloadUrlResponseSchema = {
    properties: {
        presigned_url: {
            type: 'string',
            title: 'Presigned Url'
        }
    },
    type: 'object',
    required: [
        'presigned_url'
    ],
    title: 'PresignedDownloadUrlResponse',
    description: 'Response schema for presigned download URL request.'
} as const;

export const PresignedUploadUrlResponseSchema = {
    properties: {
        url: {
            type: 'string',
            title: 'Url'
        },
        expires_at: {
            type: 'string',
            format: 'date-time',
            title: 'Expires At'
        }
    },
    type: 'object',
    required: [
        'url',
        'expires_at'
    ],
    title: 'PresignedUploadUrlResponse',
    description: 'Response schema for presigned upload URL request.'
} as const;

export const PresignedUrlRequestSchema = {
    properties: {
        display_filename: {
            type: 'string',
            title: 'Display Filename'
        },
        content_type: {
            type: 'string',
            enum: [
                'image/png',
                'image/jpeg',
                'image/webp'
            ],
            title: 'Content Type'
        },
        sequence_order: {
            type: 'integer',
            minimum: 1,
            title: 'Sequence Order'
        }
    },
    type: 'object',
    required: [
        'display_filename',
        'content_type',
        'sequence_order'
    ],
    title: 'PresignedUrlRequest',
    description: 'Request schema for individual presigned URL generation.'
} as const;

export const PrivateUserCreateSchema = {
    properties: {
        email: {
            type: 'string',
            format: 'email',
            title: 'Email'
        },
        password: {
            type: 'string',
            title: 'Password'
        },
        first_name: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'First Name'
        },
        last_name: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Last Name'
        }
    },
    type: 'object',
    required: [
        'email',
        'password'
    ],
    title: 'PrivateUserCreate'
} as const;

export const ProductClassificationSchema = {
    type: 'string',
    enum: [
        'fertilizer',
        'supplement',
        'growing_medium',
        'treated_seed'
    ],
    title: 'ProductClassification'
} as const;

export const ProductCreateSchema = {
    properties: {
        registration_number: {
            anyOf: [
                {
                    type: 'string',
                    pattern: '^([0-9]{7}[FfPpGgHhMmSs])?$'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Registration Number'
        },
        product_type: {
            type: 'string',
            title: 'Product Type'
        },
        brand_name_en: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Brand Name En'
        },
        brand_name_fr: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Brand Name Fr'
        },
        name_en: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Name En'
        },
        name_fr: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Name Fr'
        }
    },
    type: 'object',
    required: [
        'product_type'
    ],
    title: 'ProductCreate'
} as const;

export const ProductPublicSchema = {
    properties: {
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        brand_name_en: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Brand Name En'
        },
        brand_name_fr: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Brand Name Fr'
        },
        name_en: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Name En'
        },
        name_fr: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Name Fr'
        },
        registration_number: {
            anyOf: [
                {
                    type: 'string',
                    pattern: '^([0-9]{7}[FfPpGgHhMmSs])?$'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Registration Number'
        },
        created_at: {
            type: 'string',
            format: 'date-time',
            title: 'Created At'
        }
    },
    type: 'object',
    required: [
        'id',
        'created_at'
    ],
    title: 'ProductPublic'
} as const;

export const ProductTypePublicSchema = {
    properties: {
        code: {
            type: 'string',
            maxLength: 255,
            title: 'Code'
        },
        name_en: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Name En'
        },
        name_fr: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Name Fr'
        },
        is_active: {
            type: 'boolean',
            title: 'Is Active',
            default: true
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        created_at: {
            type: 'string',
            format: 'date-time',
            title: 'Created At'
        },
        updated_at: {
            type: 'string',
            format: 'date-time',
            title: 'Updated At'
        }
    },
    type: 'object',
    required: [
        'code',
        'id',
        'created_at',
        'updated_at'
    ],
    title: 'ProductTypePublic'
} as const;

export const ReadinessSchema = {
    properties: {
        status: {
            type: 'string',
            title: 'Status'
        },
        database: {
            type: 'string',
            title: 'Database'
        }
    },
    type: 'object',
    required: [
        'status',
        'database'
    ],
    title: 'Readiness'
} as const;

export const RequirementPublicSchema = {
    properties: {
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        legislation_id: {
            type: 'string',
            format: 'uuid',
            title: 'Legislation Id'
        },
        title_en: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Title En'
        },
        title_fr: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Title Fr'
        },
        description_en: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description En'
        },
        description_fr: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description Fr'
        },
        guidance_en: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Guidance En'
        },
        guidance_fr: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Guidance Fr'
        },
        created_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Created At'
        },
        updated_at: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Updated At'
        }
    },
    type: 'object',
    required: [
        'id',
        'legislation_id'
    ],
    title: 'RequirementPublic'
} as const;

export const ReviewStatusSchema = {
    type: 'string',
    enum: [
        'not_started',
        'in_progress',
        'completed'
    ],
    title: 'ReviewStatus'
} as const;

export const TokenSchema = {
    properties: {
        access_token: {
            type: 'string',
            title: 'Access Token'
        },
        token_type: {
            type: 'string',
            title: 'Token Type',
            default: 'bearer'
        }
    },
    type: 'object',
    required: [
        'access_token'
    ],
    title: 'Token'
} as const;

export const UpdateNonComplianceDataItemPayloadSchema = {
    properties: {
        note: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Note'
        },
        description_en: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description En'
        },
        description_fr: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description Fr'
        },
        status: {
            anyOf: [
                {
                    $ref: '#/components/schemas/ComplianceStatus'
                },
                {
                    type: 'null'
                }
            ]
        }
    },
    type: 'object',
    title: 'UpdateNonComplianceDataItemPayload'
} as const;

export const UpdatePasswordSchema = {
    properties: {
        current_password: {
            type: 'string',
            maxLength: 40,
            minLength: 8,
            format: 'password',
            title: 'Current Password',
            writeOnly: true
        },
        new_password: {
            type: 'string',
            maxLength: 40,
            minLength: 8,
            format: 'password',
            title: 'New Password',
            writeOnly: true
        }
    },
    type: 'object',
    required: [
        'current_password',
        'new_password'
    ],
    title: 'UpdatePassword'
} as const;

export const UploadCompletionRequestSchema = {
    properties: {
        storage_file_path: {
            type: 'string',
            title: 'Storage File Path'
        }
    },
    type: 'object',
    required: [
        'storage_file_path'
    ],
    title: 'UploadCompletionRequest',
    description: 'Request schema for upload completion notification.'
} as const;

export const UploadStatusSchema = {
    type: 'string',
    enum: [
        'pending',
        'completed'
    ],
    title: 'UploadStatus'
} as const;

export const UserCreateSchema = {
    properties: {
        email: {
            type: 'string',
            maxLength: 255,
            format: 'email',
            title: 'Email'
        },
        is_active: {
            type: 'boolean',
            title: 'Is Active',
            default: true
        },
        is_superuser: {
            type: 'boolean',
            title: 'Is Superuser',
            default: false
        },
        first_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'First Name'
        },
        last_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Last Name'
        }
    },
    type: 'object',
    required: [
        'email'
    ],
    title: 'UserCreate'
} as const;

export const UserPublicSchema = {
    properties: {
        email: {
            type: 'string',
            maxLength: 255,
            format: 'email',
            title: 'Email'
        },
        is_active: {
            type: 'boolean',
            title: 'Is Active',
            default: true
        },
        is_superuser: {
            type: 'boolean',
            title: 'Is Superuser',
            default: false
        },
        first_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'First Name'
        },
        last_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Last Name'
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        }
    },
    type: 'object',
    required: [
        'email',
        'id'
    ],
    title: 'UserPublic'
} as const;

export const UserUpdateSchema = {
    properties: {
        email: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255,
                    format: 'email'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Email'
        },
        password: {
            anyOf: [
                {
                    type: 'null'
                }
            ],
            title: 'Password'
        },
        is_active: {
            anyOf: [
                {
                    type: 'boolean'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Is Active'
        },
        is_superuser: {
            anyOf: [
                {
                    type: 'boolean'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Is Superuser'
        },
        first_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'First Name'
        },
        last_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Last Name'
        }
    },
    type: 'object',
    title: 'UserUpdate'
} as const;

export const UserUpdateMeSchema = {
    properties: {
        first_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'First Name'
        },
        last_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Last Name'
        },
        email: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255,
                    format: 'email'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Email'
        }
    },
    type: 'object',
    title: 'UserUpdateMe'
} as const;

export const UsersPublicSchema = {
    properties: {
        data: {
            items: {
                $ref: '#/components/schemas/UserPublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: [
        'data',
        'count'
    ],
    title: 'UsersPublic'
} as const;

export const ValidationErrorSchema = {
    properties: {
        loc: {
            items: {
                anyOf: [
                    {
                        type: 'string'
                    },
                    {
                        type: 'integer'
                    }
                ]
            },
            type: 'array',
            title: 'Location'
        },
        msg: {
            type: 'string',
            title: 'Message'
        },
        type: {
            type: 'string',
            title: 'Error Type'
        }
    },
    type: 'object',
    required: [
        'loc',
        'msg',
        'type'
    ],
    title: 'ValidationError'
} as const;

export const UserCreateWritableSchema = {
    properties: {
        email: {
            type: 'string',
            maxLength: 255,
            format: 'email',
            title: 'Email'
        },
        is_active: {
            type: 'boolean',
            title: 'Is Active',
            default: true
        },
        is_superuser: {
            type: 'boolean',
            title: 'Is Superuser',
            default: false
        },
        first_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'First Name'
        },
        last_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Last Name'
        },
        password: {
            type: 'string',
            maxLength: 40,
            minLength: 8,
            format: 'password',
            title: 'Password',
            writeOnly: true
        }
    },
    type: 'object',
    required: [
        'email',
        'password'
    ],
    title: 'UserCreate'
} as const;

export const UserUpdateWritableSchema = {
    properties: {
        email: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255,
                    format: 'email'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Email'
        },
        password: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 40,
                    minLength: 8,
                    format: 'password',
                    writeOnly: true
                },
                {
                    type: 'null'
                }
            ],
            title: 'Password'
        },
        is_active: {
            anyOf: [
                {
                    type: 'boolean'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Is Active'
        },
        is_superuser: {
            anyOf: [
                {
                    type: 'boolean'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Is Superuser'
        },
        first_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'First Name'
        },
        last_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Last Name'
        }
    },
    type: 'object',
    title: 'UserUpdate'
} as const;
