// This file is auto-generated by @hey-api/openapi-ts

export const Body_login_login_access_tokenSchema = {
    properties: {
        grant_type: {
            anyOf: [
                {
                    type: 'string',
                    pattern: '^password$'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Grant Type'
        },
        username: {
            type: 'string',
            title: 'Username'
        },
        password: {
            type: 'string',
            format: 'password',
            title: 'Password'
        },
        scope: {
            type: 'string',
            title: 'Scope',
            default: ''
        },
        client_id: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Client Id'
        },
        client_secret: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            format: 'password',
            title: 'Client Secret'
        }
    },
    type: 'object',
    required: [
        'username',
        'password'
    ],
    title: 'Body_login_login_access_token'
} as const;

export const ExtractionStatusSchema = {
    type: 'string',
    enum: [
        'pending',
        'in_progress',
        'completed',
        'failed'
    ],
    title: 'ExtractionStatus'
} as const;

export const HTTPValidationErrorSchema = {
    properties: {
        detail: {
            items: {
                $ref: '#/components/schemas/ValidationError'
            },
            type: 'array',
            title: 'Detail'
        }
    },
    type: 'object',
    title: 'HTTPValidationError'
} as const;

export const HealthSchema = {
    properties: {
        status: {
            type: 'string',
            title: 'Status'
        }
    },
    type: 'object',
    required: [
        'status'
    ],
    title: 'Health'
} as const;

export const LabelCreateSchema = {
    properties: {
        product_type: {
            type: 'string',
            title: 'Product Type'
        },
        product_id: {
            anyOf: [
                {
                    type: 'string',
                    format: 'uuid'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Product Id'
        }
    },
    type: 'object',
    required: [
        'product_type'
    ],
    title: 'LabelCreate'
} as const;

export const LabelDetailSchema = {
    properties: {
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        extraction_status: {
            $ref: '#/components/schemas/ExtractionStatus'
        },
        verification_status: {
            $ref: '#/components/schemas/VerificationStatus'
        },
        extraction_error_message: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Extraction Error Message'
        },
        created_at: {
            type: 'string',
            format: 'date-time',
            title: 'Created At'
        },
        updated_at: {
            type: 'string',
            format: 'date-time',
            title: 'Updated At'
        },
        images: {
            items: {
                $ref: '#/components/schemas/LabelImageDetail'
            },
            type: 'array',
            title: 'Images'
        },
        has_label_data: {
            type: 'boolean',
            title: 'Has Label Data',
            default: false
        }
    },
    type: 'object',
    required: [
        'id',
        'extraction_status',
        'verification_status',
        'created_at',
        'updated_at'
    ],
    title: 'LabelDetail'
} as const;

export const LabelImageDetailSchema = {
    properties: {
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        display_filename: {
            type: 'string',
            title: 'Display Filename'
        },
        storage_file_path: {
            type: 'string',
            title: 'Storage File Path'
        },
        sequence_order: {
            type: 'integer',
            title: 'Sequence Order'
        },
        status: {
            $ref: '#/components/schemas/UploadStatus'
        },
        presigned_url: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Presigned Url'
        },
        current_image_count: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Current Image Count'
        }
    },
    type: 'object',
    required: [
        'id',
        'display_filename',
        'storage_file_path',
        'sequence_order',
        'status'
    ],
    title: 'LabelImageDetail'
} as const;

export const LabelPublicSchema = {
    properties: {
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        }
    },
    type: 'object',
    required: [
        'id'
    ],
    title: 'LabelPublic'
} as const;

export const LimitOffsetPage_LabelPublic_Schema = {
    properties: {
        items: {
            items: {
                $ref: '#/components/schemas/LabelPublic'
            },
            type: 'array',
            title: 'Items'
        },
        total: {
            type: 'integer',
            minimum: 0,
            title: 'Total'
        },
        limit: {
            type: 'integer',
            minimum: 1,
            title: 'Limit'
        },
        offset: {
            type: 'integer',
            minimum: 0,
            title: 'Offset'
        }
    },
    type: 'object',
    required: [
        'items',
        'total',
        'limit',
        'offset'
    ],
    title: 'LimitOffsetPage[LabelPublic]'
} as const;

export const LimitOffsetPage_ProductPublic_Schema = {
    properties: {
        items: {
            items: {
                $ref: '#/components/schemas/ProductPublic'
            },
            type: 'array',
            title: 'Items'
        },
        total: {
            type: 'integer',
            minimum: 0,
            title: 'Total'
        },
        limit: {
            type: 'integer',
            minimum: 1,
            title: 'Limit'
        },
        offset: {
            type: 'integer',
            minimum: 0,
            title: 'Offset'
        }
    },
    type: 'object',
    required: [
        'items',
        'total',
        'limit',
        'offset'
    ],
    title: 'LimitOffsetPage[ProductPublic]'
} as const;

export const MessageSchema = {
    properties: {
        message: {
            type: 'string',
            title: 'Message'
        }
    },
    type: 'object',
    required: [
        'message'
    ],
    title: 'Message'
} as const;

export const NewPasswordSchema = {
    properties: {
        token: {
            type: 'string',
            title: 'Token'
        },
        new_password: {
            type: 'string',
            title: 'New Password'
        }
    },
    type: 'object',
    required: [
        'token',
        'new_password'
    ],
    title: 'NewPassword'
} as const;

export const PresignedDownloadUrlResponseSchema = {
    properties: {
        presigned_url: {
            type: 'string',
            title: 'Presigned Url'
        }
    },
    type: 'object',
    required: [
        'presigned_url'
    ],
    title: 'PresignedDownloadUrlResponse',
    description: 'Response schema for presigned download URL request.'
} as const;

export const PresignedUrlRequestSchema = {
    properties: {
        display_filename: {
            type: 'string',
            title: 'Display Filename'
        },
        content_type: {
            type: 'string',
            enum: [
                'image/png',
                'image/jpeg',
                'image/webp'
            ],
            title: 'Content Type'
        },
        sequence_order: {
            type: 'integer',
            minimum: 1,
            title: 'Sequence Order'
        }
    },
    type: 'object',
    required: [
        'display_filename',
        'content_type',
        'sequence_order'
    ],
    title: 'PresignedUrlRequest',
    description: 'Request schema for individual presigned URL generation.'
} as const;

export const PrivateUserCreateSchema = {
    properties: {
        email: {
            type: 'string',
            format: 'email',
            title: 'Email'
        },
        password: {
            type: 'string',
            title: 'Password'
        },
        first_name: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'First Name'
        },
        last_name: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Last Name'
        }
    },
    type: 'object',
    required: [
        'email',
        'password'
    ],
    title: 'PrivateUserCreate'
} as const;

export const ProductPublicSchema = {
    properties: {
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        }
    },
    type: 'object',
    required: [
        'id'
    ],
    title: 'ProductPublic'
} as const;

export const ReadinessSchema = {
    properties: {
        status: {
            type: 'string',
            title: 'Status'
        },
        database: {
            type: 'string',
            title: 'Database'
        }
    },
    type: 'object',
    required: [
        'status',
        'database'
    ],
    title: 'Readiness'
} as const;

export const TokenSchema = {
    properties: {
        access_token: {
            type: 'string',
            title: 'Access Token'
        },
        token_type: {
            type: 'string',
            title: 'Token Type',
            default: 'bearer'
        }
    },
    type: 'object',
    required: [
        'access_token'
    ],
    title: 'Token'
} as const;

export const UpdatePasswordSchema = {
    properties: {
        current_password: {
            type: 'string',
            maxLength: 40,
            minLength: 8,
            format: 'password',
            title: 'Current Password',
            writeOnly: true
        },
        new_password: {
            type: 'string',
            maxLength: 40,
            minLength: 8,
            format: 'password',
            title: 'New Password',
            writeOnly: true
        }
    },
    type: 'object',
    required: [
        'current_password',
        'new_password'
    ],
    title: 'UpdatePassword'
} as const;

export const UploadCompletionRequestSchema = {
    properties: {
        storage_file_path: {
            type: 'string',
            title: 'Storage File Path'
        }
    },
    type: 'object',
    required: [
        'storage_file_path'
    ],
    title: 'UploadCompletionRequest',
    description: 'Request schema for upload completion notification.'
} as const;

export const UploadStatusSchema = {
    type: 'string',
    enum: [
        'pending',
        'completed'
    ],
    title: 'UploadStatus'
} as const;

export const UserCreateSchema = {
    properties: {
        email: {
            type: 'string',
            maxLength: 255,
            format: 'email',
            title: 'Email'
        },
        is_active: {
            type: 'boolean',
            title: 'Is Active',
            default: true
        },
        is_superuser: {
            type: 'boolean',
            title: 'Is Superuser',
            default: false
        },
        first_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'First Name'
        },
        last_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Last Name'
        }
    },
    type: 'object',
    required: [
        'email'
    ],
    title: 'UserCreate'
} as const;

export const UserPublicSchema = {
    properties: {
        email: {
            type: 'string',
            maxLength: 255,
            format: 'email',
            title: 'Email'
        },
        is_active: {
            type: 'boolean',
            title: 'Is Active',
            default: true
        },
        is_superuser: {
            type: 'boolean',
            title: 'Is Superuser',
            default: false
        },
        first_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'First Name'
        },
        last_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Last Name'
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        }
    },
    type: 'object',
    required: [
        'email',
        'id'
    ],
    title: 'UserPublic'
} as const;

export const UserUpdateSchema = {
    properties: {
        email: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255,
                    format: 'email'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Email'
        },
        password: {
            anyOf: [
                {
                    type: 'null'
                }
            ],
            title: 'Password'
        },
        is_active: {
            anyOf: [
                {
                    type: 'boolean'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Is Active'
        },
        is_superuser: {
            anyOf: [
                {
                    type: 'boolean'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Is Superuser'
        },
        first_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'First Name'
        },
        last_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Last Name'
        }
    },
    type: 'object',
    title: 'UserUpdate'
} as const;

export const UserUpdateMeSchema = {
    properties: {
        first_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'First Name'
        },
        last_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Last Name'
        },
        email: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255,
                    format: 'email'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Email'
        }
    },
    type: 'object',
    title: 'UserUpdateMe'
} as const;

export const UsersPublicSchema = {
    properties: {
        data: {
            items: {
                $ref: '#/components/schemas/UserPublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: [
        'data',
        'count'
    ],
    title: 'UsersPublic'
} as const;

export const ValidationErrorSchema = {
    properties: {
        loc: {
            items: {
                anyOf: [
                    {
                        type: 'string'
                    },
                    {
                        type: 'integer'
                    }
                ]
            },
            type: 'array',
            title: 'Location'
        },
        msg: {
            type: 'string',
            title: 'Message'
        },
        type: {
            type: 'string',
            title: 'Error Type'
        }
    },
    type: 'object',
    required: [
        'loc',
        'msg',
        'type'
    ],
    title: 'ValidationError'
} as const;

export const VerificationStatusSchema = {
    type: 'string',
    enum: [
        'not_started',
        'in_progress',
        'completed'
    ],
    title: 'VerificationStatus'
} as const;

export const UserCreateWritableSchema = {
    properties: {
        email: {
            type: 'string',
            maxLength: 255,
            format: 'email',
            title: 'Email'
        },
        is_active: {
            type: 'boolean',
            title: 'Is Active',
            default: true
        },
        is_superuser: {
            type: 'boolean',
            title: 'Is Superuser',
            default: false
        },
        first_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'First Name'
        },
        last_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Last Name'
        },
        password: {
            type: 'string',
            maxLength: 40,
            minLength: 8,
            format: 'password',
            title: 'Password',
            writeOnly: true
        }
    },
    type: 'object',
    required: [
        'email',
        'password'
    ],
    title: 'UserCreate'
} as const;

export const UserUpdateWritableSchema = {
    properties: {
        email: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255,
                    format: 'email'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Email'
        },
        password: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 40,
                    minLength: 8,
                    format: 'password',
                    writeOnly: true
                },
                {
                    type: 'null'
                }
            ],
            title: 'Password'
        },
        is_active: {
            anyOf: [
                {
                    type: 'boolean'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Is Active'
        },
        is_superuser: {
            anyOf: [
                {
                    type: 'boolean'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Is Superuser'
        },
        first_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'First Name'
        },
        last_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Last Name'
        }
    },
    type: 'object',
    title: 'UserUpdate'
} as const;
