// This file is auto-generated by @hey-api/openapi-ts

import {
  type Client,
  type Options as Options2,
  type TDataShape,
  urlSearchParamsBodySerializer,
} from "./client"
import { client } from "./client.gen"
import type {
  HealthLivenessData,
  HealthLivenessResponses,
  HealthReadinessData,
  HealthReadinessResponses,
  LoginLoginAccessTokenData,
  LoginLoginAccessTokenErrors,
  LoginLoginAccessTokenResponses,
  LoginRecoverPasswordData,
  LoginRecoverPasswordErrors,
  LoginRecoverPasswordHtmlContentData,
  LoginRecoverPasswordHtmlContentErrors,
  LoginRecoverPasswordHtmlContentResponses,
  LoginRecoverPasswordResponses,
  LoginResetPasswordData,
  LoginResetPasswordErrors,
  LoginResetPasswordResponses,
  LoginTestTokenData,
  LoginTestTokenResponses,
  PrivateCreateUserNoVerificationData,
  PrivateCreateUserNoVerificationErrors,
  PrivateCreateUserNoVerificationResponses,
  UsersCreateUserData,
  UsersCreateUserErrors,
  UsersCreateUserResponses,
  UsersDeleteUserData,
  UsersDeleteUserErrors,
  UsersDeleteUserMeData,
  UsersDeleteUserMeResponses,
  UsersDeleteUserResponses,
  UsersReadUserByIdData,
  UsersReadUserByIdErrors,
  UsersReadUserByIdResponses,
  UsersReadUserMeData,
  UsersReadUserMeResponses,
  UsersReadUsersData,
  UsersReadUsersErrors,
  UsersReadUsersResponses,
  UsersUpdatePasswordMeData,
  UsersUpdatePasswordMeErrors,
  UsersUpdatePasswordMeResponses,
  UsersUpdateUserData,
  UsersUpdateUserErrors,
  UsersUpdateUserMeData,
  UsersUpdateUserMeErrors,
  UsersUpdateUserMeResponses,
  UsersUpdateUserResponses,
} from "./types.gen"

export type Options<
  TData extends TDataShape = TDataShape,
  ThrowOnError extends boolean = boolean,
> = Options2<TData, ThrowOnError> & {
  /**
   * You can provide a client instance returned by `createClient()` instead of
   * individual options. This might be also useful if you want to implement a
   * custom client.
   */
  client?: Client
  /**
   * You can pass arbitrary values through the `meta` object. This can be
   * used to access values that aren't defined as part of the SDK function.
   */
  meta?: Record<string, unknown>
}

export class HealthService {
  /**
   * Liveness
   *
   * Liveness probe - is the application running?
   */
  public static liveness<ThrowOnError extends boolean = false>(
    options?: Options<HealthLivenessData, ThrowOnError>,
  ) {
    return (options?.client ?? client).get<
      HealthLivenessResponses,
      unknown,
      ThrowOnError
    >({
      responseType: "json",
      url: "/healthz",
      ...options,
    })
  }

  /**
   * Readiness
   *
   * Readiness probe - can the application handle requests?
   */
  public static readiness<ThrowOnError extends boolean = false>(
    options?: Options<HealthReadinessData, ThrowOnError>,
  ) {
    return (options?.client ?? client).get<
      HealthReadinessResponses,
      unknown,
      ThrowOnError
    >({
      responseType: "json",
      url: "/readyz",
      ...options,
    })
  }
}

export class LoginService {
  /**
   * Login Access Token
   *
   * OAuth2 compatible token login, get an access token for future requests.
   */
  public static loginAccessToken<ThrowOnError extends boolean = false>(
    options: Options<LoginLoginAccessTokenData, ThrowOnError>,
  ) {
    return (options.client ?? client).post<
      LoginLoginAccessTokenResponses,
      LoginLoginAccessTokenErrors,
      ThrowOnError
    >({
      ...urlSearchParamsBodySerializer,
      responseType: "json",
      url: "/api/v1/login/access-token",
      ...options,
      headers: {
        "Content-Type": "application/x-www-form-urlencoded",
        ...options.headers,
      },
    })
  }

  /**
   * Test Token
   *
   * Test access token.
   */
  public static testToken<ThrowOnError extends boolean = false>(
    options?: Options<LoginTestTokenData, ThrowOnError>,
  ) {
    return (options?.client ?? client).post<
      LoginTestTokenResponses,
      unknown,
      ThrowOnError
    >({
      responseType: "json",
      security: [{ scheme: "bearer", type: "http" }],
      url: "/api/v1/login/test-token",
      ...options,
    })
  }

  /**
   * Recover Password
   *
   * Password Recovery.
   */
  public static recoverPassword<ThrowOnError extends boolean = false>(
    options: Options<LoginRecoverPasswordData, ThrowOnError>,
  ) {
    return (options.client ?? client).post<
      LoginRecoverPasswordResponses,
      LoginRecoverPasswordErrors,
      ThrowOnError
    >({
      responseType: "json",
      url: "/api/v1/password-recovery/{email}",
      ...options,
    })
  }

  /**
   * Reset Password
   *
   * Reset password.
   */
  public static resetPassword<ThrowOnError extends boolean = false>(
    options: Options<LoginResetPasswordData, ThrowOnError>,
  ) {
    return (options.client ?? client).post<
      LoginResetPasswordResponses,
      LoginResetPasswordErrors,
      ThrowOnError
    >({
      responseType: "json",
      url: "/api/v1/reset-password/",
      ...options,
      headers: {
        "Content-Type": "application/json",
        ...options.headers,
      },
    })
  }

  /**
   * Recover Password Html Content
   *
   * HTML Content for Password Recovery (dev/testing only).
   */
  public static recoverPasswordHtmlContent<
    ThrowOnError extends boolean = false,
  >(options: Options<LoginRecoverPasswordHtmlContentData, ThrowOnError>) {
    return (options.client ?? client).post<
      LoginRecoverPasswordHtmlContentResponses,
      LoginRecoverPasswordHtmlContentErrors,
      ThrowOnError
    >({
      responseType: "text",
      security: [{ scheme: "bearer", type: "http" }],
      url: "/api/v1/password-recovery-html-content/{email}",
      ...options,
    })
  }
}

export class UsersService {
  /**
   * Read Users
   *
   * List all users (superuser only).
   */
  public static readUsers<ThrowOnError extends boolean = false>(
    options?: Options<UsersReadUsersData, ThrowOnError>,
  ) {
    return (options?.client ?? client).get<
      UsersReadUsersResponses,
      UsersReadUsersErrors,
      ThrowOnError
    >({
      responseType: "json",
      security: [{ scheme: "bearer", type: "http" }],
      url: "/api/v1/users",
      ...options,
    })
  }

  /**
   * Create User
   *
   * Create new user (superuser only).
   */
  public static createUser<ThrowOnError extends boolean = false>(
    options: Options<UsersCreateUserData, ThrowOnError>,
  ) {
    return (options.client ?? client).post<
      UsersCreateUserResponses,
      UsersCreateUserErrors,
      ThrowOnError
    >({
      responseType: "json",
      security: [{ scheme: "bearer", type: "http" }],
      url: "/api/v1/users",
      ...options,
      headers: {
        "Content-Type": "application/json",
        ...options.headers,
      },
    })
  }

  /**
   * Delete User Me
   *
   * Delete current user.
   */
  public static deleteUserMe<ThrowOnError extends boolean = false>(
    options?: Options<UsersDeleteUserMeData, ThrowOnError>,
  ) {
    return (options?.client ?? client).delete<
      UsersDeleteUserMeResponses,
      unknown,
      ThrowOnError
    >({
      responseType: "json",
      security: [{ scheme: "bearer", type: "http" }],
      url: "/api/v1/users/me",
      ...options,
    })
  }

  /**
   * Read User Me
   *
   * Get current user.
   */
  public static readUserMe<ThrowOnError extends boolean = false>(
    options?: Options<UsersReadUserMeData, ThrowOnError>,
  ) {
    return (options?.client ?? client).get<
      UsersReadUserMeResponses,
      unknown,
      ThrowOnError
    >({
      responseType: "json",
      security: [{ scheme: "bearer", type: "http" }],
      url: "/api/v1/users/me",
      ...options,
    })
  }

  /**
   * Update User Me
   *
   * Update current user.
   */
  public static updateUserMe<ThrowOnError extends boolean = false>(
    options: Options<UsersUpdateUserMeData, ThrowOnError>,
  ) {
    return (options.client ?? client).patch<
      UsersUpdateUserMeResponses,
      UsersUpdateUserMeErrors,
      ThrowOnError
    >({
      responseType: "json",
      security: [{ scheme: "bearer", type: "http" }],
      url: "/api/v1/users/me",
      ...options,
      headers: {
        "Content-Type": "application/json",
        ...options.headers,
      },
    })
  }

  /**
   * Update Password Me
   *
   * Update current user password.
   */
  public static updatePasswordMe<ThrowOnError extends boolean = false>(
    options: Options<UsersUpdatePasswordMeData, ThrowOnError>,
  ) {
    return (options.client ?? client).patch<
      UsersUpdatePasswordMeResponses,
      UsersUpdatePasswordMeErrors,
      ThrowOnError
    >({
      responseType: "json",
      security: [{ scheme: "bearer", type: "http" }],
      url: "/api/v1/users/me/password",
      ...options,
      headers: {
        "Content-Type": "application/json",
        ...options.headers,
      },
    })
  }

  /**
   * Delete User
   *
   * Delete user (superuser only).
   */
  public static deleteUser<ThrowOnError extends boolean = false>(
    options: Options<UsersDeleteUserData, ThrowOnError>,
  ) {
    return (options.client ?? client).delete<
      UsersDeleteUserResponses,
      UsersDeleteUserErrors,
      ThrowOnError
    >({
      responseType: "json",
      security: [{ scheme: "bearer", type: "http" }],
      url: "/api/v1/users/{user_id}",
      ...options,
    })
  }

  /**
   * Read User By Id
   *
   * Get user by ID (superuser only).
   */
  public static readUserById<ThrowOnError extends boolean = false>(
    options: Options<UsersReadUserByIdData, ThrowOnError>,
  ) {
    return (options.client ?? client).get<
      UsersReadUserByIdResponses,
      UsersReadUserByIdErrors,
      ThrowOnError
    >({
      responseType: "json",
      security: [{ scheme: "bearer", type: "http" }],
      url: "/api/v1/users/{user_id}",
      ...options,
    })
  }

  /**
   * Update User
   *
   * Update user (superuser only).
   */
  public static updateUser<ThrowOnError extends boolean = false>(
    options: Options<UsersUpdateUserData, ThrowOnError>,
  ) {
    return (options.client ?? client).patch<
      UsersUpdateUserResponses,
      UsersUpdateUserErrors,
      ThrowOnError
    >({
      responseType: "json",
      security: [{ scheme: "bearer", type: "http" }],
      url: "/api/v1/users/{user_id}",
      ...options,
      headers: {
        "Content-Type": "application/json",
        ...options.headers,
      },
    })
  }
}

export class PrivateService {
  /**
   * Create User No Verification
   *
   * Create user without email verification - for testing only.
   */
  public static createUserNoVerification<ThrowOnError extends boolean = false>(
    options: Options<PrivateCreateUserNoVerificationData, ThrowOnError>,
  ) {
    return (options.client ?? client).post<
      PrivateCreateUserNoVerificationResponses,
      PrivateCreateUserNoVerificationErrors,
      ThrowOnError
    >({
      responseType: "json",
      url: "/api/v1/private/users/",
      ...options,
      headers: {
        "Content-Type": "application/json",
        ...options.headers,
      },
    })
  }
}
