// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseURL: `${string}://${string}` | (string & {});
};

/**
 * Body_login_login_access_token
 */
export type BodyLoginLoginAccessToken = {
    /**
     * Grant Type
     */
    grant_type?: string | null;
    /**
     * Username
     */
    username: string;
    /**
     * Password
     */
    password: string;
    /**
     * Scope
     */
    scope?: string;
    /**
     * Client Id
     */
    client_id?: string | null;
    /**
     * Client Secret
     */
    client_secret?: string | null;
};

/**
 * ExtractionStatus
 */
export type ExtractionStatus = 'pending' | 'in_progress' | 'completed' | 'failed';

/**
 * HTTPValidationError
 */
export type HttpValidationError = {
    /**
     * Detail
     */
    detail?: Array<ValidationError>;
};

/**
 * Health
 */
export type Health = {
    /**
     * Status
     */
    status: string;
};

/**
 * LabelCreate
 */
export type LabelCreate = {
    /**
     * Product Type
     */
    product_type: string;
    /**
     * Product Id
     */
    product_id?: string | null;
};

/**
 * LabelCreated
 *
 * Response schema for label creation.
 */
export type LabelCreated = {
    /**
     * Id
     */
    id: string;
};

/**
 * LabelDetail
 */
export type LabelDetail = {
    /**
     * Id
     */
    id: string;
    /**
     * Product Id
     */
    product_id?: string | null;
    /**
     * Created By Id
     */
    created_by_id: string;
    extraction_status: ExtractionStatus;
    verification_status: VerificationStatus;
    /**
     * Extraction Error Message
     */
    extraction_error_message?: string | null;
    /**
     * Created At
     */
    created_at: string;
    /**
     * Updated At
     */
    updated_at: string;
    product_type: ProductTypePublic;
    created_by: UserPublic;
    /**
     * Images
     */
    images?: Array<LabelImageDetail>;
};

/**
 * LabelImageDetail
 */
export type LabelImageDetail = {
    /**
     * Id
     */
    id: string;
    /**
     * Label Id
     */
    label_id: string;
    /**
     * Display Filename
     */
    display_filename: string;
    /**
     * File Path
     */
    file_path: string;
    /**
     * Sequence Order
     */
    sequence_order: number;
    status: UploadStatus;
    /**
     * Created At
     */
    created_at: string;
    /**
     * Updated At
     */
    updated_at: string;
    /**
     * Current Image Count
     */
    current_image_count?: number | null;
};

/**
 * LabelListItem
 *
 * Schema for label list items.
 */
export type LabelListItem = {
    /**
     * Id
     */
    id: string;
    extraction_status: ExtractionStatus;
    verification_status: VerificationStatus;
    /**
     * Extraction Error Message
     */
    extraction_error_message?: string | null;
    /**
     * Created At
     */
    created_at: string;
    /**
     * Updated At
     */
    updated_at: string;
    product?: ProductPublic | null;
};

/**
 * LimitOffsetPage[LabelListItem]
 */
export type LimitOffsetPageLabelListItem = {
    /**
     * Items
     */
    items: Array<LabelListItem>;
    /**
     * Total
     */
    total: number;
    /**
     * Limit
     */
    limit: number;
    /**
     * Offset
     */
    offset: number;
};

/**
 * LimitOffsetPage[ProductPublic]
 */
export type LimitOffsetPageProductPublic = {
    /**
     * Items
     */
    items: Array<ProductPublic>;
    /**
     * Total
     */
    total: number;
    /**
     * Limit
     */
    limit: number;
    /**
     * Offset
     */
    offset: number;
};

/**
 * Message
 */
export type Message = {
    /**
     * Message
     */
    message: string;
};

/**
 * NewPassword
 */
export type NewPassword = {
    /**
     * Token
     */
    token: string;
    /**
     * New Password
     */
    new_password: string;
};

/**
 * PresignedDownloadUrlResponse
 *
 * Response schema for presigned download URL request.
 */
export type PresignedDownloadUrlResponse = {
    /**
     * Presigned Url
     */
    presigned_url: string;
};

/**
 * PresignedUploadUrlResponse
 *
 * Response schema for presigned upload URL request.
 */
export type PresignedUploadUrlResponse = {
    /**
     * Url
     */
    url: string;
    /**
     * Expires At
     */
    expires_at: string;
};

/**
 * PresignedUrlRequest
 *
 * Request schema for individual presigned URL generation.
 */
export type PresignedUrlRequest = {
    /**
     * Display Filename
     */
    display_filename: string;
    /**
     * Content Type
     */
    content_type: 'image/png' | 'image/jpeg' | 'image/webp';
    /**
     * Sequence Order
     */
    sequence_order: number;
};

/**
 * PrivateUserCreate
 */
export type PrivateUserCreate = {
    /**
     * Email
     */
    email: string;
    /**
     * Password
     */
    password: string;
    /**
     * First Name
     */
    first_name?: string | null;
    /**
     * Last Name
     */
    last_name?: string | null;
};

/**
 * ProductPublic
 */
export type ProductPublic = {
    /**
     * Id
     */
    id: string;
    /**
     * Name En
     */
    name_en?: string | null;
    /**
     * Name Fr
     */
    name_fr?: string | null;
    /**
     * Registration Number
     */
    registration_number: string;
};

/**
 * ProductTypePublic
 */
export type ProductTypePublic = {
    /**
     * Code
     */
    code: string;
    /**
     * Name En
     */
    name_en?: string | null;
    /**
     * Name Fr
     */
    name_fr?: string | null;
    /**
     * Is Active
     */
    is_active?: boolean;
    /**
     * Id
     */
    id: string;
    /**
     * Created At
     */
    created_at: string;
    /**
     * Updated At
     */
    updated_at: string;
};

/**
 * Readiness
 */
export type Readiness = {
    /**
     * Status
     */
    status: string;
    /**
     * Database
     */
    database: string;
};

/**
 * Token
 */
export type Token = {
    /**
     * Access Token
     */
    access_token: string;
    /**
     * Token Type
     */
    token_type?: string;
};

/**
 * UpdatePassword
 */
export type UpdatePassword = {
    /**
     * Current Password
     */
    current_password: string;
    /**
     * New Password
     */
    new_password: string;
};

/**
 * UploadCompletionRequest
 *
 * Request schema for upload completion notification.
 */
export type UploadCompletionRequest = {
    /**
     * Storage File Path
     */
    storage_file_path: string;
};

/**
 * UploadStatus
 */
export type UploadStatus = 'pending' | 'completed';

/**
 * UserCreate
 */
export type UserCreate = {
    /**
     * Email
     */
    email: string;
    /**
     * Is Active
     */
    is_active?: boolean;
    /**
     * Is Superuser
     */
    is_superuser?: boolean;
    /**
     * First Name
     */
    first_name?: string | null;
    /**
     * Last Name
     */
    last_name?: string | null;
};

/**
 * UserPublic
 */
export type UserPublic = {
    /**
     * Email
     */
    email: string;
    /**
     * Is Active
     */
    is_active?: boolean;
    /**
     * Is Superuser
     */
    is_superuser?: boolean;
    /**
     * First Name
     */
    first_name?: string | null;
    /**
     * Last Name
     */
    last_name?: string | null;
    /**
     * Id
     */
    id: string;
};

/**
 * UserUpdate
 */
export type UserUpdate = {
    /**
     * Email
     */
    email?: string | null;
    /**
     * Password
     */
    password?: null;
    /**
     * Is Active
     */
    is_active?: boolean | null;
    /**
     * Is Superuser
     */
    is_superuser?: boolean | null;
    /**
     * First Name
     */
    first_name?: string | null;
    /**
     * Last Name
     */
    last_name?: string | null;
};

/**
 * UserUpdateMe
 */
export type UserUpdateMe = {
    /**
     * First Name
     */
    first_name?: string | null;
    /**
     * Last Name
     */
    last_name?: string | null;
    /**
     * Email
     */
    email?: string | null;
};

/**
 * UsersPublic
 */
export type UsersPublic = {
    /**
     * Data
     */
    data: Array<UserPublic>;
    /**
     * Count
     */
    count: number;
};

/**
 * ValidationError
 */
export type ValidationError = {
    /**
     * Location
     */
    loc: Array<string | number>;
    /**
     * Message
     */
    msg: string;
    /**
     * Error Type
     */
    type: string;
};

/**
 * VerificationStatus
 */
export type VerificationStatus = 'not_started' | 'in_progress' | 'completed';

/**
 * UserCreate
 */
export type UserCreateWritable = {
    /**
     * Email
     */
    email: string;
    /**
     * Is Active
     */
    is_active?: boolean;
    /**
     * Is Superuser
     */
    is_superuser?: boolean;
    /**
     * First Name
     */
    first_name?: string | null;
    /**
     * Last Name
     */
    last_name?: string | null;
    /**
     * Password
     */
    password: string;
};

/**
 * UserUpdate
 */
export type UserUpdateWritable = {
    /**
     * Email
     */
    email?: string | null;
    /**
     * Password
     */
    password?: string | null;
    /**
     * Is Active
     */
    is_active?: boolean | null;
    /**
     * Is Superuser
     */
    is_superuser?: boolean | null;
    /**
     * First Name
     */
    first_name?: string | null;
    /**
     * Last Name
     */
    last_name?: string | null;
};

export type HealthLivenessData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/healthz';
};

export type HealthLivenessResponses = {
    /**
     * Successful Response
     */
    200: Health;
};

export type HealthLivenessResponse = HealthLivenessResponses[keyof HealthLivenessResponses];

export type HealthReadinessData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/readyz';
};

export type HealthReadinessResponses = {
    /**
     * Successful Response
     */
    200: Readiness;
};

export type HealthReadinessResponse = HealthReadinessResponses[keyof HealthReadinessResponses];

export type LoginLoginAccessTokenData = {
    body: BodyLoginLoginAccessToken;
    path?: never;
    query?: never;
    url: '/api/v1/login/access-token';
};

export type LoginLoginAccessTokenErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type LoginLoginAccessTokenError = LoginLoginAccessTokenErrors[keyof LoginLoginAccessTokenErrors];

export type LoginLoginAccessTokenResponses = {
    /**
     * Successful Response
     */
    200: Token;
};

export type LoginLoginAccessTokenResponse = LoginLoginAccessTokenResponses[keyof LoginLoginAccessTokenResponses];

export type LoginTestTokenData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/login/test-token';
};

export type LoginTestTokenResponses = {
    /**
     * Successful Response
     */
    200: UserPublic;
};

export type LoginTestTokenResponse = LoginTestTokenResponses[keyof LoginTestTokenResponses];

export type LoginRecoverPasswordData = {
    body?: never;
    path: {
        /**
         * Email
         */
        email: string;
    };
    query?: never;
    url: '/api/v1/password-recovery/{email}';
};

export type LoginRecoverPasswordErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type LoginRecoverPasswordError = LoginRecoverPasswordErrors[keyof LoginRecoverPasswordErrors];

export type LoginRecoverPasswordResponses = {
    /**
     * Successful Response
     */
    200: Message;
};

export type LoginRecoverPasswordResponse = LoginRecoverPasswordResponses[keyof LoginRecoverPasswordResponses];

export type LoginResetPasswordData = {
    body: NewPassword;
    path?: never;
    query?: never;
    url: '/api/v1/reset-password/';
};

export type LoginResetPasswordErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type LoginResetPasswordError = LoginResetPasswordErrors[keyof LoginResetPasswordErrors];

export type LoginResetPasswordResponses = {
    /**
     * Successful Response
     */
    200: Message;
};

export type LoginResetPasswordResponse = LoginResetPasswordResponses[keyof LoginResetPasswordResponses];

export type LoginRecoverPasswordHtmlContentData = {
    body?: never;
    path: {
        /**
         * Email
         */
        email: string;
    };
    query?: never;
    url: '/api/v1/password-recovery-html-content/{email}';
};

export type LoginRecoverPasswordHtmlContentErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type LoginRecoverPasswordHtmlContentError = LoginRecoverPasswordHtmlContentErrors[keyof LoginRecoverPasswordHtmlContentErrors];

export type LoginRecoverPasswordHtmlContentResponses = {
    /**
     * Successful Response
     */
    200: string;
};

export type LoginRecoverPasswordHtmlContentResponse = LoginRecoverPasswordHtmlContentResponses[keyof LoginRecoverPasswordHtmlContentResponses];

export type UsersReadUsersData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Skip
         */
        skip?: number;
        /**
         * Limit
         */
        limit?: number;
    };
    url: '/api/v1/users';
};

export type UsersReadUsersErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UsersReadUsersError = UsersReadUsersErrors[keyof UsersReadUsersErrors];

export type UsersReadUsersResponses = {
    /**
     * Successful Response
     */
    200: UsersPublic;
};

export type UsersReadUsersResponse = UsersReadUsersResponses[keyof UsersReadUsersResponses];

export type UsersCreateUserData = {
    body: UserCreateWritable;
    path?: never;
    query?: never;
    url: '/api/v1/users';
};

export type UsersCreateUserErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UsersCreateUserError = UsersCreateUserErrors[keyof UsersCreateUserErrors];

export type UsersCreateUserResponses = {
    /**
     * Successful Response
     */
    201: UserPublic;
};

export type UsersCreateUserResponse = UsersCreateUserResponses[keyof UsersCreateUserResponses];

export type UsersDeleteUserMeData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/users/me';
};

export type UsersDeleteUserMeResponses = {
    /**
     * Successful Response
     */
    200: Message;
};

export type UsersDeleteUserMeResponse = UsersDeleteUserMeResponses[keyof UsersDeleteUserMeResponses];

export type UsersReadUserMeData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/users/me';
};

export type UsersReadUserMeResponses = {
    /**
     * Successful Response
     */
    200: UserPublic;
};

export type UsersReadUserMeResponse = UsersReadUserMeResponses[keyof UsersReadUserMeResponses];

export type UsersUpdateUserMeData = {
    body: UserUpdateMe;
    path?: never;
    query?: never;
    url: '/api/v1/users/me';
};

export type UsersUpdateUserMeErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UsersUpdateUserMeError = UsersUpdateUserMeErrors[keyof UsersUpdateUserMeErrors];

export type UsersUpdateUserMeResponses = {
    /**
     * Successful Response
     */
    200: UserPublic;
};

export type UsersUpdateUserMeResponse = UsersUpdateUserMeResponses[keyof UsersUpdateUserMeResponses];

export type UsersUpdatePasswordMeData = {
    body: UpdatePassword;
    path?: never;
    query?: never;
    url: '/api/v1/users/me/password';
};

export type UsersUpdatePasswordMeErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UsersUpdatePasswordMeError = UsersUpdatePasswordMeErrors[keyof UsersUpdatePasswordMeErrors];

export type UsersUpdatePasswordMeResponses = {
    /**
     * Successful Response
     */
    200: Message;
};

export type UsersUpdatePasswordMeResponse = UsersUpdatePasswordMeResponses[keyof UsersUpdatePasswordMeResponses];

export type UsersDeleteUserData = {
    body?: never;
    path: {
        /**
         * User Id
         */
        user_id: string;
    };
    query?: never;
    url: '/api/v1/users/{user_id}';
};

export type UsersDeleteUserErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UsersDeleteUserError = UsersDeleteUserErrors[keyof UsersDeleteUserErrors];

export type UsersDeleteUserResponses = {
    /**
     * Successful Response
     */
    200: Message;
};

export type UsersDeleteUserResponse = UsersDeleteUserResponses[keyof UsersDeleteUserResponses];

export type UsersReadUserByIdData = {
    body?: never;
    path: {
        /**
         * User Id
         */
        user_id: string;
    };
    query?: never;
    url: '/api/v1/users/{user_id}';
};

export type UsersReadUserByIdErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UsersReadUserByIdError = UsersReadUserByIdErrors[keyof UsersReadUserByIdErrors];

export type UsersReadUserByIdResponses = {
    /**
     * Successful Response
     */
    200: UserPublic;
};

export type UsersReadUserByIdResponse = UsersReadUserByIdResponses[keyof UsersReadUserByIdResponses];

export type UsersUpdateUserData = {
    body: UserUpdateWritable;
    path: {
        /**
         * User Id
         */
        user_id: string;
    };
    query?: never;
    url: '/api/v1/users/{user_id}';
};

export type UsersUpdateUserErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UsersUpdateUserError = UsersUpdateUserErrors[keyof UsersUpdateUserErrors];

export type UsersUpdateUserResponses = {
    /**
     * Successful Response
     */
    200: UserPublic;
};

export type UsersUpdateUserResponse = UsersUpdateUserResponses[keyof UsersUpdateUserResponses];

export type LabelsReadLabelsData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Product Type
         *
         * Product type
         */
        product_type?: string;
        /**
         * Verification Status
         *
         * Filter by verification status
         */
        verification_status?: VerificationStatus | null;
        /**
         * Extraction Status
         *
         * Filter by extraction status
         */
        extraction_status?: ExtractionStatus | null;
        /**
         * Unlinked
         *
         * Filter unlinked labels only (product_id is null)
         */
        unlinked?: boolean | null;
        /**
         * Order By
         *
         * Field to sort by
         */
        order_by?: string;
        /**
         * Order
         *
         * Sort direction (asc or desc)
         */
        order?: string;
        /**
         * Limit
         *
         * Page size limit
         */
        limit?: number;
        /**
         * Offset
         *
         * Page offset
         */
        offset?: number;
    };
    url: '/api/v1/labels';
};

export type LabelsReadLabelsErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type LabelsReadLabelsError = LabelsReadLabelsErrors[keyof LabelsReadLabelsErrors];

export type LabelsReadLabelsResponses = {
    /**
     * Successful Response
     */
    200: LimitOffsetPageLabelListItem;
};

export type LabelsReadLabelsResponse = LabelsReadLabelsResponses[keyof LabelsReadLabelsResponses];

export type LabelsCreateLabelData = {
    body: LabelCreate;
    path?: never;
    query?: never;
    url: '/api/v1/labels';
};

export type LabelsCreateLabelErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type LabelsCreateLabelError = LabelsCreateLabelErrors[keyof LabelsCreateLabelErrors];

export type LabelsCreateLabelResponses = {
    /**
     * Successful Response
     */
    201: LabelCreated;
};

export type LabelsCreateLabelResponse = LabelsCreateLabelResponses[keyof LabelsCreateLabelResponses];

export type LabelsDeleteLabelData = {
    body?: never;
    path: {
        /**
         * Label Id
         */
        label_id: string;
    };
    query?: never;
    url: '/api/v1/labels/{label_id}';
};

export type LabelsDeleteLabelErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type LabelsDeleteLabelError = LabelsDeleteLabelErrors[keyof LabelsDeleteLabelErrors];

export type LabelsDeleteLabelResponses = {
    /**
     * Successful Response
     */
    204: void;
};

export type LabelsDeleteLabelResponse = LabelsDeleteLabelResponses[keyof LabelsDeleteLabelResponses];

export type LabelsReadLabelData = {
    body?: never;
    path: {
        /**
         * Label Id
         */
        label_id: string;
    };
    query?: never;
    url: '/api/v1/labels/{label_id}';
};

export type LabelsReadLabelErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type LabelsReadLabelError = LabelsReadLabelErrors[keyof LabelsReadLabelErrors];

export type LabelsReadLabelResponses = {
    /**
     * Successful Response
     */
    200: LabelDetail;
};

export type LabelsReadLabelResponse = LabelsReadLabelResponses[keyof LabelsReadLabelResponses];

export type LabelsReadLabelImagesData = {
    body?: never;
    path: {
        /**
         * Label Id
         */
        label_id: string;
    };
    query?: never;
    url: '/api/v1/labels/{label_id}/images';
};

export type LabelsReadLabelImagesErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type LabelsReadLabelImagesError = LabelsReadLabelImagesErrors[keyof LabelsReadLabelImagesErrors];

export type LabelsReadLabelImagesResponses = {
    /**
     * Response Labels Read Label Images
     *
     * Successful Response
     */
    200: Array<LabelImageDetail>;
};

export type LabelsReadLabelImagesResponse = LabelsReadLabelImagesResponses[keyof LabelsReadLabelImagesResponses];

export type LabelsCreateLabelImageData = {
    body: PresignedUrlRequest;
    path: {
        /**
         * Label Id
         */
        label_id: string;
    };
    query?: never;
    url: '/api/v1/labels/{label_id}/images';
};

export type LabelsCreateLabelImageErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type LabelsCreateLabelImageError = LabelsCreateLabelImageErrors[keyof LabelsCreateLabelImageErrors];

export type LabelsCreateLabelImageResponses = {
    /**
     * Successful Response
     */
    201: LabelImageDetail;
};

export type LabelsCreateLabelImageResponse = LabelsCreateLabelImageResponses[keyof LabelsCreateLabelImageResponses];

export type LabelsDeleteLabelImageData = {
    body?: never;
    path: {
        /**
         * Image Id
         */
        image_id: string;
        /**
         * Label Id
         */
        label_id: string;
    };
    query?: never;
    url: '/api/v1/labels/{label_id}/images/{image_id}';
};

export type LabelsDeleteLabelImageErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type LabelsDeleteLabelImageError = LabelsDeleteLabelImageErrors[keyof LabelsDeleteLabelImageErrors];

export type LabelsDeleteLabelImageResponses = {
    /**
     * Successful Response
     */
    204: void;
};

export type LabelsDeleteLabelImageResponse = LabelsDeleteLabelImageResponses[keyof LabelsDeleteLabelImageResponses];

export type LabelsReadLabelImageData = {
    body?: never;
    path: {
        /**
         * Image Id
         */
        image_id: string;
        /**
         * Label Id
         */
        label_id: string;
    };
    query?: never;
    url: '/api/v1/labels/{label_id}/images/{image_id}';
};

export type LabelsReadLabelImageErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type LabelsReadLabelImageError = LabelsReadLabelImageErrors[keyof LabelsReadLabelImageErrors];

export type LabelsReadLabelImageResponses = {
    /**
     * Successful Response
     */
    200: LabelImageDetail;
};

export type LabelsReadLabelImageResponse = LabelsReadLabelImageResponses[keyof LabelsReadLabelImageResponses];

export type LabelsCompleteLabelImageUploadData = {
    body: UploadCompletionRequest;
    path: {
        /**
         * Label Id
         */
        label_id: string;
    };
    query?: never;
    url: '/api/v1/labels/{label_id}/images/complete';
};

export type LabelsCompleteLabelImageUploadErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type LabelsCompleteLabelImageUploadError = LabelsCompleteLabelImageUploadErrors[keyof LabelsCompleteLabelImageUploadErrors];

export type LabelsCompleteLabelImageUploadResponses = {
    /**
     * Successful Response
     */
    200: LabelImageDetail;
};

export type LabelsCompleteLabelImageUploadResponse = LabelsCompleteLabelImageUploadResponses[keyof LabelsCompleteLabelImageUploadResponses];

export type LabelsGetLabelImagePresignedUploadUrlData = {
    body?: never;
    path: {
        /**
         * Image Id
         */
        image_id: string;
        /**
         * Label Id
         */
        label_id: string;
    };
    query: {
        /**
         * Content Type
         *
         * Content type (image/png, image/jpeg, image/webp)
         */
        content_type: string;
    };
    url: '/api/v1/labels/{label_id}/images/{image_id}/presigned-upload-url';
};

export type LabelsGetLabelImagePresignedUploadUrlErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type LabelsGetLabelImagePresignedUploadUrlError = LabelsGetLabelImagePresignedUploadUrlErrors[keyof LabelsGetLabelImagePresignedUploadUrlErrors];

export type LabelsGetLabelImagePresignedUploadUrlResponses = {
    /**
     * Successful Response
     */
    200: PresignedUploadUrlResponse;
};

export type LabelsGetLabelImagePresignedUploadUrlResponse = LabelsGetLabelImagePresignedUploadUrlResponses[keyof LabelsGetLabelImagePresignedUploadUrlResponses];

export type LabelsGetLabelImagePresignedDownloadUrlData = {
    body?: never;
    path: {
        /**
         * Image Id
         */
        image_id: string;
        /**
         * Label Id
         */
        label_id: string;
    };
    query?: never;
    url: '/api/v1/labels/{label_id}/images/{image_id}/presigned-download-url';
};

export type LabelsGetLabelImagePresignedDownloadUrlErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type LabelsGetLabelImagePresignedDownloadUrlError = LabelsGetLabelImagePresignedDownloadUrlErrors[keyof LabelsGetLabelImagePresignedDownloadUrlErrors];

export type LabelsGetLabelImagePresignedDownloadUrlResponses = {
    /**
     * Successful Response
     */
    200: PresignedDownloadUrlResponse;
};

export type LabelsGetLabelImagePresignedDownloadUrlResponse = LabelsGetLabelImagePresignedDownloadUrlResponses[keyof LabelsGetLabelImagePresignedDownloadUrlResponses];

export type ProductsReadProductsData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Product Type
         *
         * Product type
         */
        product_type?: string;
        /**
         * Limit
         *
         * Page size limit
         */
        limit?: number;
        /**
         * Offset
         *
         * Page offset
         */
        offset?: number;
    };
    url: '/api/v1/products';
};

export type ProductsReadProductsErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ProductsReadProductsError = ProductsReadProductsErrors[keyof ProductsReadProductsErrors];

export type ProductsReadProductsResponses = {
    /**
     * Successful Response
     */
    200: LimitOffsetPageProductPublic;
};

export type ProductsReadProductsResponse = ProductsReadProductsResponses[keyof ProductsReadProductsResponses];

export type PrivateCreateUserNoVerificationData = {
    body: PrivateUserCreate;
    path?: never;
    query?: never;
    url: '/api/v1/private/users/';
};

export type PrivateCreateUserNoVerificationErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type PrivateCreateUserNoVerificationError = PrivateCreateUserNoVerificationErrors[keyof PrivateCreateUserNoVerificationErrors];

export type PrivateCreateUserNoVerificationResponses = {
    /**
     * Successful Response
     */
    200: UserPublic;
};

export type PrivateCreateUserNoVerificationResponse = PrivateCreateUserNoVerificationResponses[keyof PrivateCreateUserNoVerificationResponses];
