// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseURL: `${string}://${string}` | (string & {});
};

/**
 * Body_login_login_access_token
 */
export type BodyLoginLoginAccessToken = {
    /**
     * Grant Type
     */
    grant_type?: string | null;
    /**
     * Username
     */
    username: string;
    /**
     * Password
     */
    password: string;
    /**
     * Scope
     */
    scope?: string;
    /**
     * Client Id
     */
    client_id?: string | null;
    /**
     * Client Secret
     */
    client_secret?: string | null;
};

/**
 * Contact
 */
export type Contact = {
    /**
     * Type
     *
     * Type of contact
     */
    type: string;
    /**
     * Name
     *
     * Company or organization name
     */
    name: string;
    /**
     * Address
     *
     * Full mailing address
     */
    address?: string | null;
    /**
     * Phone
     *
     * Phone number in any format
     */
    phone?: string | null;
    /**
     * Email
     *
     * Email address
     */
    email?: string | null;
    /**
     * Website
     *
     * Website URL
     */
    website?: string | null;
};

/**
 * ExtractFertilizerFieldsOutput
 */
export type ExtractFertilizerFieldsOutput = {
    /**
     * Brand Name En
     *
     * Brand name in English
     */
    brand_name_en?: string | null;
    /**
     * Brand Name Fr
     *
     * Brand name in French
     */
    brand_name_fr?: string | null;
    /**
     * Product Name En
     *
     * Product name in English
     */
    product_name_en?: string | null;
    /**
     * Product Name Fr
     *
     * Product name in French
     */
    product_name_fr?: string | null;
    /**
     * Contacts
     *
     * List of contact information (manufacturer, distributor, etc.)
     */
    contacts?: Array<Contact> | null;
    /**
     * Registration Number
     *
     * Product registration number
     */
    registration_number?: string | null;
    /**
     * Lot Number
     *
     * Lot or batch number
     */
    lot_number?: string | null;
    /**
     * Net Weight
     *
     * Net weight with unit
     */
    net_weight?: string | null;
    /**
     * Volume
     *
     * Volume with unit
     */
    volume?: string | null;
    /**
     * N
     *
     * Nitrogen percentage (NPK analysis)
     */
    n?: string | null;
    /**
     * P
     *
     * Phosphorus percentage (NPK analysis)
     */
    p?: string | null;
    /**
     * K
     *
     * Potassium percentage (NPK analysis)
     */
    k?: string | null;
    /**
     * Ingredients
     *
     * List of ingredients with bilingual names, values and units
     */
    ingredients?: Array<Ingredient> | null;
    /**
     * Guaranteed analysis section with bilingual title and nutrients
     */
    guaranteed_analysis?: GuaranteedAnalysisOutput | null;
    /**
     * Caution En
     *
     * Caution statements in English
     */
    caution_en?: string | null;
    /**
     * Caution Fr
     *
     * Caution statements in French
     */
    caution_fr?: string | null;
    /**
     * Instructions En
     *
     * Usage instructions in English
     */
    instructions_en?: string | null;
    /**
     * Instructions Fr
     *
     * Usage instructions in French
     */
    instructions_fr?: string | null;
};

/**
 * ExtractFieldsRequest
 */
export type ExtractFieldsRequest = {
    /**
     * Field Names
     *
     * List of field names to extract. If None or empty, extract all fields.
     */
    field_names?: Array<LabelDataFieldName | FertilizerLabelDataFieldName> | null;
};

/**
 * FertilizerLabelData
 */
export type FertilizerLabelData = {
    /**
     * N
     */
    n?: string | null;
    /**
     * P
     */
    p?: string | null;
    /**
     * K
     */
    k?: string | null;
    /**
     * Ingredients
     */
    ingredients?: Array<Ingredient> | null;
    guaranteed_analysis?: GuaranteedAnalysisOutput | null;
    /**
     * Caution En
     */
    caution_en?: string | null;
    /**
     * Caution Fr
     */
    caution_fr?: string | null;
    /**
     * Instructions En
     */
    instructions_en?: string | null;
    /**
     * Instructions Fr
     */
    instructions_fr?: string | null;
};

/**
 * FertilizerLabelDataCreate
 */
export type FertilizerLabelDataCreate = {
    /**
     * N
     */
    n?: number | string | null;
    /**
     * P
     */
    p?: number | string | null;
    /**
     * K
     */
    k?: number | string | null;
    /**
     * Ingredients
     */
    ingredients?: Array<Ingredient> | null;
    guaranteed_analysis?: GuaranteedAnalysisInput | null;
    /**
     * Caution En
     */
    caution_en?: string | null;
    /**
     * Caution Fr
     */
    caution_fr?: string | null;
    /**
     * Instructions En
     */
    instructions_en?: string | null;
    /**
     * Instructions Fr
     */
    instructions_fr?: string | null;
};

/**
 * FertilizerLabelDataFieldName
 *
 * Valid field names for FertilizerLabelDataMeta.
 */
export type FertilizerLabelDataFieldName = 'n' | 'p' | 'k' | 'ingredients' | 'guaranteed_analysis' | 'caution_en' | 'caution_fr' | 'instructions_en' | 'instructions_fr';

/**
 * FertilizerLabelDataMetaResponse
 */
export type FertilizerLabelDataMetaResponse = {
    /**
     * Field Name
     */
    field_name: string;
    /**
     * Needs Review
     */
    needs_review: boolean;
    /**
     * Note
     */
    note: string | null;
    /**
     * Ai Generated
     */
    ai_generated: boolean;
};

/**
 * FertilizerLabelDataMetaUpdate
 */
export type FertilizerLabelDataMetaUpdate = {
    field_name: FertilizerLabelDataFieldName;
    /**
     * Needs Review
     */
    needs_review?: boolean | null;
    /**
     * Note
     */
    note?: string | null;
    /**
     * Ai Generated
     */
    ai_generated?: boolean | null;
};

/**
 * FertilizerLabelDataUpdate
 */
export type FertilizerLabelDataUpdate = {
    /**
     * N
     */
    n?: number | string | null;
    /**
     * P
     */
    p?: number | string | null;
    /**
     * K
     */
    k?: number | string | null;
    /**
     * Ingredients
     */
    ingredients?: Array<Ingredient> | null;
    guaranteed_analysis?: GuaranteedAnalysisInput | null;
    /**
     * Caution En
     */
    caution_en?: string | null;
    /**
     * Caution Fr
     */
    caution_fr?: string | null;
    /**
     * Instructions En
     */
    instructions_en?: string | null;
    /**
     * Instructions Fr
     */
    instructions_fr?: string | null;
};

/**
 * GuaranteedAnalysis
 */
export type GuaranteedAnalysisInput = {
    /**
     * Title En
     *
     * Section title in English from label
     */
    title_en: string;
    /**
     * Title Fr
     *
     * Section title in French from label
     */
    title_fr?: string | null;
    /**
     * Is Minimum
     *
     * True if title contains 'Minimum', false otherwise
     */
    is_minimum: boolean;
    /**
     * Nutrients
     *
     * List of nutrients with bilingual names, values and units
     */
    nutrients: Array<NutrientInput>;
};

/**
 * GuaranteedAnalysis
 */
export type GuaranteedAnalysisOutput = {
    /**
     * Title En
     *
     * Section title in English from label
     */
    title_en: string;
    /**
     * Title Fr
     *
     * Section title in French from label
     */
    title_fr?: string | null;
    /**
     * Is Minimum
     *
     * True if title contains 'Minimum', false otherwise
     */
    is_minimum: boolean;
    /**
     * Nutrients
     *
     * List of nutrients with bilingual names, values and units
     */
    nutrients: Array<NutrientOutput>;
};

/**
 * HTTPValidationError
 */
export type HttpValidationError = {
    /**
     * Detail
     */
    detail?: Array<ValidationError>;
};

/**
 * Health
 */
export type Health = {
    /**
     * Status
     */
    status: string;
};

/**
 * Ingredient
 */
export type Ingredient = {
    /**
     * Name En
     *
     * Ingredient name in English as it appears on the label
     */
    name_en: string;
    /**
     * Name Fr
     *
     * Ingredient name in French as it appears on the label
     */
    name_fr?: string | null;
    /**
     * Value
     *
     * Ingredient percentage or amount.
     */
    value: string;
    /**
     * Unit
     *
     * Unit of measurement
     */
    unit: string;
};

/**
 * LabelCreate
 */
export type LabelCreate = {
    /**
     * Product Type
     */
    product_type: string;
    /**
     * Product Id
     */
    product_id?: string | null;
};

/**
 * LabelCreated
 *
 * Response schema for label creation.
 */
export type LabelCreated = {
    /**
     * Id
     */
    id: string;
};

/**
 * LabelData
 */
export type LabelData = {
    /**
     * Brand Name En
     */
    brand_name_en?: string | null;
    /**
     * Brand Name Fr
     */
    brand_name_fr?: string | null;
    /**
     * Product Name En
     */
    product_name_en?: string | null;
    /**
     * Product Name Fr
     */
    product_name_fr?: string | null;
    /**
     * Contacts
     */
    contacts?: Array<Contact> | null;
    /**
     * Registration Number
     */
    registration_number?: string | null;
    /**
     * Lot Number
     */
    lot_number?: string | null;
    /**
     * Net Weight
     */
    net_weight?: string | null;
    /**
     * Volume
     */
    volume?: string | null;
};

/**
 * LabelDataCreate
 */
export type LabelDataCreate = {
    /**
     * Brand Name En
     */
    brand_name_en?: string | null;
    /**
     * Brand Name Fr
     */
    brand_name_fr?: string | null;
    /**
     * Product Name En
     */
    product_name_en?: string | null;
    /**
     * Product Name Fr
     */
    product_name_fr?: string | null;
    /**
     * Contacts
     */
    contacts?: Array<Contact> | null;
    /**
     * Registration Number
     */
    registration_number?: string | null;
    /**
     * Lot Number
     */
    lot_number?: string | null;
    /**
     * Net Weight
     */
    net_weight?: string | null;
    /**
     * Volume
     */
    volume?: string | null;
};

/**
 * LabelDataFieldMetaResponse
 */
export type LabelDataFieldMetaResponse = {
    /**
     * Field Name
     */
    field_name: string;
    /**
     * Needs Review
     */
    needs_review: boolean;
    /**
     * Note
     */
    note: string | null;
    /**
     * Ai Generated
     */
    ai_generated: boolean;
};

/**
 * LabelDataFieldMetaUpdate
 */
export type LabelDataFieldMetaUpdate = {
    field_name: LabelDataFieldName;
    /**
     * Needs Review
     */
    needs_review?: boolean | null;
    /**
     * Note
     */
    note?: string | null;
    /**
     * Ai Generated
     */
    ai_generated?: boolean | null;
};

/**
 * LabelDataFieldName
 *
 * Valid field names for LabelDataFieldMeta.
 */
export type LabelDataFieldName = 'brand_name_en' | 'brand_name_fr' | 'product_name_en' | 'product_name_fr' | 'contacts' | 'registration_number' | 'lot_number' | 'net_weight' | 'volume';

/**
 * LabelDataLite
 */
export type LabelDataLite = {
    /**
     * Brand Name En
     */
    brand_name_en?: string | null;
    /**
     * Brand Name Fr
     */
    brand_name_fr?: string | null;
    /**
     * Product Name En
     */
    product_name_en?: string | null;
    /**
     * Product Name Fr
     */
    product_name_fr?: string | null;
};

/**
 * LabelDataUpdate
 */
export type LabelDataUpdate = {
    /**
     * Brand Name En
     */
    brand_name_en?: string | null;
    /**
     * Brand Name Fr
     */
    brand_name_fr?: string | null;
    /**
     * Product Name En
     */
    product_name_en?: string | null;
    /**
     * Product Name Fr
     */
    product_name_fr?: string | null;
    /**
     * Contacts
     */
    contacts?: Array<Contact> | null;
    /**
     * Registration Number
     */
    registration_number?: string | null;
    /**
     * Lot Number
     */
    lot_number?: string | null;
    /**
     * Net Weight
     */
    net_weight?: string | null;
    /**
     * Volume
     */
    volume?: string | null;
};

/**
 * LabelDetail
 */
export type LabelDetail = {
    /**
     * Id
     */
    id: string;
    /**
     * Product Id
     */
    product_id?: string | null;
    /**
     * Created By Id
     */
    created_by_id: string;
    review_status: ReviewStatus;
    /**
     * Created At
     */
    created_at: string;
    /**
     * Updated At
     */
    updated_at: string;
    product_type: ProductTypePublic;
    created_by: UserPublic;
    /**
     * Images
     */
    images?: Array<LabelImageDetail>;
};

/**
 * LabelImageDetail
 */
export type LabelImageDetail = {
    /**
     * Id
     */
    id: string;
    /**
     * Label Id
     */
    label_id: string;
    /**
     * Display Filename
     */
    display_filename: string;
    /**
     * File Path
     */
    file_path: string;
    /**
     * Sequence Order
     */
    sequence_order: number;
    status: UploadStatus;
    /**
     * Created At
     */
    created_at: string;
    /**
     * Updated At
     */
    updated_at: string;
    /**
     * Current Image Count
     */
    current_image_count?: number | null;
};

/**
 * LabelListItem
 *
 * Schema for label list items.
 */
export type LabelListItem = {
    /**
     * Id
     */
    id: string;
    review_status: ReviewStatus;
    /**
     * Created At
     */
    created_at: string;
    /**
     * Updated At
     */
    updated_at: string;
    label_data?: LabelDataLite | null;
};

/**
 * LabelReviewStatusUpdate
 */
export type LabelReviewStatusUpdate = {
    review_status: ReviewStatus;
};

/**
 * LabelUpdate
 */
export type LabelUpdate = {
    /**
     * Product Id
     */
    product_id?: string | null;
};

/**
 * LimitOffsetPage[LabelListItem]
 */
export type LimitOffsetPageLabelListItem = {
    /**
     * Items
     */
    items: Array<LabelListItem>;
    /**
     * Total
     */
    total: number;
    /**
     * Limit
     */
    limit: number;
    /**
     * Offset
     */
    offset: number;
};

/**
 * LimitOffsetPage[ProductPublic]
 */
export type LimitOffsetPageProductPublic = {
    /**
     * Items
     */
    items: Array<ProductPublic>;
    /**
     * Total
     */
    total: number;
    /**
     * Limit
     */
    limit: number;
    /**
     * Offset
     */
    offset: number;
};

/**
 * Message
 */
export type Message = {
    /**
     * Message
     */
    message: string;
};

/**
 * NewPassword
 */
export type NewPassword = {
    /**
     * Token
     */
    token: string;
    /**
     * New Password
     */
    new_password: string;
};

/**
 * Nutrient
 */
export type NutrientInput = {
    /**
     * Name En
     *
     * Nutrient name in English as it appears on the label
     */
    name_en: string;
    /**
     * Name Fr
     *
     * Nutrient name in French as it appears on the label
     */
    name_fr?: string | null;
    /**
     * Value
     *
     * Nutrient percentage value
     */
    value: number | string;
    /**
     * Unit
     *
     * Unit of measurement
     */
    unit: string;
};

/**
 * Nutrient
 */
export type NutrientOutput = {
    /**
     * Name En
     *
     * Nutrient name in English as it appears on the label
     */
    name_en: string;
    /**
     * Name Fr
     *
     * Nutrient name in French as it appears on the label
     */
    name_fr?: string | null;
    /**
     * Value
     *
     * Nutrient percentage value
     */
    value: string;
    /**
     * Unit
     *
     * Unit of measurement
     */
    unit: string;
};

/**
 * PresignedDownloadUrlResponse
 *
 * Response schema for presigned download URL request.
 */
export type PresignedDownloadUrlResponse = {
    /**
     * Presigned Url
     */
    presigned_url: string;
};

/**
 * PresignedUploadUrlResponse
 *
 * Response schema for presigned upload URL request.
 */
export type PresignedUploadUrlResponse = {
    /**
     * Url
     */
    url: string;
    /**
     * Expires At
     */
    expires_at: string;
};

/**
 * PresignedUrlRequest
 *
 * Request schema for individual presigned URL generation.
 */
export type PresignedUrlRequest = {
    /**
     * Display Filename
     */
    display_filename: string;
    /**
     * Content Type
     */
    content_type: 'image/png' | 'image/jpeg' | 'image/webp';
    /**
     * Sequence Order
     */
    sequence_order: number;
};

/**
 * PrivateUserCreate
 */
export type PrivateUserCreate = {
    /**
     * Email
     */
    email: string;
    /**
     * Password
     */
    password: string;
    /**
     * First Name
     */
    first_name?: string | null;
    /**
     * Last Name
     */
    last_name?: string | null;
};

/**
 * ProductCreate
 */
export type ProductCreate = {
    /**
     * Registration Number
     */
    registration_number?: string | null;
    /**
     * Product Type
     */
    product_type: string;
    /**
     * Brand Name En
     */
    brand_name_en?: string | null;
    /**
     * Brand Name Fr
     */
    brand_name_fr?: string | null;
    /**
     * Name En
     */
    name_en?: string | null;
    /**
     * Name Fr
     */
    name_fr?: string | null;
};

/**
 * ProductPublic
 */
export type ProductPublic = {
    /**
     * Id
     */
    id: string;
    /**
     * Brand Name En
     */
    brand_name_en?: string | null;
    /**
     * Brand Name Fr
     */
    brand_name_fr?: string | null;
    /**
     * Name En
     */
    name_en?: string | null;
    /**
     * Name Fr
     */
    name_fr?: string | null;
    /**
     * Registration Number
     */
    registration_number?: string | null;
};

/**
 * ProductTypePublic
 */
export type ProductTypePublic = {
    /**
     * Code
     */
    code: string;
    /**
     * Name En
     */
    name_en?: string | null;
    /**
     * Name Fr
     */
    name_fr?: string | null;
    /**
     * Is Active
     */
    is_active?: boolean;
    /**
     * Id
     */
    id: string;
    /**
     * Created At
     */
    created_at: string;
    /**
     * Updated At
     */
    updated_at: string;
};

/**
 * Readiness
 */
export type Readiness = {
    /**
     * Status
     */
    status: string;
    /**
     * Database
     */
    database: string;
};

/**
 * ReviewStatus
 */
export type ReviewStatus = 'not_started' | 'in_progress' | 'completed';

/**
 * Token
 */
export type Token = {
    /**
     * Access Token
     */
    access_token: string;
    /**
     * Token Type
     */
    token_type?: string;
};

/**
 * UpdatePassword
 */
export type UpdatePassword = {
    /**
     * Current Password
     */
    current_password: string;
    /**
     * New Password
     */
    new_password: string;
};

/**
 * UploadCompletionRequest
 *
 * Request schema for upload completion notification.
 */
export type UploadCompletionRequest = {
    /**
     * Storage File Path
     */
    storage_file_path: string;
};

/**
 * UploadStatus
 */
export type UploadStatus = 'pending' | 'completed';

/**
 * UserCreate
 */
export type UserCreate = {
    /**
     * Email
     */
    email: string;
    /**
     * Is Active
     */
    is_active?: boolean;
    /**
     * Is Superuser
     */
    is_superuser?: boolean;
    /**
     * First Name
     */
    first_name?: string | null;
    /**
     * Last Name
     */
    last_name?: string | null;
};

/**
 * UserPublic
 */
export type UserPublic = {
    /**
     * Email
     */
    email: string;
    /**
     * Is Active
     */
    is_active?: boolean;
    /**
     * Is Superuser
     */
    is_superuser?: boolean;
    /**
     * First Name
     */
    first_name?: string | null;
    /**
     * Last Name
     */
    last_name?: string | null;
    /**
     * Id
     */
    id: string;
};

/**
 * UserUpdate
 */
export type UserUpdate = {
    /**
     * Email
     */
    email?: string | null;
    /**
     * Password
     */
    password?: null;
    /**
     * Is Active
     */
    is_active?: boolean | null;
    /**
     * Is Superuser
     */
    is_superuser?: boolean | null;
    /**
     * First Name
     */
    first_name?: string | null;
    /**
     * Last Name
     */
    last_name?: string | null;
};

/**
 * UserUpdateMe
 */
export type UserUpdateMe = {
    /**
     * First Name
     */
    first_name?: string | null;
    /**
     * Last Name
     */
    last_name?: string | null;
    /**
     * Email
     */
    email?: string | null;
};

/**
 * UsersPublic
 */
export type UsersPublic = {
    /**
     * Data
     */
    data: Array<UserPublic>;
    /**
     * Count
     */
    count: number;
};

/**
 * ValidationError
 */
export type ValidationError = {
    /**
     * Location
     */
    loc: Array<string | number>;
    /**
     * Message
     */
    msg: string;
    /**
     * Error Type
     */
    type: string;
};

/**
 * UserCreate
 */
export type UserCreateWritable = {
    /**
     * Email
     */
    email: string;
    /**
     * Is Active
     */
    is_active?: boolean;
    /**
     * Is Superuser
     */
    is_superuser?: boolean;
    /**
     * First Name
     */
    first_name?: string | null;
    /**
     * Last Name
     */
    last_name?: string | null;
    /**
     * Password
     */
    password: string;
};

/**
 * UserUpdate
 */
export type UserUpdateWritable = {
    /**
     * Email
     */
    email?: string | null;
    /**
     * Password
     */
    password?: string | null;
    /**
     * Is Active
     */
    is_active?: boolean | null;
    /**
     * Is Superuser
     */
    is_superuser?: boolean | null;
    /**
     * First Name
     */
    first_name?: string | null;
    /**
     * Last Name
     */
    last_name?: string | null;
};

export type GetHealthzData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/healthz';
};

export type GetHealthzResponses = {
    /**
     * Successful Response
     */
    200: Health;
};

export type GetHealthzResponse = GetHealthzResponses[keyof GetHealthzResponses];

export type GetReadyzData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/readyz';
};

export type GetReadyzResponses = {
    /**
     * Successful Response
     */
    200: Readiness;
};

export type GetReadyzResponse = GetReadyzResponses[keyof GetReadyzResponses];

export type PostApiV1LoginAccessTokenData = {
    body: BodyLoginLoginAccessToken;
    path?: never;
    query?: never;
    url: '/api/v1/login/access-token';
};

export type PostApiV1LoginAccessTokenErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type PostApiV1LoginAccessTokenError = PostApiV1LoginAccessTokenErrors[keyof PostApiV1LoginAccessTokenErrors];

export type PostApiV1LoginAccessTokenResponses = {
    /**
     * Successful Response
     */
    200: Token;
};

export type PostApiV1LoginAccessTokenResponse = PostApiV1LoginAccessTokenResponses[keyof PostApiV1LoginAccessTokenResponses];

export type PostApiV1LoginTestTokenData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/login/test-token';
};

export type PostApiV1LoginTestTokenResponses = {
    /**
     * Successful Response
     */
    200: UserPublic;
};

export type PostApiV1LoginTestTokenResponse = PostApiV1LoginTestTokenResponses[keyof PostApiV1LoginTestTokenResponses];

export type PostApiV1PasswordRecoveryByEmailData = {
    body?: never;
    path: {
        /**
         * Email
         */
        email: string;
    };
    query?: never;
    url: '/api/v1/password-recovery/{email}';
};

export type PostApiV1PasswordRecoveryByEmailErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type PostApiV1PasswordRecoveryByEmailError = PostApiV1PasswordRecoveryByEmailErrors[keyof PostApiV1PasswordRecoveryByEmailErrors];

export type PostApiV1PasswordRecoveryByEmailResponses = {
    /**
     * Successful Response
     */
    200: Message;
};

export type PostApiV1PasswordRecoveryByEmailResponse = PostApiV1PasswordRecoveryByEmailResponses[keyof PostApiV1PasswordRecoveryByEmailResponses];

export type PostApiV1ResetPasswordData = {
    body: NewPassword;
    path?: never;
    query?: never;
    url: '/api/v1/reset-password/';
};

export type PostApiV1ResetPasswordErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type PostApiV1ResetPasswordError = PostApiV1ResetPasswordErrors[keyof PostApiV1ResetPasswordErrors];

export type PostApiV1ResetPasswordResponses = {
    /**
     * Successful Response
     */
    200: Message;
};

export type PostApiV1ResetPasswordResponse = PostApiV1ResetPasswordResponses[keyof PostApiV1ResetPasswordResponses];

export type PostApiV1PasswordRecoveryHtmlContentByEmailData = {
    body?: never;
    path: {
        /**
         * Email
         */
        email: string;
    };
    query?: never;
    url: '/api/v1/password-recovery-html-content/{email}';
};

export type PostApiV1PasswordRecoveryHtmlContentByEmailErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type PostApiV1PasswordRecoveryHtmlContentByEmailError = PostApiV1PasswordRecoveryHtmlContentByEmailErrors[keyof PostApiV1PasswordRecoveryHtmlContentByEmailErrors];

export type PostApiV1PasswordRecoveryHtmlContentByEmailResponses = {
    /**
     * Successful Response
     */
    200: string;
};

export type PostApiV1PasswordRecoveryHtmlContentByEmailResponse = PostApiV1PasswordRecoveryHtmlContentByEmailResponses[keyof PostApiV1PasswordRecoveryHtmlContentByEmailResponses];

export type GetApiV1UsersData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Skip
         */
        skip?: number;
        /**
         * Limit
         */
        limit?: number;
    };
    url: '/api/v1/users';
};

export type GetApiV1UsersErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetApiV1UsersError = GetApiV1UsersErrors[keyof GetApiV1UsersErrors];

export type GetApiV1UsersResponses = {
    /**
     * Successful Response
     */
    200: UsersPublic;
};

export type GetApiV1UsersResponse = GetApiV1UsersResponses[keyof GetApiV1UsersResponses];

export type PostApiV1UsersData = {
    body: UserCreateWritable;
    path?: never;
    query?: never;
    url: '/api/v1/users';
};

export type PostApiV1UsersErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type PostApiV1UsersError = PostApiV1UsersErrors[keyof PostApiV1UsersErrors];

export type PostApiV1UsersResponses = {
    /**
     * Successful Response
     */
    201: UserPublic;
};

export type PostApiV1UsersResponse = PostApiV1UsersResponses[keyof PostApiV1UsersResponses];

export type DeleteApiV1UsersMeData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/users/me';
};

export type DeleteApiV1UsersMeResponses = {
    /**
     * Successful Response
     */
    200: Message;
};

export type DeleteApiV1UsersMeResponse = DeleteApiV1UsersMeResponses[keyof DeleteApiV1UsersMeResponses];

export type GetApiV1UsersMeData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/users/me';
};

export type GetApiV1UsersMeResponses = {
    /**
     * Successful Response
     */
    200: UserPublic;
};

export type GetApiV1UsersMeResponse = GetApiV1UsersMeResponses[keyof GetApiV1UsersMeResponses];

export type PatchApiV1UsersMeData = {
    body: UserUpdateMe;
    path?: never;
    query?: never;
    url: '/api/v1/users/me';
};

export type PatchApiV1UsersMeErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type PatchApiV1UsersMeError = PatchApiV1UsersMeErrors[keyof PatchApiV1UsersMeErrors];

export type PatchApiV1UsersMeResponses = {
    /**
     * Successful Response
     */
    200: UserPublic;
};

export type PatchApiV1UsersMeResponse = PatchApiV1UsersMeResponses[keyof PatchApiV1UsersMeResponses];

export type PatchApiV1UsersMePasswordData = {
    body: UpdatePassword;
    path?: never;
    query?: never;
    url: '/api/v1/users/me/password';
};

export type PatchApiV1UsersMePasswordErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type PatchApiV1UsersMePasswordError = PatchApiV1UsersMePasswordErrors[keyof PatchApiV1UsersMePasswordErrors];

export type PatchApiV1UsersMePasswordResponses = {
    /**
     * Successful Response
     */
    200: Message;
};

export type PatchApiV1UsersMePasswordResponse = PatchApiV1UsersMePasswordResponses[keyof PatchApiV1UsersMePasswordResponses];

export type DeleteApiV1UsersByUserIdData = {
    body?: never;
    path: {
        /**
         * User Id
         */
        user_id: string;
    };
    query?: never;
    url: '/api/v1/users/{user_id}';
};

export type DeleteApiV1UsersByUserIdErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeleteApiV1UsersByUserIdError = DeleteApiV1UsersByUserIdErrors[keyof DeleteApiV1UsersByUserIdErrors];

export type DeleteApiV1UsersByUserIdResponses = {
    /**
     * Successful Response
     */
    200: Message;
};

export type DeleteApiV1UsersByUserIdResponse = DeleteApiV1UsersByUserIdResponses[keyof DeleteApiV1UsersByUserIdResponses];

export type GetApiV1UsersByUserIdData = {
    body?: never;
    path: {
        /**
         * User Id
         */
        user_id: string;
    };
    query?: never;
    url: '/api/v1/users/{user_id}';
};

export type GetApiV1UsersByUserIdErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetApiV1UsersByUserIdError = GetApiV1UsersByUserIdErrors[keyof GetApiV1UsersByUserIdErrors];

export type GetApiV1UsersByUserIdResponses = {
    /**
     * Successful Response
     */
    200: UserPublic;
};

export type GetApiV1UsersByUserIdResponse = GetApiV1UsersByUserIdResponses[keyof GetApiV1UsersByUserIdResponses];

export type PatchApiV1UsersByUserIdData = {
    body: UserUpdateWritable;
    path: {
        /**
         * User Id
         */
        user_id: string;
    };
    query?: never;
    url: '/api/v1/users/{user_id}';
};

export type PatchApiV1UsersByUserIdErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type PatchApiV1UsersByUserIdError = PatchApiV1UsersByUserIdErrors[keyof PatchApiV1UsersByUserIdErrors];

export type PatchApiV1UsersByUserIdResponses = {
    /**
     * Successful Response
     */
    200: UserPublic;
};

export type PatchApiV1UsersByUserIdResponse = PatchApiV1UsersByUserIdResponses[keyof PatchApiV1UsersByUserIdResponses];

export type GetApiV1LabelsData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Review Status
         *
         * Filter by review status
         */
        review_status?: ReviewStatus | null;
        /**
         * Unlinked
         *
         * Filter labels not linked to a product (product_id is null)
         */
        unlinked?: boolean | null;
        /**
         * Order By
         *
         * Field to sort by
         */
        order_by?: string;
        /**
         * Order
         *
         * Sort direction (asc or desc)
         */
        order?: string;
        /**
         * Limit
         *
         * Page size limit
         */
        limit?: number;
        /**
         * Offset
         *
         * Page offset
         */
        offset?: number;
        /**
         * Product Type
         *
         * Product type
         */
        product_type?: string;
    };
    url: '/api/v1/labels';
};

export type GetApiV1LabelsErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetApiV1LabelsError = GetApiV1LabelsErrors[keyof GetApiV1LabelsErrors];

export type GetApiV1LabelsResponses = {
    /**
     * Successful Response
     */
    200: LimitOffsetPageLabelListItem;
};

export type GetApiV1LabelsResponse = GetApiV1LabelsResponses[keyof GetApiV1LabelsResponses];

export type PostApiV1LabelsData = {
    body: LabelCreate;
    path?: never;
    query?: never;
    url: '/api/v1/labels';
};

export type PostApiV1LabelsErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type PostApiV1LabelsError = PostApiV1LabelsErrors[keyof PostApiV1LabelsErrors];

export type PostApiV1LabelsResponses = {
    /**
     * Successful Response
     */
    201: LabelCreated;
};

export type PostApiV1LabelsResponse = PostApiV1LabelsResponses[keyof PostApiV1LabelsResponses];

export type DeleteApiV1LabelsByLabelIdData = {
    body?: never;
    path: {
        /**
         * Label Id
         */
        label_id: string;
    };
    query?: never;
    url: '/api/v1/labels/{label_id}';
};

export type DeleteApiV1LabelsByLabelIdErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeleteApiV1LabelsByLabelIdError = DeleteApiV1LabelsByLabelIdErrors[keyof DeleteApiV1LabelsByLabelIdErrors];

export type DeleteApiV1LabelsByLabelIdResponses = {
    /**
     * Successful Response
     */
    204: void;
};

export type DeleteApiV1LabelsByLabelIdResponse = DeleteApiV1LabelsByLabelIdResponses[keyof DeleteApiV1LabelsByLabelIdResponses];

export type GetApiV1LabelsByLabelIdData = {
    body?: never;
    path: {
        /**
         * Label Id
         */
        label_id: string;
    };
    query?: never;
    url: '/api/v1/labels/{label_id}';
};

export type GetApiV1LabelsByLabelIdErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetApiV1LabelsByLabelIdError = GetApiV1LabelsByLabelIdErrors[keyof GetApiV1LabelsByLabelIdErrors];

export type GetApiV1LabelsByLabelIdResponses = {
    /**
     * Successful Response
     */
    200: LabelDetail;
};

export type GetApiV1LabelsByLabelIdResponse = GetApiV1LabelsByLabelIdResponses[keyof GetApiV1LabelsByLabelIdResponses];

export type PatchApiV1LabelsByLabelIdData = {
    body: LabelUpdate;
    path: {
        /**
         * Label Id
         */
        label_id: string;
    };
    query?: never;
    url: '/api/v1/labels/{label_id}';
};

export type PatchApiV1LabelsByLabelIdErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type PatchApiV1LabelsByLabelIdError = PatchApiV1LabelsByLabelIdErrors[keyof PatchApiV1LabelsByLabelIdErrors];

export type PatchApiV1LabelsByLabelIdResponses = {
    /**
     * Successful Response
     */
    200: LabelDetail;
};

export type PatchApiV1LabelsByLabelIdResponse = PatchApiV1LabelsByLabelIdResponses[keyof PatchApiV1LabelsByLabelIdResponses];

export type PatchApiV1LabelsByLabelIdReviewStatusData = {
    body: LabelReviewStatusUpdate;
    path: {
        /**
         * Label Id
         */
        label_id: string;
    };
    query?: never;
    url: '/api/v1/labels/{label_id}/review-status';
};

export type PatchApiV1LabelsByLabelIdReviewStatusErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type PatchApiV1LabelsByLabelIdReviewStatusError = PatchApiV1LabelsByLabelIdReviewStatusErrors[keyof PatchApiV1LabelsByLabelIdReviewStatusErrors];

export type PatchApiV1LabelsByLabelIdReviewStatusResponses = {
    /**
     * Successful Response
     */
    200: LabelDetail;
};

export type PatchApiV1LabelsByLabelIdReviewStatusResponse = PatchApiV1LabelsByLabelIdReviewStatusResponses[keyof PatchApiV1LabelsByLabelIdReviewStatusResponses];

export type GetApiV1LabelsByLabelIdImagesData = {
    body?: never;
    path: {
        /**
         * Label Id
         */
        label_id: string;
    };
    query?: never;
    url: '/api/v1/labels/{label_id}/images';
};

export type GetApiV1LabelsByLabelIdImagesErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetApiV1LabelsByLabelIdImagesError = GetApiV1LabelsByLabelIdImagesErrors[keyof GetApiV1LabelsByLabelIdImagesErrors];

export type GetApiV1LabelsByLabelIdImagesResponses = {
    /**
     * Response Labels Read Label Images
     *
     * Successful Response
     */
    200: Array<LabelImageDetail>;
};

export type GetApiV1LabelsByLabelIdImagesResponse = GetApiV1LabelsByLabelIdImagesResponses[keyof GetApiV1LabelsByLabelIdImagesResponses];

export type PostApiV1LabelsByLabelIdImagesData = {
    body: PresignedUrlRequest;
    path: {
        /**
         * Label Id
         */
        label_id: string;
    };
    query?: never;
    url: '/api/v1/labels/{label_id}/images';
};

export type PostApiV1LabelsByLabelIdImagesErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type PostApiV1LabelsByLabelIdImagesError = PostApiV1LabelsByLabelIdImagesErrors[keyof PostApiV1LabelsByLabelIdImagesErrors];

export type PostApiV1LabelsByLabelIdImagesResponses = {
    /**
     * Successful Response
     */
    201: LabelImageDetail;
};

export type PostApiV1LabelsByLabelIdImagesResponse = PostApiV1LabelsByLabelIdImagesResponses[keyof PostApiV1LabelsByLabelIdImagesResponses];

export type DeleteApiV1LabelsByLabelIdImagesByImageIdData = {
    body?: never;
    path: {
        /**
         * Image Id
         */
        image_id: string;
        /**
         * Label Id
         */
        label_id: string;
    };
    query?: never;
    url: '/api/v1/labels/{label_id}/images/{image_id}';
};

export type DeleteApiV1LabelsByLabelIdImagesByImageIdErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeleteApiV1LabelsByLabelIdImagesByImageIdError = DeleteApiV1LabelsByLabelIdImagesByImageIdErrors[keyof DeleteApiV1LabelsByLabelIdImagesByImageIdErrors];

export type DeleteApiV1LabelsByLabelIdImagesByImageIdResponses = {
    /**
     * Successful Response
     */
    204: void;
};

export type DeleteApiV1LabelsByLabelIdImagesByImageIdResponse = DeleteApiV1LabelsByLabelIdImagesByImageIdResponses[keyof DeleteApiV1LabelsByLabelIdImagesByImageIdResponses];

export type GetApiV1LabelsByLabelIdImagesByImageIdData = {
    body?: never;
    path: {
        /**
         * Image Id
         */
        image_id: string;
        /**
         * Label Id
         */
        label_id: string;
    };
    query?: never;
    url: '/api/v1/labels/{label_id}/images/{image_id}';
};

export type GetApiV1LabelsByLabelIdImagesByImageIdErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetApiV1LabelsByLabelIdImagesByImageIdError = GetApiV1LabelsByLabelIdImagesByImageIdErrors[keyof GetApiV1LabelsByLabelIdImagesByImageIdErrors];

export type GetApiV1LabelsByLabelIdImagesByImageIdResponses = {
    /**
     * Successful Response
     */
    200: LabelImageDetail;
};

export type GetApiV1LabelsByLabelIdImagesByImageIdResponse = GetApiV1LabelsByLabelIdImagesByImageIdResponses[keyof GetApiV1LabelsByLabelIdImagesByImageIdResponses];

export type PostApiV1LabelsByLabelIdImagesCompleteData = {
    body: UploadCompletionRequest;
    path: {
        /**
         * Label Id
         */
        label_id: string;
    };
    query?: never;
    url: '/api/v1/labels/{label_id}/images/complete';
};

export type PostApiV1LabelsByLabelIdImagesCompleteErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type PostApiV1LabelsByLabelIdImagesCompleteError = PostApiV1LabelsByLabelIdImagesCompleteErrors[keyof PostApiV1LabelsByLabelIdImagesCompleteErrors];

export type PostApiV1LabelsByLabelIdImagesCompleteResponses = {
    /**
     * Successful Response
     */
    200: LabelImageDetail;
};

export type PostApiV1LabelsByLabelIdImagesCompleteResponse = PostApiV1LabelsByLabelIdImagesCompleteResponses[keyof PostApiV1LabelsByLabelIdImagesCompleteResponses];

export type GetApiV1LabelsByLabelIdImagesByImageIdPresignedUploadUrlData = {
    body?: never;
    path: {
        /**
         * Image Id
         */
        image_id: string;
        /**
         * Label Id
         */
        label_id: string;
    };
    query: {
        /**
         * Content Type
         *
         * Content type (image/png, image/jpeg, image/webp)
         */
        content_type: string;
    };
    url: '/api/v1/labels/{label_id}/images/{image_id}/presigned-upload-url';
};

export type GetApiV1LabelsByLabelIdImagesByImageIdPresignedUploadUrlErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetApiV1LabelsByLabelIdImagesByImageIdPresignedUploadUrlError = GetApiV1LabelsByLabelIdImagesByImageIdPresignedUploadUrlErrors[keyof GetApiV1LabelsByLabelIdImagesByImageIdPresignedUploadUrlErrors];

export type GetApiV1LabelsByLabelIdImagesByImageIdPresignedUploadUrlResponses = {
    /**
     * Successful Response
     */
    200: PresignedUploadUrlResponse;
};

export type GetApiV1LabelsByLabelIdImagesByImageIdPresignedUploadUrlResponse = GetApiV1LabelsByLabelIdImagesByImageIdPresignedUploadUrlResponses[keyof GetApiV1LabelsByLabelIdImagesByImageIdPresignedUploadUrlResponses];

export type GetApiV1LabelsByLabelIdImagesByImageIdPresignedDownloadUrlData = {
    body?: never;
    path: {
        /**
         * Image Id
         */
        image_id: string;
        /**
         * Label Id
         */
        label_id: string;
    };
    query?: never;
    url: '/api/v1/labels/{label_id}/images/{image_id}/presigned-download-url';
};

export type GetApiV1LabelsByLabelIdImagesByImageIdPresignedDownloadUrlErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetApiV1LabelsByLabelIdImagesByImageIdPresignedDownloadUrlError = GetApiV1LabelsByLabelIdImagesByImageIdPresignedDownloadUrlErrors[keyof GetApiV1LabelsByLabelIdImagesByImageIdPresignedDownloadUrlErrors];

export type GetApiV1LabelsByLabelIdImagesByImageIdPresignedDownloadUrlResponses = {
    /**
     * Successful Response
     */
    200: PresignedDownloadUrlResponse;
};

export type GetApiV1LabelsByLabelIdImagesByImageIdPresignedDownloadUrlResponse = GetApiV1LabelsByLabelIdImagesByImageIdPresignedDownloadUrlResponses[keyof GetApiV1LabelsByLabelIdImagesByImageIdPresignedDownloadUrlResponses];

export type GetApiV1LabelsByLabelIdDataData = {
    body?: never;
    path: {
        /**
         * Label Id
         */
        label_id: string;
    };
    query?: never;
    url: '/api/v1/labels/{label_id}/data';
};

export type GetApiV1LabelsByLabelIdDataErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetApiV1LabelsByLabelIdDataError = GetApiV1LabelsByLabelIdDataErrors[keyof GetApiV1LabelsByLabelIdDataErrors];

export type GetApiV1LabelsByLabelIdDataResponses = {
    /**
     * Successful Response
     */
    200: LabelData;
};

export type GetApiV1LabelsByLabelIdDataResponse = GetApiV1LabelsByLabelIdDataResponses[keyof GetApiV1LabelsByLabelIdDataResponses];

export type PatchApiV1LabelsByLabelIdDataData = {
    body: LabelDataUpdate;
    path: {
        /**
         * Label Id
         */
        label_id: string;
    };
    query?: never;
    url: '/api/v1/labels/{label_id}/data';
};

export type PatchApiV1LabelsByLabelIdDataErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type PatchApiV1LabelsByLabelIdDataError = PatchApiV1LabelsByLabelIdDataErrors[keyof PatchApiV1LabelsByLabelIdDataErrors];

export type PatchApiV1LabelsByLabelIdDataResponses = {
    /**
     * Successful Response
     */
    200: LabelData;
};

export type PatchApiV1LabelsByLabelIdDataResponse = PatchApiV1LabelsByLabelIdDataResponses[keyof PatchApiV1LabelsByLabelIdDataResponses];

export type PostApiV1LabelsByLabelIdDataData = {
    body: LabelDataCreate;
    path: {
        /**
         * Label Id
         */
        label_id: string;
    };
    query?: never;
    url: '/api/v1/labels/{label_id}/data';
};

export type PostApiV1LabelsByLabelIdDataErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type PostApiV1LabelsByLabelIdDataError = PostApiV1LabelsByLabelIdDataErrors[keyof PostApiV1LabelsByLabelIdDataErrors];

export type PostApiV1LabelsByLabelIdDataResponses = {
    /**
     * Successful Response
     */
    201: LabelData;
};

export type PostApiV1LabelsByLabelIdDataResponse = PostApiV1LabelsByLabelIdDataResponses[keyof PostApiV1LabelsByLabelIdDataResponses];

export type GetApiV1LabelsByLabelIdDataMetaData = {
    body?: never;
    path: {
        /**
         * Label Id
         */
        label_id: string;
    };
    query?: {
        /**
         * Field Name
         *
         * Filter by field name
         */
        field_name?: string | null;
        /**
         * Needs Review
         *
         * Filter by needs_review flag
         */
        needs_review?: boolean | null;
    };
    url: '/api/v1/labels/{label_id}/data/meta';
};

export type GetApiV1LabelsByLabelIdDataMetaErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetApiV1LabelsByLabelIdDataMetaError = GetApiV1LabelsByLabelIdDataMetaErrors[keyof GetApiV1LabelsByLabelIdDataMetaErrors];

export type GetApiV1LabelsByLabelIdDataMetaResponses = {
    /**
     * Response Labels Read Label Data Meta
     *
     * Successful Response
     */
    200: Array<LabelDataFieldMetaResponse>;
};

export type GetApiV1LabelsByLabelIdDataMetaResponse = GetApiV1LabelsByLabelIdDataMetaResponses[keyof GetApiV1LabelsByLabelIdDataMetaResponses];

export type PatchApiV1LabelsByLabelIdDataMetaData = {
    body: LabelDataFieldMetaUpdate;
    path: {
        /**
         * Label Id
         */
        label_id: string;
    };
    query?: never;
    url: '/api/v1/labels/{label_id}/data/meta';
};

export type PatchApiV1LabelsByLabelIdDataMetaErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type PatchApiV1LabelsByLabelIdDataMetaError = PatchApiV1LabelsByLabelIdDataMetaErrors[keyof PatchApiV1LabelsByLabelIdDataMetaErrors];

export type PatchApiV1LabelsByLabelIdDataMetaResponses = {
    /**
     * Successful Response
     */
    200: LabelDataFieldMetaResponse;
};

export type PatchApiV1LabelsByLabelIdDataMetaResponse = PatchApiV1LabelsByLabelIdDataMetaResponses[keyof PatchApiV1LabelsByLabelIdDataMetaResponses];

export type GetApiV1LabelsByLabelIdFertilizerDataData = {
    body?: never;
    path: {
        /**
         * Label Id
         */
        label_id: string;
    };
    query?: never;
    url: '/api/v1/labels/{label_id}/fertilizer-data';
};

export type GetApiV1LabelsByLabelIdFertilizerDataErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetApiV1LabelsByLabelIdFertilizerDataError = GetApiV1LabelsByLabelIdFertilizerDataErrors[keyof GetApiV1LabelsByLabelIdFertilizerDataErrors];

export type GetApiV1LabelsByLabelIdFertilizerDataResponses = {
    /**
     * Successful Response
     */
    200: FertilizerLabelData;
};

export type GetApiV1LabelsByLabelIdFertilizerDataResponse = GetApiV1LabelsByLabelIdFertilizerDataResponses[keyof GetApiV1LabelsByLabelIdFertilizerDataResponses];

export type PatchApiV1LabelsByLabelIdFertilizerDataData = {
    body: FertilizerLabelDataUpdate;
    path: {
        /**
         * Label Id
         */
        label_id: string;
    };
    query?: never;
    url: '/api/v1/labels/{label_id}/fertilizer-data';
};

export type PatchApiV1LabelsByLabelIdFertilizerDataErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type PatchApiV1LabelsByLabelIdFertilizerDataError = PatchApiV1LabelsByLabelIdFertilizerDataErrors[keyof PatchApiV1LabelsByLabelIdFertilizerDataErrors];

export type PatchApiV1LabelsByLabelIdFertilizerDataResponses = {
    /**
     * Successful Response
     */
    200: FertilizerLabelData;
};

export type PatchApiV1LabelsByLabelIdFertilizerDataResponse = PatchApiV1LabelsByLabelIdFertilizerDataResponses[keyof PatchApiV1LabelsByLabelIdFertilizerDataResponses];

export type PostApiV1LabelsByLabelIdFertilizerDataData = {
    body: FertilizerLabelDataCreate;
    path: {
        /**
         * Label Id
         */
        label_id: string;
    };
    query?: never;
    url: '/api/v1/labels/{label_id}/fertilizer-data';
};

export type PostApiV1LabelsByLabelIdFertilizerDataErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type PostApiV1LabelsByLabelIdFertilizerDataError = PostApiV1LabelsByLabelIdFertilizerDataErrors[keyof PostApiV1LabelsByLabelIdFertilizerDataErrors];

export type PostApiV1LabelsByLabelIdFertilizerDataResponses = {
    /**
     * Successful Response
     */
    201: FertilizerLabelData;
};

export type PostApiV1LabelsByLabelIdFertilizerDataResponse = PostApiV1LabelsByLabelIdFertilizerDataResponses[keyof PostApiV1LabelsByLabelIdFertilizerDataResponses];

export type GetApiV1LabelsByLabelIdFertilizerDataMetaData = {
    body?: never;
    path: {
        /**
         * Label Id
         */
        label_id: string;
    };
    query?: {
        /**
         * Field Name
         *
         * Filter by field name
         */
        field_name?: string | null;
        /**
         * Needs Review
         *
         * Filter by needs_review flag
         */
        needs_review?: boolean | null;
    };
    url: '/api/v1/labels/{label_id}/fertilizer-data/meta';
};

export type GetApiV1LabelsByLabelIdFertilizerDataMetaErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetApiV1LabelsByLabelIdFertilizerDataMetaError = GetApiV1LabelsByLabelIdFertilizerDataMetaErrors[keyof GetApiV1LabelsByLabelIdFertilizerDataMetaErrors];

export type GetApiV1LabelsByLabelIdFertilizerDataMetaResponses = {
    /**
     * Response Labels Read Fertilizer Label Data Meta
     *
     * Successful Response
     */
    200: Array<FertilizerLabelDataMetaResponse>;
};

export type GetApiV1LabelsByLabelIdFertilizerDataMetaResponse = GetApiV1LabelsByLabelIdFertilizerDataMetaResponses[keyof GetApiV1LabelsByLabelIdFertilizerDataMetaResponses];

export type PatchApiV1LabelsByLabelIdFertilizerDataMetaData = {
    body: FertilizerLabelDataMetaUpdate;
    path: {
        /**
         * Label Id
         */
        label_id: string;
    };
    query?: never;
    url: '/api/v1/labels/{label_id}/fertilizer-data/meta';
};

export type PatchApiV1LabelsByLabelIdFertilizerDataMetaErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type PatchApiV1LabelsByLabelIdFertilizerDataMetaError = PatchApiV1LabelsByLabelIdFertilizerDataMetaErrors[keyof PatchApiV1LabelsByLabelIdFertilizerDataMetaErrors];

export type PatchApiV1LabelsByLabelIdFertilizerDataMetaResponses = {
    /**
     * Successful Response
     */
    200: FertilizerLabelDataMetaResponse;
};

export type PatchApiV1LabelsByLabelIdFertilizerDataMetaResponse = PatchApiV1LabelsByLabelIdFertilizerDataMetaResponses[keyof PatchApiV1LabelsByLabelIdFertilizerDataMetaResponses];

export type PostApiV1LabelsByLabelIdFertilizerExtractData = {
    /**
     * Request
     */
    body?: ExtractFieldsRequest | null;
    path: {
        /**
         * Label Id
         */
        label_id: string;
    };
    query?: never;
    url: '/api/v1/labels/{label_id}/fertilizer-extract';
};

export type PostApiV1LabelsByLabelIdFertilizerExtractErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type PostApiV1LabelsByLabelIdFertilizerExtractError = PostApiV1LabelsByLabelIdFertilizerExtractErrors[keyof PostApiV1LabelsByLabelIdFertilizerExtractErrors];

export type PostApiV1LabelsByLabelIdFertilizerExtractResponses = {
    /**
     * Successful Response
     */
    200: ExtractFertilizerFieldsOutput;
};

export type PostApiV1LabelsByLabelIdFertilizerExtractResponse = PostApiV1LabelsByLabelIdFertilizerExtractResponses[keyof PostApiV1LabelsByLabelIdFertilizerExtractResponses];

export type GetApiV1ProductsData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Limit
         *
         * Page size limit
         */
        limit?: number;
        /**
         * Offset
         *
         * Page offset
         */
        offset?: number;
        /**
         * Product Type
         *
         * Product type
         */
        product_type?: string;
        /**
         * Registration Number
         */
        registration_number?: string | null;
        /**
         * Brand Name En
         */
        brand_name_en?: string | null;
        /**
         * Brand Name Fr
         */
        brand_name_fr?: string | null;
        /**
         * Name En
         */
        name_en?: string | null;
        /**
         * Name Fr
         */
        name_fr?: string | null;
        /**
         * Start Created At
         */
        start_created_at?: string | null;
        /**
         * End Created At
         */
        end_created_at?: string | null;
        /**
         * Start Updated At
         */
        start_updated_at?: string | null;
        /**
         * End Updated At
         */
        end_updated_at?: string | null;
    };
    url: '/api/v1/products';
};

export type GetApiV1ProductsErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetApiV1ProductsError = GetApiV1ProductsErrors[keyof GetApiV1ProductsErrors];

export type GetApiV1ProductsResponses = {
    /**
     * Successful Response
     */
    200: LimitOffsetPageProductPublic;
};

export type GetApiV1ProductsResponse = GetApiV1ProductsResponses[keyof GetApiV1ProductsResponses];

export type PostApiV1ProductsData = {
    body: ProductCreate;
    path?: never;
    query?: never;
    url: '/api/v1/products';
};

export type PostApiV1ProductsErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type PostApiV1ProductsError = PostApiV1ProductsErrors[keyof PostApiV1ProductsErrors];

export type PostApiV1ProductsResponses = {
    /**
     * Successful Response
     */
    201: ProductPublic;
};

export type PostApiV1ProductsResponse = PostApiV1ProductsResponses[keyof PostApiV1ProductsResponses];

export type DeleteApiV1ProductsByProductIdData = {
    body?: never;
    path: {
        /**
         * Product Id
         */
        product_id: string;
    };
    query?: never;
    url: '/api/v1/products/{product_id}';
};

export type DeleteApiV1ProductsByProductIdErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeleteApiV1ProductsByProductIdError = DeleteApiV1ProductsByProductIdErrors[keyof DeleteApiV1ProductsByProductIdErrors];

export type DeleteApiV1ProductsByProductIdResponses = {
    /**
     * Successful Response
     */
    200: Message;
};

export type DeleteApiV1ProductsByProductIdResponse = DeleteApiV1ProductsByProductIdResponses[keyof DeleteApiV1ProductsByProductIdResponses];

export type GetApiV1ProductsByProductIdData = {
    body?: never;
    path: {
        /**
         * Product Id
         */
        product_id: string;
    };
    query?: never;
    url: '/api/v1/products/{product_id}';
};

export type GetApiV1ProductsByProductIdErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetApiV1ProductsByProductIdError = GetApiV1ProductsByProductIdErrors[keyof GetApiV1ProductsByProductIdErrors];

export type GetApiV1ProductsByProductIdResponses = {
    /**
     * Successful Response
     */
    200: ProductPublic;
};

export type GetApiV1ProductsByProductIdResponse = GetApiV1ProductsByProductIdResponses[keyof GetApiV1ProductsByProductIdResponses];

export type PostApiV1PrivateUsersData = {
    body: PrivateUserCreate;
    path?: never;
    query?: never;
    url: '/api/v1/private/users/';
};

export type PostApiV1PrivateUsersErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type PostApiV1PrivateUsersError = PostApiV1PrivateUsersErrors[keyof PostApiV1PrivateUsersErrors];

export type PostApiV1PrivateUsersResponses = {
    /**
     * Successful Response
     */
    200: UserPublic;
};

export type PostApiV1PrivateUsersResponse = PostApiV1PrivateUsersResponses[keyof PostApiV1PrivateUsersResponses];
