// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseURL: `${string}://${string}` | (string & {});
};

/**
 * Body_login_login_access_token
 */
export type BodyLoginLoginAccessToken = {
    /**
     * Grant Type
     */
    grant_type?: string | null;
    /**
     * Username
     */
    username: string;
    /**
     * Password
     */
    password: string;
    /**
     * Scope
     */
    scope?: string;
    /**
     * Client Id
     */
    client_id?: string | null;
    /**
     * Client Secret
     */
    client_secret?: string | null;
};

/**
 * Contact
 */
export type Contact = {
    /**
     * Type
     *
     * Type of contact
     */
    type: string;
    /**
     * Name
     *
     * Company or organization name
     */
    name: string;
    /**
     * Address
     *
     * Full mailing address
     */
    address?: string | null;
    /**
     * Phone
     *
     * Phone number in any format
     */
    phone?: string | null;
    /**
     * Email
     *
     * Email address
     */
    email?: string | null;
    /**
     * Website
     *
     * Website URL
     */
    website?: string | null;
};

/**
 * ExtractFertilizerFieldsOutput
 */
export type ExtractFertilizerFieldsOutput = {
    /**
     * Brand Name En
     *
     * Brand name in English
     */
    brand_name_en?: string | null;
    /**
     * Brand Name Fr
     *
     * Brand name in French
     */
    brand_name_fr?: string | null;
    /**
     * Product Name En
     *
     * Product name in English
     */
    product_name_en?: string | null;
    /**
     * Product Name Fr
     *
     * Product name in French
     */
    product_name_fr?: string | null;
    /**
     * Contacts
     *
     * List of contact information (manufacturer, distributor, etc.)
     */
    contacts?: Array<Contact> | null;
    /**
     * Registration Number
     *
     * Product registration number
     */
    registration_number?: string | null;
    /**
     * Lot Number
     *
     * Lot or batch number
     */
    lot_number?: string | null;
    /**
     * Net Weight
     *
     * Net weight with unit
     */
    net_weight?: string | null;
    /**
     * Volume
     *
     * Volume with unit
     */
    volume?: string | null;
    /**
     * N
     *
     * Nitrogen percentage (NPK analysis)
     */
    n?: string | null;
    /**
     * P
     *
     * Phosphorus percentage (NPK analysis)
     */
    p?: string | null;
    /**
     * K
     *
     * Potassium percentage (NPK analysis)
     */
    k?: string | null;
    /**
     * Ingredients
     *
     * List of ingredients with bilingual names, values and units
     */
    ingredients?: Array<Ingredient> | null;
    /**
     * Guaranteed analysis section with bilingual title and nutrients
     */
    guaranteed_analysis?: GuaranteedAnalysisOutput | null;
    /**
     * Caution En
     *
     * Caution statements in English
     */
    caution_en?: string | null;
    /**
     * Caution Fr
     *
     * Caution statements in French
     */
    caution_fr?: string | null;
    /**
     * Instructions En
     *
     * Usage instructions in English
     */
    instructions_en?: string | null;
    /**
     * Instructions Fr
     *
     * Usage instructions in French
     */
    instructions_fr?: string | null;
};

/**
 * ExtractFieldsRequest
 */
export type ExtractFieldsRequest = {
    /**
     * Field Names
     *
     * List of field names to extract. If None or empty, extract all fields.
     */
    field_names?: Array<LabelDataFieldName | FertilizerLabelDataFieldName> | null;
};

/**
 * FertilizerLabelData
 */
export type FertilizerLabelData = {
    /**
     * N
     */
    n?: string | null;
    /**
     * P
     */
    p?: string | null;
    /**
     * K
     */
    k?: string | null;
    /**
     * Ingredients
     */
    ingredients?: Array<Ingredient> | null;
    guaranteed_analysis?: GuaranteedAnalysisOutput | null;
    /**
     * Caution En
     */
    caution_en?: string | null;
    /**
     * Caution Fr
     */
    caution_fr?: string | null;
    /**
     * Instructions En
     */
    instructions_en?: string | null;
    /**
     * Instructions Fr
     */
    instructions_fr?: string | null;
};

/**
 * FertilizerLabelDataCreate
 */
export type FertilizerLabelDataCreate = {
    /**
     * N
     */
    n?: number | string | null;
    /**
     * P
     */
    p?: number | string | null;
    /**
     * K
     */
    k?: number | string | null;
    /**
     * Ingredients
     */
    ingredients?: Array<Ingredient> | null;
    guaranteed_analysis?: GuaranteedAnalysisInput | null;
    /**
     * Caution En
     */
    caution_en?: string | null;
    /**
     * Caution Fr
     */
    caution_fr?: string | null;
    /**
     * Instructions En
     */
    instructions_en?: string | null;
    /**
     * Instructions Fr
     */
    instructions_fr?: string | null;
};

/**
 * FertilizerLabelDataFieldName
 *
 * Valid field names for FertilizerLabelDataMeta.
 */
export type FertilizerLabelDataFieldName = 'n' | 'p' | 'k' | 'ingredients' | 'guaranteed_analysis' | 'caution_en' | 'caution_fr' | 'instructions_en' | 'instructions_fr';

/**
 * FertilizerLabelDataMetaResponse
 */
export type FertilizerLabelDataMetaResponse = {
    /**
     * Field Name
     */
    field_name: string;
    /**
     * Needs Review
     */
    needs_review: boolean;
    /**
     * Note
     */
    note: string | null;
    /**
     * Ai Generated
     */
    ai_generated: boolean;
};

/**
 * FertilizerLabelDataMetaUpdate
 */
export type FertilizerLabelDataMetaUpdate = {
    field_name: FertilizerLabelDataFieldName;
    /**
     * Needs Review
     */
    needs_review?: boolean | null;
    /**
     * Note
     */
    note?: string | null;
    /**
     * Ai Generated
     */
    ai_generated?: boolean | null;
};

/**
 * FertilizerLabelDataUpdate
 */
export type FertilizerLabelDataUpdate = {
    /**
     * N
     */
    n?: number | string | null;
    /**
     * P
     */
    p?: number | string | null;
    /**
     * K
     */
    k?: number | string | null;
    /**
     * Ingredients
     */
    ingredients?: Array<Ingredient> | null;
    guaranteed_analysis?: GuaranteedAnalysisInput | null;
    /**
     * Caution En
     */
    caution_en?: string | null;
    /**
     * Caution Fr
     */
    caution_fr?: string | null;
    /**
     * Instructions En
     */
    instructions_en?: string | null;
    /**
     * Instructions Fr
     */
    instructions_fr?: string | null;
};

/**
 * GuaranteedAnalysis
 */
export type GuaranteedAnalysisInput = {
    /**
     * Title En
     *
     * Section title in English from label
     */
    title_en: string;
    /**
     * Title Fr
     *
     * Section title in French from label
     */
    title_fr?: string | null;
    /**
     * Is Minimum
     *
     * True if title contains 'Minimum', false otherwise
     */
    is_minimum: boolean;
    /**
     * Nutrients
     *
     * List of nutrients with bilingual names, values and units
     */
    nutrients: Array<NutrientInput>;
};

/**
 * GuaranteedAnalysis
 */
export type GuaranteedAnalysisOutput = {
    /**
     * Title En
     *
     * Section title in English from label
     */
    title_en: string;
    /**
     * Title Fr
     *
     * Section title in French from label
     */
    title_fr?: string | null;
    /**
     * Is Minimum
     *
     * True if title contains 'Minimum', false otherwise
     */
    is_minimum: boolean;
    /**
     * Nutrients
     *
     * List of nutrients with bilingual names, values and units
     */
    nutrients: Array<NutrientOutput>;
};

/**
 * HTTPValidationError
 */
export type HttpValidationError = {
    /**
     * Detail
     */
    detail?: Array<ValidationError>;
};

/**
 * Health
 */
export type Health = {
    /**
     * Status
     */
    status: string;
};

/**
 * Ingredient
 */
export type Ingredient = {
    /**
     * Name En
     *
     * Ingredient name in English as it appears on the label
     */
    name_en: string;
    /**
     * Name Fr
     *
     * Ingredient name in French as it appears on the label
     */
    name_fr?: string | null;
    /**
     * Value
     *
     * Ingredient percentage or amount.
     */
    value: string;
    /**
     * Unit
     *
     * Unit of measurement
     */
    unit: string;
};

/**
 * LabelCreate
 */
export type LabelCreate = {
    /**
     * Product Type
     */
    product_type: string;
    /**
     * Product Id
     */
    product_id?: string | null;
};

/**
 * LabelCreated
 *
 * Response schema for label creation.
 */
export type LabelCreated = {
    /**
     * Id
     */
    id: string;
};

/**
 * LabelData
 */
export type LabelData = {
    /**
     * Brand Name En
     */
    brand_name_en?: string | null;
    /**
     * Brand Name Fr
     */
    brand_name_fr?: string | null;
    /**
     * Product Name En
     */
    product_name_en?: string | null;
    /**
     * Product Name Fr
     */
    product_name_fr?: string | null;
    /**
     * Contacts
     */
    contacts?: Array<Contact> | null;
    /**
     * Registration Number
     */
    registration_number?: string | null;
    /**
     * Lot Number
     */
    lot_number?: string | null;
    /**
     * Net Weight
     */
    net_weight?: string | null;
    /**
     * Volume
     */
    volume?: string | null;
};

/**
 * LabelDataCreate
 */
export type LabelDataCreate = {
    /**
     * Brand Name En
     */
    brand_name_en?: string | null;
    /**
     * Brand Name Fr
     */
    brand_name_fr?: string | null;
    /**
     * Product Name En
     */
    product_name_en?: string | null;
    /**
     * Product Name Fr
     */
    product_name_fr?: string | null;
    /**
     * Contacts
     */
    contacts?: Array<Contact> | null;
    /**
     * Registration Number
     */
    registration_number?: string | null;
    /**
     * Lot Number
     */
    lot_number?: string | null;
    /**
     * Net Weight
     */
    net_weight?: string | null;
    /**
     * Volume
     */
    volume?: string | null;
};

/**
 * LabelDataFieldMetaResponse
 */
export type LabelDataFieldMetaResponse = {
    /**
     * Field Name
     */
    field_name: string;
    /**
     * Needs Review
     */
    needs_review: boolean;
    /**
     * Note
     */
    note: string | null;
    /**
     * Ai Generated
     */
    ai_generated: boolean;
};

/**
 * LabelDataFieldMetaUpdate
 */
export type LabelDataFieldMetaUpdate = {
    field_name: LabelDataFieldName;
    /**
     * Needs Review
     */
    needs_review?: boolean | null;
    /**
     * Note
     */
    note?: string | null;
    /**
     * Ai Generated
     */
    ai_generated?: boolean | null;
};

/**
 * LabelDataFieldName
 *
 * Valid field names for LabelDataFieldMeta.
 */
export type LabelDataFieldName = 'brand_name_en' | 'brand_name_fr' | 'product_name_en' | 'product_name_fr' | 'contacts' | 'registration_number' | 'lot_number' | 'net_weight' | 'volume';

/**
 * LabelDataLite
 */
export type LabelDataLite = {
    /**
     * Brand Name En
     */
    brand_name_en?: string | null;
    /**
     * Brand Name Fr
     */
    brand_name_fr?: string | null;
    /**
     * Product Name En
     */
    product_name_en?: string | null;
    /**
     * Product Name Fr
     */
    product_name_fr?: string | null;
};

/**
 * LabelDataUpdate
 */
export type LabelDataUpdate = {
    /**
     * Brand Name En
     */
    brand_name_en?: string | null;
    /**
     * Brand Name Fr
     */
    brand_name_fr?: string | null;
    /**
     * Product Name En
     */
    product_name_en?: string | null;
    /**
     * Product Name Fr
     */
    product_name_fr?: string | null;
    /**
     * Contacts
     */
    contacts?: Array<Contact> | null;
    /**
     * Registration Number
     */
    registration_number?: string | null;
    /**
     * Lot Number
     */
    lot_number?: string | null;
    /**
     * Net Weight
     */
    net_weight?: string | null;
    /**
     * Volume
     */
    volume?: string | null;
};

/**
 * LabelDetail
 */
export type LabelDetail = {
    /**
     * Id
     */
    id: string;
    /**
     * Product Id
     */
    product_id?: string | null;
    /**
     * Created By Id
     */
    created_by_id: string;
    review_status: ReviewStatus;
    /**
     * Created At
     */
    created_at: string;
    /**
     * Updated At
     */
    updated_at: string;
    product_type: ProductTypePublic;
    created_by: UserPublic;
    /**
     * Images
     */
    images?: Array<LabelImageDetail>;
};

/**
 * LabelImageDetail
 */
export type LabelImageDetail = {
    /**
     * Id
     */
    id: string;
    /**
     * Label Id
     */
    label_id: string;
    /**
     * Display Filename
     */
    display_filename: string;
    /**
     * File Path
     */
    file_path: string;
    /**
     * Sequence Order
     */
    sequence_order: number;
    status: UploadStatus;
    /**
     * Created At
     */
    created_at: string;
    /**
     * Updated At
     */
    updated_at: string;
    /**
     * Current Image Count
     */
    current_image_count?: number | null;
};

/**
 * LabelListItem
 *
 * Schema for label list items.
 */
export type LabelListItem = {
    /**
     * Id
     */
    id: string;
    review_status: ReviewStatus;
    /**
     * Created At
     */
    created_at: string;
    /**
     * Updated At
     */
    updated_at: string;
    label_data?: LabelDataLite | null;
};

/**
 * LabelReviewStatusUpdate
 */
export type LabelReviewStatusUpdate = {
    review_status: ReviewStatus;
};

/**
 * LabelUpdate
 */
export type LabelUpdate = {
    /**
     * Product Id
     */
    product_id?: string | null;
};

/**
 * LimitOffsetPage[LabelListItem]
 */
export type LimitOffsetPageLabelListItem = {
    /**
     * Items
     */
    items: Array<LabelListItem>;
    /**
     * Total
     */
    total: number;
    /**
     * Limit
     */
    limit: number;
    /**
     * Offset
     */
    offset: number;
};

/**
 * LimitOffsetPage[ProductPublic]
 */
export type LimitOffsetPageProductPublic = {
    /**
     * Items
     */
    items: Array<ProductPublic>;
    /**
     * Total
     */
    total: number;
    /**
     * Limit
     */
    limit: number;
    /**
     * Offset
     */
    offset: number;
};

/**
 * Message
 */
export type Message = {
    /**
     * Message
     */
    message: string;
};

/**
 * NewPassword
 */
export type NewPassword = {
    /**
     * Token
     */
    token: string;
    /**
     * New Password
     */
    new_password: string;
};

/**
 * Nutrient
 */
export type NutrientInput = {
    /**
     * Name En
     *
     * Nutrient name in English as it appears on the label
     */
    name_en: string;
    /**
     * Name Fr
     *
     * Nutrient name in French as it appears on the label
     */
    name_fr?: string | null;
    /**
     * Value
     *
     * Nutrient percentage value
     */
    value: number | string;
    /**
     * Unit
     *
     * Unit of measurement
     */
    unit: string;
};

/**
 * Nutrient
 */
export type NutrientOutput = {
    /**
     * Name En
     *
     * Nutrient name in English as it appears on the label
     */
    name_en: string;
    /**
     * Name Fr
     *
     * Nutrient name in French as it appears on the label
     */
    name_fr?: string | null;
    /**
     * Value
     *
     * Nutrient percentage value
     */
    value: string;
    /**
     * Unit
     *
     * Unit of measurement
     */
    unit: string;
};

/**
 * PresignedDownloadUrlResponse
 *
 * Response schema for presigned download URL request.
 */
export type PresignedDownloadUrlResponse = {
    /**
     * Presigned Url
     */
    presigned_url: string;
};

/**
 * PresignedUploadUrlResponse
 *
 * Response schema for presigned upload URL request.
 */
export type PresignedUploadUrlResponse = {
    /**
     * Url
     */
    url: string;
    /**
     * Expires At
     */
    expires_at: string;
};

/**
 * PresignedUrlRequest
 *
 * Request schema for individual presigned URL generation.
 */
export type PresignedUrlRequest = {
    /**
     * Display Filename
     */
    display_filename: string;
    /**
     * Content Type
     */
    content_type: 'image/png' | 'image/jpeg' | 'image/webp';
    /**
     * Sequence Order
     */
    sequence_order: number;
};

/**
 * PrivateUserCreate
 */
export type PrivateUserCreate = {
    /**
     * Email
     */
    email: string;
    /**
     * Password
     */
    password: string;
    /**
     * First Name
     */
    first_name?: string | null;
    /**
     * Last Name
     */
    last_name?: string | null;
};

/**
 * ProductPublic
 */
export type ProductPublic = {
    /**
     * Id
     */
    id: string;
    /**
     * Name En
     */
    name_en?: string | null;
    /**
     * Name Fr
     */
    name_fr?: string | null;
    /**
     * Registration Number
     */
    registration_number: string;
};

/**
 * ProductTypePublic
 */
export type ProductTypePublic = {
    /**
     * Code
     */
    code: string;
    /**
     * Name En
     */
    name_en?: string | null;
    /**
     * Name Fr
     */
    name_fr?: string | null;
    /**
     * Is Active
     */
    is_active?: boolean;
    /**
     * Id
     */
    id: string;
    /**
     * Created At
     */
    created_at: string;
    /**
     * Updated At
     */
    updated_at: string;
};

/**
 * Readiness
 */
export type Readiness = {
    /**
     * Status
     */
    status: string;
    /**
     * Database
     */
    database: string;
};

/**
 * ReviewStatus
 */
export type ReviewStatus = 'not_started' | 'in_progress' | 'completed';

/**
 * Token
 */
export type Token = {
    /**
     * Access Token
     */
    access_token: string;
    /**
     * Token Type
     */
    token_type?: string;
};

/**
 * UpdatePassword
 */
export type UpdatePassword = {
    /**
     * Current Password
     */
    current_password: string;
    /**
     * New Password
     */
    new_password: string;
};

/**
 * UploadCompletionRequest
 *
 * Request schema for upload completion notification.
 */
export type UploadCompletionRequest = {
    /**
     * Storage File Path
     */
    storage_file_path: string;
};

/**
 * UploadStatus
 */
export type UploadStatus = 'pending' | 'completed';

/**
 * UserCreate
 */
export type UserCreate = {
    /**
     * Email
     */
    email: string;
    /**
     * Is Active
     */
    is_active?: boolean;
    /**
     * Is Superuser
     */
    is_superuser?: boolean;
    /**
     * First Name
     */
    first_name?: string | null;
    /**
     * Last Name
     */
    last_name?: string | null;
};

/**
 * UserPublic
 */
export type UserPublic = {
    /**
     * Email
     */
    email: string;
    /**
     * Is Active
     */
    is_active?: boolean;
    /**
     * Is Superuser
     */
    is_superuser?: boolean;
    /**
     * First Name
     */
    first_name?: string | null;
    /**
     * Last Name
     */
    last_name?: string | null;
    /**
     * Id
     */
    id: string;
};

/**
 * UserUpdate
 */
export type UserUpdate = {
    /**
     * Email
     */
    email?: string | null;
    /**
     * Password
     */
    password?: null;
    /**
     * Is Active
     */
    is_active?: boolean | null;
    /**
     * Is Superuser
     */
    is_superuser?: boolean | null;
    /**
     * First Name
     */
    first_name?: string | null;
    /**
     * Last Name
     */
    last_name?: string | null;
};

/**
 * UserUpdateMe
 */
export type UserUpdateMe = {
    /**
     * First Name
     */
    first_name?: string | null;
    /**
     * Last Name
     */
    last_name?: string | null;
    /**
     * Email
     */
    email?: string | null;
};

/**
 * UsersPublic
 */
export type UsersPublic = {
    /**
     * Data
     */
    data: Array<UserPublic>;
    /**
     * Count
     */
    count: number;
};

/**
 * ValidationError
 */
export type ValidationError = {
    /**
     * Location
     */
    loc: Array<string | number>;
    /**
     * Message
     */
    msg: string;
    /**
     * Error Type
     */
    type: string;
};

/**
 * UserCreate
 */
export type UserCreateWritable = {
    /**
     * Email
     */
    email: string;
    /**
     * Is Active
     */
    is_active?: boolean;
    /**
     * Is Superuser
     */
    is_superuser?: boolean;
    /**
     * First Name
     */
    first_name?: string | null;
    /**
     * Last Name
     */
    last_name?: string | null;
    /**
     * Password
     */
    password: string;
};

/**
 * UserUpdate
 */
export type UserUpdateWritable = {
    /**
     * Email
     */
    email?: string | null;
    /**
     * Password
     */
    password?: string | null;
    /**
     * Is Active
     */
    is_active?: boolean | null;
    /**
     * Is Superuser
     */
    is_superuser?: boolean | null;
    /**
     * First Name
     */
    first_name?: string | null;
    /**
     * Last Name
     */
    last_name?: string | null;
};

export type HealthLivenessData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/healthz';
};

export type HealthLivenessResponses = {
    /**
     * Successful Response
     */
    200: Health;
};

export type HealthLivenessResponse = HealthLivenessResponses[keyof HealthLivenessResponses];

export type HealthReadinessData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/readyz';
};

export type HealthReadinessResponses = {
    /**
     * Successful Response
     */
    200: Readiness;
};

export type HealthReadinessResponse = HealthReadinessResponses[keyof HealthReadinessResponses];

export type LoginLoginAccessTokenData = {
    body: BodyLoginLoginAccessToken;
    path?: never;
    query?: never;
    url: '/api/v1/login/access-token';
};

export type LoginLoginAccessTokenErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type LoginLoginAccessTokenError = LoginLoginAccessTokenErrors[keyof LoginLoginAccessTokenErrors];

export type LoginLoginAccessTokenResponses = {
    /**
     * Successful Response
     */
    200: Token;
};

export type LoginLoginAccessTokenResponse = LoginLoginAccessTokenResponses[keyof LoginLoginAccessTokenResponses];

export type LoginTestTokenData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/login/test-token';
};

export type LoginTestTokenResponses = {
    /**
     * Successful Response
     */
    200: UserPublic;
};

export type LoginTestTokenResponse = LoginTestTokenResponses[keyof LoginTestTokenResponses];

export type LoginRecoverPasswordData = {
    body?: never;
    path: {
        /**
         * Email
         */
        email: string;
    };
    query?: never;
    url: '/api/v1/password-recovery/{email}';
};

export type LoginRecoverPasswordErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type LoginRecoverPasswordError = LoginRecoverPasswordErrors[keyof LoginRecoverPasswordErrors];

export type LoginRecoverPasswordResponses = {
    /**
     * Successful Response
     */
    200: Message;
};

export type LoginRecoverPasswordResponse = LoginRecoverPasswordResponses[keyof LoginRecoverPasswordResponses];

export type LoginResetPasswordData = {
    body: NewPassword;
    path?: never;
    query?: never;
    url: '/api/v1/reset-password/';
};

export type LoginResetPasswordErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type LoginResetPasswordError = LoginResetPasswordErrors[keyof LoginResetPasswordErrors];

export type LoginResetPasswordResponses = {
    /**
     * Successful Response
     */
    200: Message;
};

export type LoginResetPasswordResponse = LoginResetPasswordResponses[keyof LoginResetPasswordResponses];

export type LoginRecoverPasswordHtmlContentData = {
    body?: never;
    path: {
        /**
         * Email
         */
        email: string;
    };
    query?: never;
    url: '/api/v1/password-recovery-html-content/{email}';
};

export type LoginRecoverPasswordHtmlContentErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type LoginRecoverPasswordHtmlContentError = LoginRecoverPasswordHtmlContentErrors[keyof LoginRecoverPasswordHtmlContentErrors];

export type LoginRecoverPasswordHtmlContentResponses = {
    /**
     * Successful Response
     */
    200: string;
};

export type LoginRecoverPasswordHtmlContentResponse = LoginRecoverPasswordHtmlContentResponses[keyof LoginRecoverPasswordHtmlContentResponses];

export type UsersReadUsersData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Skip
         */
        skip?: number;
        /**
         * Limit
         */
        limit?: number;
    };
    url: '/api/v1/users';
};

export type UsersReadUsersErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UsersReadUsersError = UsersReadUsersErrors[keyof UsersReadUsersErrors];

export type UsersReadUsersResponses = {
    /**
     * Successful Response
     */
    200: UsersPublic;
};

export type UsersReadUsersResponse = UsersReadUsersResponses[keyof UsersReadUsersResponses];

export type UsersCreateUserData = {
    body: UserCreateWritable;
    path?: never;
    query?: never;
    url: '/api/v1/users';
};

export type UsersCreateUserErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UsersCreateUserError = UsersCreateUserErrors[keyof UsersCreateUserErrors];

export type UsersCreateUserResponses = {
    /**
     * Successful Response
     */
    201: UserPublic;
};

export type UsersCreateUserResponse = UsersCreateUserResponses[keyof UsersCreateUserResponses];

export type UsersDeleteUserMeData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/users/me';
};

export type UsersDeleteUserMeResponses = {
    /**
     * Successful Response
     */
    200: Message;
};

export type UsersDeleteUserMeResponse = UsersDeleteUserMeResponses[keyof UsersDeleteUserMeResponses];

export type UsersReadUserMeData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/v1/users/me';
};

export type UsersReadUserMeResponses = {
    /**
     * Successful Response
     */
    200: UserPublic;
};

export type UsersReadUserMeResponse = UsersReadUserMeResponses[keyof UsersReadUserMeResponses];

export type UsersUpdateUserMeData = {
    body: UserUpdateMe;
    path?: never;
    query?: never;
    url: '/api/v1/users/me';
};

export type UsersUpdateUserMeErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UsersUpdateUserMeError = UsersUpdateUserMeErrors[keyof UsersUpdateUserMeErrors];

export type UsersUpdateUserMeResponses = {
    /**
     * Successful Response
     */
    200: UserPublic;
};

export type UsersUpdateUserMeResponse = UsersUpdateUserMeResponses[keyof UsersUpdateUserMeResponses];

export type UsersUpdatePasswordMeData = {
    body: UpdatePassword;
    path?: never;
    query?: never;
    url: '/api/v1/users/me/password';
};

export type UsersUpdatePasswordMeErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UsersUpdatePasswordMeError = UsersUpdatePasswordMeErrors[keyof UsersUpdatePasswordMeErrors];

export type UsersUpdatePasswordMeResponses = {
    /**
     * Successful Response
     */
    200: Message;
};

export type UsersUpdatePasswordMeResponse = UsersUpdatePasswordMeResponses[keyof UsersUpdatePasswordMeResponses];

export type UsersDeleteUserData = {
    body?: never;
    path: {
        /**
         * User Id
         */
        user_id: string;
    };
    query?: never;
    url: '/api/v1/users/{user_id}';
};

export type UsersDeleteUserErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UsersDeleteUserError = UsersDeleteUserErrors[keyof UsersDeleteUserErrors];

export type UsersDeleteUserResponses = {
    /**
     * Successful Response
     */
    200: Message;
};

export type UsersDeleteUserResponse = UsersDeleteUserResponses[keyof UsersDeleteUserResponses];

export type UsersReadUserByIdData = {
    body?: never;
    path: {
        /**
         * User Id
         */
        user_id: string;
    };
    query?: never;
    url: '/api/v1/users/{user_id}';
};

export type UsersReadUserByIdErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UsersReadUserByIdError = UsersReadUserByIdErrors[keyof UsersReadUserByIdErrors];

export type UsersReadUserByIdResponses = {
    /**
     * Successful Response
     */
    200: UserPublic;
};

export type UsersReadUserByIdResponse = UsersReadUserByIdResponses[keyof UsersReadUserByIdResponses];

export type UsersUpdateUserData = {
    body: UserUpdateWritable;
    path: {
        /**
         * User Id
         */
        user_id: string;
    };
    query?: never;
    url: '/api/v1/users/{user_id}';
};

export type UsersUpdateUserErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UsersUpdateUserError = UsersUpdateUserErrors[keyof UsersUpdateUserErrors];

export type UsersUpdateUserResponses = {
    /**
     * Successful Response
     */
    200: UserPublic;
};

export type UsersUpdateUserResponse = UsersUpdateUserResponses[keyof UsersUpdateUserResponses];

export type LabelsReadLabelsData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Product Type
         *
         * Product type
         */
        product_type?: string;
        /**
         * Review Status
         *
         * Filter by review status
         */
        review_status?: ReviewStatus | null;
        /**
         * Unlinked
         *
         * Filter labels not linked to a product (product_id is null)
         */
        unlinked?: boolean | null;
        /**
         * Order By
         *
         * Field to sort by
         */
        order_by?: string;
        /**
         * Order
         *
         * Sort direction (asc or desc)
         */
        order?: string;
        /**
         * Limit
         *
         * Page size limit
         */
        limit?: number;
        /**
         * Offset
         *
         * Page offset
         */
        offset?: number;
    };
    url: '/api/v1/labels';
};

export type LabelsReadLabelsErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type LabelsReadLabelsError = LabelsReadLabelsErrors[keyof LabelsReadLabelsErrors];

export type LabelsReadLabelsResponses = {
    /**
     * Successful Response
     */
    200: LimitOffsetPageLabelListItem;
};

export type LabelsReadLabelsResponse = LabelsReadLabelsResponses[keyof LabelsReadLabelsResponses];

export type LabelsCreateLabelData = {
    body: LabelCreate;
    path?: never;
    query?: never;
    url: '/api/v1/labels';
};

export type LabelsCreateLabelErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type LabelsCreateLabelError = LabelsCreateLabelErrors[keyof LabelsCreateLabelErrors];

export type LabelsCreateLabelResponses = {
    /**
     * Successful Response
     */
    201: LabelCreated;
};

export type LabelsCreateLabelResponse = LabelsCreateLabelResponses[keyof LabelsCreateLabelResponses];

export type LabelsDeleteLabelData = {
    body?: never;
    path: {
        /**
         * Label Id
         */
        label_id: string;
    };
    query?: never;
    url: '/api/v1/labels/{label_id}';
};

export type LabelsDeleteLabelErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type LabelsDeleteLabelError = LabelsDeleteLabelErrors[keyof LabelsDeleteLabelErrors];

export type LabelsDeleteLabelResponses = {
    /**
     * Successful Response
     */
    204: void;
};

export type LabelsDeleteLabelResponse = LabelsDeleteLabelResponses[keyof LabelsDeleteLabelResponses];

export type LabelsReadLabelData = {
    body?: never;
    path: {
        /**
         * Label Id
         */
        label_id: string;
    };
    query?: never;
    url: '/api/v1/labels/{label_id}';
};

export type LabelsReadLabelErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type LabelsReadLabelError = LabelsReadLabelErrors[keyof LabelsReadLabelErrors];

export type LabelsReadLabelResponses = {
    /**
     * Successful Response
     */
    200: LabelDetail;
};

export type LabelsReadLabelResponse = LabelsReadLabelResponses[keyof LabelsReadLabelResponses];

export type LabelsUpdateLabelData = {
    body: LabelUpdate;
    path: {
        /**
         * Label Id
         */
        label_id: string;
    };
    query?: never;
    url: '/api/v1/labels/{label_id}';
};

export type LabelsUpdateLabelErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type LabelsUpdateLabelError = LabelsUpdateLabelErrors[keyof LabelsUpdateLabelErrors];

export type LabelsUpdateLabelResponses = {
    /**
     * Successful Response
     */
    200: LabelDetail;
};

export type LabelsUpdateLabelResponse = LabelsUpdateLabelResponses[keyof LabelsUpdateLabelResponses];

export type LabelsUpdateLabelReviewStatusData = {
    body: LabelReviewStatusUpdate;
    path: {
        /**
         * Label Id
         */
        label_id: string;
    };
    query?: never;
    url: '/api/v1/labels/{label_id}/review-status';
};

export type LabelsUpdateLabelReviewStatusErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type LabelsUpdateLabelReviewStatusError = LabelsUpdateLabelReviewStatusErrors[keyof LabelsUpdateLabelReviewStatusErrors];

export type LabelsUpdateLabelReviewStatusResponses = {
    /**
     * Successful Response
     */
    200: LabelDetail;
};

export type LabelsUpdateLabelReviewStatusResponse = LabelsUpdateLabelReviewStatusResponses[keyof LabelsUpdateLabelReviewStatusResponses];

export type LabelsReadLabelImagesData = {
    body?: never;
    path: {
        /**
         * Label Id
         */
        label_id: string;
    };
    query?: never;
    url: '/api/v1/labels/{label_id}/images';
};

export type LabelsReadLabelImagesErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type LabelsReadLabelImagesError = LabelsReadLabelImagesErrors[keyof LabelsReadLabelImagesErrors];

export type LabelsReadLabelImagesResponses = {
    /**
     * Response Labels Read Label Images
     *
     * Successful Response
     */
    200: Array<LabelImageDetail>;
};

export type LabelsReadLabelImagesResponse = LabelsReadLabelImagesResponses[keyof LabelsReadLabelImagesResponses];

export type LabelsCreateLabelImageData = {
    body: PresignedUrlRequest;
    path: {
        /**
         * Label Id
         */
        label_id: string;
    };
    query?: never;
    url: '/api/v1/labels/{label_id}/images';
};

export type LabelsCreateLabelImageErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type LabelsCreateLabelImageError = LabelsCreateLabelImageErrors[keyof LabelsCreateLabelImageErrors];

export type LabelsCreateLabelImageResponses = {
    /**
     * Successful Response
     */
    201: LabelImageDetail;
};

export type LabelsCreateLabelImageResponse = LabelsCreateLabelImageResponses[keyof LabelsCreateLabelImageResponses];

export type LabelsDeleteLabelImageData = {
    body?: never;
    path: {
        /**
         * Image Id
         */
        image_id: string;
        /**
         * Label Id
         */
        label_id: string;
    };
    query?: never;
    url: '/api/v1/labels/{label_id}/images/{image_id}';
};

export type LabelsDeleteLabelImageErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type LabelsDeleteLabelImageError = LabelsDeleteLabelImageErrors[keyof LabelsDeleteLabelImageErrors];

export type LabelsDeleteLabelImageResponses = {
    /**
     * Successful Response
     */
    204: void;
};

export type LabelsDeleteLabelImageResponse = LabelsDeleteLabelImageResponses[keyof LabelsDeleteLabelImageResponses];

export type LabelsReadLabelImageData = {
    body?: never;
    path: {
        /**
         * Image Id
         */
        image_id: string;
        /**
         * Label Id
         */
        label_id: string;
    };
    query?: never;
    url: '/api/v1/labels/{label_id}/images/{image_id}';
};

export type LabelsReadLabelImageErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type LabelsReadLabelImageError = LabelsReadLabelImageErrors[keyof LabelsReadLabelImageErrors];

export type LabelsReadLabelImageResponses = {
    /**
     * Successful Response
     */
    200: LabelImageDetail;
};

export type LabelsReadLabelImageResponse = LabelsReadLabelImageResponses[keyof LabelsReadLabelImageResponses];

export type LabelsCompleteLabelImageUploadData = {
    body: UploadCompletionRequest;
    path: {
        /**
         * Label Id
         */
        label_id: string;
    };
    query?: never;
    url: '/api/v1/labels/{label_id}/images/complete';
};

export type LabelsCompleteLabelImageUploadErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type LabelsCompleteLabelImageUploadError = LabelsCompleteLabelImageUploadErrors[keyof LabelsCompleteLabelImageUploadErrors];

export type LabelsCompleteLabelImageUploadResponses = {
    /**
     * Successful Response
     */
    200: LabelImageDetail;
};

export type LabelsCompleteLabelImageUploadResponse = LabelsCompleteLabelImageUploadResponses[keyof LabelsCompleteLabelImageUploadResponses];

export type LabelsGetLabelImagePresignedUploadUrlData = {
    body?: never;
    path: {
        /**
         * Image Id
         */
        image_id: string;
        /**
         * Label Id
         */
        label_id: string;
    };
    query: {
        /**
         * Content Type
         *
         * Content type (image/png, image/jpeg, image/webp)
         */
        content_type: string;
    };
    url: '/api/v1/labels/{label_id}/images/{image_id}/presigned-upload-url';
};

export type LabelsGetLabelImagePresignedUploadUrlErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type LabelsGetLabelImagePresignedUploadUrlError = LabelsGetLabelImagePresignedUploadUrlErrors[keyof LabelsGetLabelImagePresignedUploadUrlErrors];

export type LabelsGetLabelImagePresignedUploadUrlResponses = {
    /**
     * Successful Response
     */
    200: PresignedUploadUrlResponse;
};

export type LabelsGetLabelImagePresignedUploadUrlResponse = LabelsGetLabelImagePresignedUploadUrlResponses[keyof LabelsGetLabelImagePresignedUploadUrlResponses];

export type LabelsGetLabelImagePresignedDownloadUrlData = {
    body?: never;
    path: {
        /**
         * Image Id
         */
        image_id: string;
        /**
         * Label Id
         */
        label_id: string;
    };
    query?: never;
    url: '/api/v1/labels/{label_id}/images/{image_id}/presigned-download-url';
};

export type LabelsGetLabelImagePresignedDownloadUrlErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type LabelsGetLabelImagePresignedDownloadUrlError = LabelsGetLabelImagePresignedDownloadUrlErrors[keyof LabelsGetLabelImagePresignedDownloadUrlErrors];

export type LabelsGetLabelImagePresignedDownloadUrlResponses = {
    /**
     * Successful Response
     */
    200: PresignedDownloadUrlResponse;
};

export type LabelsGetLabelImagePresignedDownloadUrlResponse = LabelsGetLabelImagePresignedDownloadUrlResponses[keyof LabelsGetLabelImagePresignedDownloadUrlResponses];

export type LabelsReadLabelDataData = {
    body?: never;
    path: {
        /**
         * Label Id
         */
        label_id: string;
    };
    query?: never;
    url: '/api/v1/labels/{label_id}/data';
};

export type LabelsReadLabelDataErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type LabelsReadLabelDataError = LabelsReadLabelDataErrors[keyof LabelsReadLabelDataErrors];

export type LabelsReadLabelDataResponses = {
    /**
     * Successful Response
     */
    200: LabelData;
};

export type LabelsReadLabelDataResponse = LabelsReadLabelDataResponses[keyof LabelsReadLabelDataResponses];

export type LabelsUpdateLabelDataData = {
    body: LabelDataUpdate;
    path: {
        /**
         * Label Id
         */
        label_id: string;
    };
    query?: never;
    url: '/api/v1/labels/{label_id}/data';
};

export type LabelsUpdateLabelDataErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type LabelsUpdateLabelDataError = LabelsUpdateLabelDataErrors[keyof LabelsUpdateLabelDataErrors];

export type LabelsUpdateLabelDataResponses = {
    /**
     * Successful Response
     */
    200: LabelData;
};

export type LabelsUpdateLabelDataResponse = LabelsUpdateLabelDataResponses[keyof LabelsUpdateLabelDataResponses];

export type LabelsCreateLabelDataData = {
    body: LabelDataCreate;
    path: {
        /**
         * Label Id
         */
        label_id: string;
    };
    query?: never;
    url: '/api/v1/labels/{label_id}/data';
};

export type LabelsCreateLabelDataErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type LabelsCreateLabelDataError = LabelsCreateLabelDataErrors[keyof LabelsCreateLabelDataErrors];

export type LabelsCreateLabelDataResponses = {
    /**
     * Successful Response
     */
    201: LabelData;
};

export type LabelsCreateLabelDataResponse = LabelsCreateLabelDataResponses[keyof LabelsCreateLabelDataResponses];

export type LabelsReadLabelDataMetaData = {
    body?: never;
    path: {
        /**
         * Label Id
         */
        label_id: string;
    };
    query?: {
        /**
         * Field Name
         *
         * Filter by field name
         */
        field_name?: string | null;
        /**
         * Needs Review
         *
         * Filter by needs_review flag
         */
        needs_review?: boolean | null;
    };
    url: '/api/v1/labels/{label_id}/data/meta';
};

export type LabelsReadLabelDataMetaErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type LabelsReadLabelDataMetaError = LabelsReadLabelDataMetaErrors[keyof LabelsReadLabelDataMetaErrors];

export type LabelsReadLabelDataMetaResponses = {
    /**
     * Response Labels Read Label Data Meta
     *
     * Successful Response
     */
    200: Array<LabelDataFieldMetaResponse>;
};

export type LabelsReadLabelDataMetaResponse = LabelsReadLabelDataMetaResponses[keyof LabelsReadLabelDataMetaResponses];

export type LabelsUpdateLabelDataMetaData = {
    body: LabelDataFieldMetaUpdate;
    path: {
        /**
         * Label Id
         */
        label_id: string;
    };
    query?: never;
    url: '/api/v1/labels/{label_id}/data/meta';
};

export type LabelsUpdateLabelDataMetaErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type LabelsUpdateLabelDataMetaError = LabelsUpdateLabelDataMetaErrors[keyof LabelsUpdateLabelDataMetaErrors];

export type LabelsUpdateLabelDataMetaResponses = {
    /**
     * Successful Response
     */
    200: LabelDataFieldMetaResponse;
};

export type LabelsUpdateLabelDataMetaResponse = LabelsUpdateLabelDataMetaResponses[keyof LabelsUpdateLabelDataMetaResponses];

export type LabelsReadFertilizerLabelDataData = {
    body?: never;
    path: {
        /**
         * Label Id
         */
        label_id: string;
    };
    query?: never;
    url: '/api/v1/labels/{label_id}/fertilizer-data';
};

export type LabelsReadFertilizerLabelDataErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type LabelsReadFertilizerLabelDataError = LabelsReadFertilizerLabelDataErrors[keyof LabelsReadFertilizerLabelDataErrors];

export type LabelsReadFertilizerLabelDataResponses = {
    /**
     * Successful Response
     */
    200: FertilizerLabelData;
};

export type LabelsReadFertilizerLabelDataResponse = LabelsReadFertilizerLabelDataResponses[keyof LabelsReadFertilizerLabelDataResponses];

export type LabelsUpdateFertilizerLabelDataData = {
    body: FertilizerLabelDataUpdate;
    path: {
        /**
         * Label Id
         */
        label_id: string;
    };
    query?: never;
    url: '/api/v1/labels/{label_id}/fertilizer-data';
};

export type LabelsUpdateFertilizerLabelDataErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type LabelsUpdateFertilizerLabelDataError = LabelsUpdateFertilizerLabelDataErrors[keyof LabelsUpdateFertilizerLabelDataErrors];

export type LabelsUpdateFertilizerLabelDataResponses = {
    /**
     * Successful Response
     */
    200: FertilizerLabelData;
};

export type LabelsUpdateFertilizerLabelDataResponse = LabelsUpdateFertilizerLabelDataResponses[keyof LabelsUpdateFertilizerLabelDataResponses];

export type LabelsCreateFertilizerLabelDataData = {
    body: FertilizerLabelDataCreate;
    path: {
        /**
         * Label Id
         */
        label_id: string;
    };
    query?: never;
    url: '/api/v1/labels/{label_id}/fertilizer-data';
};

export type LabelsCreateFertilizerLabelDataErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type LabelsCreateFertilizerLabelDataError = LabelsCreateFertilizerLabelDataErrors[keyof LabelsCreateFertilizerLabelDataErrors];

export type LabelsCreateFertilizerLabelDataResponses = {
    /**
     * Successful Response
     */
    201: FertilizerLabelData;
};

export type LabelsCreateFertilizerLabelDataResponse = LabelsCreateFertilizerLabelDataResponses[keyof LabelsCreateFertilizerLabelDataResponses];

export type LabelsReadFertilizerLabelDataMetaData = {
    body?: never;
    path: {
        /**
         * Label Id
         */
        label_id: string;
    };
    query?: {
        /**
         * Field Name
         *
         * Filter by field name
         */
        field_name?: string | null;
        /**
         * Needs Review
         *
         * Filter by needs_review flag
         */
        needs_review?: boolean | null;
    };
    url: '/api/v1/labels/{label_id}/fertilizer-data/meta';
};

export type LabelsReadFertilizerLabelDataMetaErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type LabelsReadFertilizerLabelDataMetaError = LabelsReadFertilizerLabelDataMetaErrors[keyof LabelsReadFertilizerLabelDataMetaErrors];

export type LabelsReadFertilizerLabelDataMetaResponses = {
    /**
     * Response Labels Read Fertilizer Label Data Meta
     *
     * Successful Response
     */
    200: Array<FertilizerLabelDataMetaResponse>;
};

export type LabelsReadFertilizerLabelDataMetaResponse = LabelsReadFertilizerLabelDataMetaResponses[keyof LabelsReadFertilizerLabelDataMetaResponses];

export type LabelsUpdateFertilizerLabelDataMetaData = {
    body: FertilizerLabelDataMetaUpdate;
    path: {
        /**
         * Label Id
         */
        label_id: string;
    };
    query?: never;
    url: '/api/v1/labels/{label_id}/fertilizer-data/meta';
};

export type LabelsUpdateFertilizerLabelDataMetaErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type LabelsUpdateFertilizerLabelDataMetaError = LabelsUpdateFertilizerLabelDataMetaErrors[keyof LabelsUpdateFertilizerLabelDataMetaErrors];

export type LabelsUpdateFertilizerLabelDataMetaResponses = {
    /**
     * Successful Response
     */
    200: FertilizerLabelDataMetaResponse;
};

export type LabelsUpdateFertilizerLabelDataMetaResponse = LabelsUpdateFertilizerLabelDataMetaResponses[keyof LabelsUpdateFertilizerLabelDataMetaResponses];

export type LabelsExtractFertilizerFieldsData = {
    /**
     * Request
     */
    body?: ExtractFieldsRequest | null;
    path: {
        /**
         * Label Id
         */
        label_id: string;
    };
    query?: never;
    url: '/api/v1/labels/{label_id}/fertilizer-extract';
};

export type LabelsExtractFertilizerFieldsErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type LabelsExtractFertilizerFieldsError = LabelsExtractFertilizerFieldsErrors[keyof LabelsExtractFertilizerFieldsErrors];

export type LabelsExtractFertilizerFieldsResponses = {
    /**
     * Successful Response
     */
    200: ExtractFertilizerFieldsOutput;
};

export type LabelsExtractFertilizerFieldsResponse = LabelsExtractFertilizerFieldsResponses[keyof LabelsExtractFertilizerFieldsResponses];

export type ProductsReadProductsData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Product Type
         *
         * Product type
         */
        product_type?: string;
        /**
         * Limit
         *
         * Page size limit
         */
        limit?: number;
        /**
         * Offset
         *
         * Page offset
         */
        offset?: number;
    };
    url: '/api/v1/products';
};

export type ProductsReadProductsErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ProductsReadProductsError = ProductsReadProductsErrors[keyof ProductsReadProductsErrors];

export type ProductsReadProductsResponses = {
    /**
     * Successful Response
     */
    200: LimitOffsetPageProductPublic;
};

export type ProductsReadProductsResponse = ProductsReadProductsResponses[keyof ProductsReadProductsResponses];

export type PrivateCreateUserNoVerificationData = {
    body: PrivateUserCreate;
    path?: never;
    query?: never;
    url: '/api/v1/private/users/';
};

export type PrivateCreateUserNoVerificationErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type PrivateCreateUserNoVerificationError = PrivateCreateUserNoVerificationErrors[keyof PrivateCreateUserNoVerificationErrors];

export type PrivateCreateUserNoVerificationResponses = {
    /**
     * Successful Response
     */
    200: UserPublic;
};

export type PrivateCreateUserNoVerificationResponse = PrivateCreateUserNoVerificationResponses[keyof PrivateCreateUserNoVerificationResponses];
