"""initial migration

Revision ID: 8454daf83241
Revises:
Create Date: 2026-03-02 20:50:43.431974

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '8454daf83241'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('legislation',
    sa.Column('guidance_en', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('guidance_fr', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('title_en', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('title_fr', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('description_en', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('description_fr', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('citation_reference', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('legislation_type', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('source_url_en', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.Column('source_url_fr', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True),
    sa.Column('last_amended_date', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_legislation'))
    )
    op.create_index(op.f('ix_legislation_citation_reference'), 'legislation', ['citation_reference'], unique=True)
    op.create_table('producttype',
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('code', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('name_en', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('name_fr', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_producttype'))
    )
    op.create_index(op.f('ix_producttype_code'), 'producttype', ['code'], unique=True)
    op.create_index(op.f('ix_producttype_is_active'), 'producttype', ['is_active'], unique=False)
    op.create_table('user',
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('first_name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('last_name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_superuser', sa.Boolean(), nullable=False),
    sa.Column('hashed_password', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('external_id', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user'))
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_index(op.f('ix_user_external_id'), 'user', ['external_id'], unique=True)
    op.create_table('definition',
    sa.Column('guidance_en', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('guidance_fr', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('description_en', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('description_fr', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('legislation_id', sa.Uuid(), nullable=False),
    sa.Column('title_en', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('title_fr', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('text_en', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('text_fr', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['legislation_id'], ['legislation.id'], name=op.f('fk_definition_legislation_id_legislation')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_definition'))
    )
    op.create_index(op.f('ix_definition_legislation_id'), 'definition', ['legislation_id'], unique=False)
    op.create_table('product',
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_by_id', sa.Uuid(), nullable=False),
    sa.Column('product_type_id', sa.Uuid(), nullable=False),
    sa.Column('brand_name_en', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('brand_name_fr', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('registration_number', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('name_en', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('name_fr', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['user.id'], name=op.f('fk_product_created_by_id_user')),
    sa.ForeignKeyConstraint(['product_type_id'], ['producttype.id'], name=op.f('fk_product_product_type_id_producttype')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_product'))
    )
    op.create_index(op.f('ix_product_created_by_id'), 'product', ['created_by_id'], unique=False)
    op.create_index(op.f('ix_product_product_type_id'), 'product', ['product_type_id'], unique=False)
    op.create_index(op.f('ix_product_registration_number'), 'product', ['registration_number'], unique=True)
    op.create_table('provision',
    sa.Column('guidance_en', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('guidance_fr', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('title_en', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('title_fr', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('description_en', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('description_fr', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('legislation_id', sa.Uuid(), nullable=False),
    sa.Column('citation', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('text_en', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('text_fr', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('is_global_rule', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['legislation_id'], ['legislation.id'], name=op.f('fk_provision_legislation_id_legislation')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_provision'))
    )
    op.create_index(op.f('ix_provision_citation'), 'provision', ['citation'], unique=True)
    op.create_index(op.f('ix_provision_legislation_id'), 'provision', ['legislation_id'], unique=False)
    op.create_table('requirement',
    sa.Column('guidance_en', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('guidance_fr', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('title_en', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('title_fr', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('description_en', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('description_fr', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('legislation_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['legislation_id'], ['legislation.id'], name=op.f('fk_requirement_legislation_id_legislation')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_requirement'))
    )
    op.create_index(op.f('ix_requirement_legislation_id'), 'requirement', ['legislation_id'], unique=False)
    op.create_table('label',
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('product_id', sa.Uuid(), nullable=True),
    sa.Column('product_type_id', sa.Uuid(), nullable=False),
    sa.Column('created_by_id', sa.Uuid(), nullable=False),
    sa.Column('review_status', sa.Enum('not_started', 'in_progress', 'completed', name='reviewstatus', native_enum=False), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['user.id'], name=op.f('fk_label_created_by_id_user')),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], name=op.f('fk_label_product_id_product')),
    sa.ForeignKeyConstraint(['product_type_id'], ['producttype.id'], name=op.f('fk_label_product_type_id_producttype')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_label'))
    )
    op.create_index(op.f('ix_label_created_by_id'), 'label', ['created_by_id'], unique=False)
    op.create_index(op.f('ix_label_product_id'), 'label', ['product_id'], unique=False)
    op.create_index(op.f('ix_label_product_type_id'), 'label', ['product_type_id'], unique=False)
    op.create_index(op.f('ix_label_review_status'), 'label', ['review_status'], unique=False)
    op.create_table('provisiondefinition',
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('provision_id', sa.Uuid(), nullable=False),
    sa.Column('definition_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['definition_id'], ['definition.id'], name=op.f('fk_provisiondefinition_definition_id_definition')),
    sa.ForeignKeyConstraint(['provision_id'], ['provision.id'], name=op.f('fk_provisiondefinition_provision_id_provision')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_provisiondefinition'))
    )
    op.create_index(op.f('ix_provisiondefinition_definition_id'), 'provisiondefinition', ['definition_id'], unique=False)
    op.create_index(op.f('ix_provisiondefinition_provision_id'), 'provisiondefinition', ['provision_id'], unique=False)
    op.create_table('requirementmodifier',
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('requirement_id', sa.Uuid(), nullable=False),
    sa.Column('provision_id', sa.Uuid(), nullable=False),
    sa.Column('type', sa.Enum('EXEMPTION', 'APPLICABILITY_CONDITION', name='modifiertype', native_enum=False), nullable=False),
    sa.ForeignKeyConstraint(['provision_id'], ['provision.id'], name=op.f('fk_requirementmodifier_provision_id_provision')),
    sa.ForeignKeyConstraint(['requirement_id'], ['requirement.id'], name=op.f('fk_requirementmodifier_requirement_id_requirement')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_requirementmodifier'))
    )
    op.create_index(op.f('ix_requirementmodifier_provision_id'), 'requirementmodifier', ['provision_id'], unique=False)
    op.create_index(op.f('ix_requirementmodifier_requirement_id'), 'requirementmodifier', ['requirement_id'], unique=False)
    op.create_index(op.f('ix_requirementmodifier_type'), 'requirementmodifier', ['type'], unique=False)
    op.create_table('requirementprovision',
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('requirement_id', sa.Uuid(), nullable=False),
    sa.Column('provision_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['provision_id'], ['provision.id'], name=op.f('fk_requirementprovision_provision_id_provision')),
    sa.ForeignKeyConstraint(['requirement_id'], ['requirement.id'], name=op.f('fk_requirementprovision_requirement_id_requirement')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_requirementprovision'))
    )
    op.create_index(op.f('ix_requirementprovision_provision_id'), 'requirementprovision', ['provision_id'], unique=False)
    op.create_index(op.f('ix_requirementprovision_requirement_id'), 'requirementprovision', ['requirement_id'], unique=False)
    op.create_table('fertilizerlabeldata',
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('label_id', sa.Uuid(), nullable=False),
    sa.Column('n', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('p', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('k', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('ingredients', sa.JSON(), nullable=True),
    sa.Column('guaranteed_analysis', sa.JSON(), nullable=True),
    sa.Column('caution_en', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('caution_fr', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('instructions_en', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('instructions_fr', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['label_id'], ['label.id'], name=op.f('fk_fertilizerlabeldata_label_id_label')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_fertilizerlabeldata'))
    )
    op.create_index(op.f('ix_fertilizerlabeldata_label_id'), 'fertilizerlabeldata', ['label_id'], unique=True)
    op.create_table('labeldata',
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('label_id', sa.Uuid(), nullable=False),
    sa.Column('brand_name_en', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('brand_name_fr', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('product_name_en', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('product_name_fr', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('contacts', sa.JSON(), nullable=True),
    sa.Column('registration_number', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('lot_number', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('net_weight', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('volume', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.ForeignKeyConstraint(['label_id'], ['label.id'], name=op.f('fk_labeldata_label_id_label')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_labeldata'))
    )
    op.create_index(op.f('ix_labeldata_label_id'), 'labeldata', ['label_id'], unique=True)
    op.create_table('labelimage',
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('label_id', sa.Uuid(), nullable=False),
    sa.Column('file_path', sqlmodel.sql.sqltypes.AutoString(length=512), nullable=False),
    sa.Column('display_filename', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('sequence_order', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'completed', name='uploadstatus', native_enum=False), nullable=False),
    sa.CheckConstraint('sequence_order >= 1', name=op.f('ck_labelimage_ck_labelimage_sequence_order_positive')),
    sa.ForeignKeyConstraint(['label_id'], ['label.id'], name=op.f('fk_labelimage_label_id_label')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_labelimage')),
    sa.UniqueConstraint('label_id', 'sequence_order', name='uq_labelimage_label_id_sequence_order')
    )
    op.create_index(op.f('ix_labelimage_label_id'), 'labelimage', ['label_id'], unique=False)
    op.create_index(op.f('ix_labelimage_sequence_order'), 'labelimage', ['sequence_order'], unique=False)
    op.create_index(op.f('ix_labelimage_status'), 'labelimage', ['status'], unique=False)
    op.create_table('noncompliancedataitem',
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('requirement_id', sa.Uuid(), nullable=False),
    sa.Column('label_id', sa.Uuid(), nullable=False),
    sa.Column('note', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('description_en', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('description_fr', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('status', sa.Enum('COMPLIANT', 'NON_COMPLIANT', 'NOT_APPLICABLE', 'INCONCLUSIVE', name='compliancestatus', native_enum=False), nullable=False),
    sa.ForeignKeyConstraint(['label_id'], ['label.id'], name=op.f('fk_noncompliancedataitem_label_id_label')),
    sa.ForeignKeyConstraint(['requirement_id'], ['requirement.id'], name=op.f('fk_noncompliancedataitem_requirement_id_requirement')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_noncompliancedataitem')),
    sa.UniqueConstraint('label_id', 'requirement_id', name='uq_noncompliancedataitem_label_id_requirement_id')
    )
    op.create_table('fertilizerlabeldatameta',
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('label_id', sa.Uuid(), nullable=False),
    sa.Column('field_name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('needs_review', sa.Boolean(), nullable=False),
    sa.Column('note', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('ai_generated', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['label_id'], ['fertilizerlabeldata.id'], name=op.f('fk_fertilizerlabeldatameta_label_id_fertilizerlabeldata')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_fertilizerlabeldatameta')),
    sa.UniqueConstraint('label_id', 'field_name', name='uq_fertilizerlabeldatameta_label_id_field_name')
    )
    op.create_index(op.f('ix_fertilizerlabeldatameta_field_name'), 'fertilizerlabeldatameta', ['field_name'], unique=False)
    op.create_index(op.f('ix_fertilizerlabeldatameta_label_id'), 'fertilizerlabeldatameta', ['label_id'], unique=False)
    op.create_table('labeldatafieldmeta',
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('label_id', sa.Uuid(), nullable=False),
    sa.Column('field_name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('needs_review', sa.Boolean(), nullable=False),
    sa.Column('note', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('ai_generated', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['label_id'], ['labeldata.id'], name=op.f('fk_labeldatafieldmeta_label_id_labeldata')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_labeldatafieldmeta')),
    sa.UniqueConstraint('label_id', 'field_name', name='uq_labeldatafieldmeta_label_id_field_name')
    )
    op.create_index(op.f('ix_labeldatafieldmeta_field_name'), 'labeldatafieldmeta', ['field_name'], unique=False)
    op.create_index(op.f('ix_labeldatafieldmeta_label_id'), 'labeldatafieldmeta', ['label_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_labeldatafieldmeta_label_id'), table_name='labeldatafieldmeta')
    op.drop_index(op.f('ix_labeldatafieldmeta_field_name'), table_name='labeldatafieldmeta')
    op.drop_table('labeldatafieldmeta')
    op.drop_index(op.f('ix_fertilizerlabeldatameta_label_id'), table_name='fertilizerlabeldatameta')
    op.drop_index(op.f('ix_fertilizerlabeldatameta_field_name'), table_name='fertilizerlabeldatameta')
    op.drop_table('fertilizerlabeldatameta')
    op.drop_table('noncompliancedataitem')
    op.drop_index(op.f('ix_labelimage_status'), table_name='labelimage')
    op.drop_index(op.f('ix_labelimage_sequence_order'), table_name='labelimage')
    op.drop_index(op.f('ix_labelimage_label_id'), table_name='labelimage')
    op.drop_table('labelimage')
    op.drop_index(op.f('ix_labeldata_label_id'), table_name='labeldata')
    op.drop_table('labeldata')
    op.drop_index(op.f('ix_fertilizerlabeldata_label_id'), table_name='fertilizerlabeldata')
    op.drop_table('fertilizerlabeldata')
    op.drop_index(op.f('ix_requirementprovision_requirement_id'), table_name='requirementprovision')
    op.drop_index(op.f('ix_requirementprovision_provision_id'), table_name='requirementprovision')
    op.drop_table('requirementprovision')
    op.drop_index(op.f('ix_requirementmodifier_type'), table_name='requirementmodifier')
    op.drop_index(op.f('ix_requirementmodifier_requirement_id'), table_name='requirementmodifier')
    op.drop_index(op.f('ix_requirementmodifier_provision_id'), table_name='requirementmodifier')
    op.drop_table('requirementmodifier')
    op.drop_index(op.f('ix_provisiondefinition_provision_id'), table_name='provisiondefinition')
    op.drop_index(op.f('ix_provisiondefinition_definition_id'), table_name='provisiondefinition')
    op.drop_table('provisiondefinition')
    op.drop_index(op.f('ix_label_review_status'), table_name='label')
    op.drop_index(op.f('ix_label_product_type_id'), table_name='label')
    op.drop_index(op.f('ix_label_product_id'), table_name='label')
    op.drop_index(op.f('ix_label_created_by_id'), table_name='label')
    op.drop_table('label')
    op.drop_index(op.f('ix_requirement_legislation_id'), table_name='requirement')
    op.drop_table('requirement')
    op.drop_index(op.f('ix_provision_legislation_id'), table_name='provision')
    op.drop_index(op.f('ix_provision_citation'), table_name='provision')
    op.drop_table('provision')
    op.drop_index(op.f('ix_product_registration_number'), table_name='product')
    op.drop_index(op.f('ix_product_product_type_id'), table_name='product')
    op.drop_index(op.f('ix_product_created_by_id'), table_name='product')
    op.drop_table('product')
    op.drop_index(op.f('ix_definition_legislation_id'), table_name='definition')
    op.drop_table('definition')
    op.drop_index(op.f('ix_user_external_id'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    op.drop_index(op.f('ix_producttype_is_active'), table_name='producttype')
    op.drop_index(op.f('ix_producttype_code'), table_name='producttype')
    op.drop_table('producttype')
    op.drop_index(op.f('ix_legislation_citation_reference'), table_name='legislation')
    op.drop_table('legislation')
    # ### end Alembic commands ###
