// This file is automatically generated by i18next-cli. Do not edit manually.
interface Resources {
  "auth": {
    "login": {
      "email": "Email",
      "emailHelper": "Enter your email address",
      "emailInvalid": "Invalid email address",
      "forgotPassword": "Forgot Password?",
      "noAccount": "Don't have an account?",
      "password": "Password",
      "passwordHelper": "Enter your password",
      "signUp": "Sign Up",
      "submit": "Log In",
      "submitting": "Logging in...",
      "title": "Login",
      "usernameRequired": "Username is required"
    },
    "recoverPassword": {
      "description": "A password recovery email will be sent to the registered account.",
      "email": "Email",
      "emailHelper": "Enter your email address to receive a password reset link",
      "emailInvalid": "Invalid email address",
      "emailRequired": "Email is required",
      "submit": "Continue",
      "submitting": "Sending...",
      "success": "Password recovery email sent successfully.",
      "title": "Password Recovery"
    },
    "resetPassword": {
      "confirmPassword": "Confirm Password",
      "confirmPasswordHelper": "Re-enter your new password to confirm",
      "description": "Please enter your new password and confirm it to reset your password.",
      "newPassword": "New Password",
      "newPasswordHelper": "Enter your new password",
      "submit": "Reset Password",
      "success": "Password updated successfully.",
      "title": "Reset Password"
    },
    "signup": {
      "confirmPassword": "Confirm Password",
      "confirmPasswordHelper": "Re-enter your password to confirm",
      "confirmPasswordRequired": "Password confirmation is required",
      "email": "Email",
      "emailHelper": "Enter your email address",
      "emailInvalid": "Invalid email address",
      "emailRequired": "Email is required",
      "firstName": "First Name",
      "firstNameHelper": "Enter your first name",
      "firstNameRequired": "First Name is required",
      "hasAccount": "Already have an account?",
      "lastName": "Last Name",
      "lastNameHelper": "Enter your last name",
      "lastNameRequired": "Last Name is required",
      "logIn": "Log In",
      "password": "Password",
      "passwordHelper": "Enter a secure password",
      "passwordMinLength": "Password must be at least 8 characters",
      "passwordRequired": "Password is required",
      "passwordsDoNotMatch": "The passwords do not match",
      "submit": "Sign Up",
      "submitting": "Signing up...",
      "title": "Sign Up"
    },
    "userMenu": {
      "logOut": "Log Out",
      "myProfile": "My Profile"
    }
  },
  "common": {
    "admin": {
      "addUser": "Add User",
      "addUserDialog": {
        "confirmPassword": "Confirm Password",
        "confirmPasswordHelper": "Re-enter the password to confirm",
        "confirmPasswordRequired": "Password confirmation is required",
        "emailHelper": "Must be unique. Used for login. Max 255 characters.",
        "emailInvalid": "Invalid email address",
        "emailMaxLength": "Email must be 255 characters or less",
        "emailRequired": "Email is required",
        "error": "Failed to create user. Please try again.",
        "password": "Password",
        "passwordHelper": "Set the initial password for this user",
        "passwordMinLength": "Password must be at least 8 characters",
        "passwordRequired": "Password is required",
        "passwordsDoNotMatch": "The passwords do not match",
        "submit": "Add User",
        "success": "User created successfully",
        "title": "Add user"
      },
      "deleteSelected": "Delete selected",
      "pageTitle": "Admin - Label Inspection",
      "rowActions": {
        "delete": "Delete",
        "deleteDialog": {
          "description": "Are you sure you want to delete this user? This action cannot be undone.",
          "title": "Delete user"
        },
        "deleteError": "Failed to delete user. Please try again.",
        "deleteSuccess": "User deleted successfully",
        "edit": "Edit",
        "editDialog": {
          "active": "Active",
          "emailHelper": "Must be unique. Used for login. Max 255 characters.",
          "emailInvalid": "Invalid email address",
          "emailMaxLength": "Email must be 255 characters or less",
          "emailRequired": "Email is required",
          "error": "Failed to update user. Please try again.",
          "firstName": "First name",
          "firstNameHelper": "Max 255 characters",
          "firstNameMaxLength": "First name must be 255 characters or less",
          "lastName": "Last name",
          "lastNameHelper": "Max 255 characters",
          "lastNameMaxLength": "Last name must be 255 characters or less",
          "success": "User updated successfully",
          "superuser": "Superuser",
          "title": "Edit user"
        }
      },
      "table": {
        "actions": "Actions",
        "active": "Active",
        "copyId": "Copy user ID {{id}}",
        "email": "Email",
        "fullName": "Full name",
        "id": "ID",
        "idCopied": "User ID copied to clipboard",
        "inactive": "Inactive",
        "role": "Role",
        "status": "Status",
        "superuser": "Superuser",
        "user": "User",
        "you": "You"
      },
      "user": "User",
      "usersManagement": "Users Management"
    },
    "app": {
      "title": "Label Inspection"
    },
    "aria": {
      "navigation": "navigation",
      "openDrawer": "open drawer",
      "togglePasswordVisibility": "Toggle password visibility"
    },
    "backend": {
      "unavailable": "Backend unavailable. Some features may not work. Please try again later."
    },
    "button": {
      "cancel": "Cancel",
      "clearAll": "Clear All",
      "dismiss": "Dismiss",
      "goBack": "Go Back",
      "label": "Label",
      "retry": "Retry",
      "save": "Save",
      "upload": "Upload Files",
      "uploading": "Uploading...",
      "viewAll": "View All"
    },
    "data": {
      "validation": {
        "registrationNumberInvalidFormat": "data.validation.registrationNumberInvalidFormat"
      }
    },
    "labels": {
      "errorOccurred": "An error occurred",
      "loadFailed": "Failed to load labels",
      "loadFailedRetry": "Failed to load labels. Please try again."
    },
    "language": {
      "en": {
        "ariaLabel": "Switch to English"
      },
      "fr": {
        "ariaLabel": "Switch to French"
      },
      "switcher": {
        "ariaLabel": "Language switcher"
      }
    },
    "notFound": {
      "message": "The page you are looking for was not found.",
      "title": "Oops!"
    },
    "products": {
      "create": {
        "form": {
          "brandNameEn": {
            "helperText": "The brand name in English (optional)",
            "label": "Brand Name (EN)",
            "maxLength": "Brand name (EN) must be 100 characters or less"
          },
          "brandNameFr": {
            "helperText": "The brand name in French (optional)",
            "label": "Brand Name (FR)",
            "maxLength": "Brand name (FR) must be 100 characters or less"
          },
          "cancel": "Cancel",
          "cancelDialog": {
            "discard": "Discard Changes",
            "keepEditing": "Keep Editing",
            "message": "You have unsaved changes. Are you sure you want to leave this page?",
            "title": "Discard Changes?"
          },
          "error": "Failed to create product. Please try again.",
          "nameEn": {
            "helperText": "The product name in English (optional)",
            "label": "Product Name (EN)",
            "maxLength": "Product name (EN) must be 200 characters or less"
          },
          "nameFr": {
            "helperText": "The product name in French (optional)",
            "label": "Product Name (FR)",
            "maxLength": "Product name (FR) must be 200 characters or less"
          },
          "registrationNumber": {
            "checking": "Checking...",
            "duplicate": "A product with this registration number already exists.",
            "helperText": "The official registration number assigned to this product",
            "invalidFormat": "7 digits followed by a letter (e.g. 1234567F)",
            "label": "Registration Number",
            "maxLength": "Registration number must be 8 characters (7 digits + 1 letter)",
            "required": "Registration number is required"
          },
          "submit": "Create Product",
          "success": "Product created successfully"
        },
        "pageTitle": "Create New Product",
        "title": "Create New Product"
      },
      "createNew": "Product"
    },
    "settings": {
      "dangerZone": {
        "deleteAccount": "Delete account",
        "deleteAccountButton": "Delete account",
        "deleteAccountDescription": "Remove your account and data.",
        "deleteAccountDialogDescription": "Your account will be removed and you will be logged out.",
        "deleteAccountDialogTitle": "Delete your account?",
        "deleteAccountSuccess": "Your account has been deleted."
      },
      "pageTitle": "Settings - Label Inspection",
      "password": {
        "confirmNewPassword": "Confirm new password",
        "confirmNewPasswordRequired": "Confirm new password is required",
        "confirmPasswordHelper": "Re-enter the new password to confirm",
        "currentPassword": "Current password",
        "currentPasswordRequired": "Current password is required",
        "error": "Failed to update password. Please try again.",
        "incorrectPassword": "Incorrect password",
        "newPassword": "New password",
        "newPasswordRequired": "New password is required",
        "passwordHelper": "8–40 characters",
        "passwordMinLength": "Password must be at least 8 characters",
        "passwordsDoNotMatch": "The passwords do not match",
        "submit": "Update password",
        "success": "Password updated successfully",
        "userHasNoPassword": "User has no password"
      },
      "profile": {
        "edit": "Edit",
        "email": "Email",
        "status": "Status"
      },
      "sections": {
        "appearance": "Appearance"
      },
      "tabs": {
        "appearance": "Appearance",
        "dangerZone": "Danger zone",
        "myProfile": "My profile",
        "password": "Password"
      },
      "title": "User Settings"
    },
    "sidebar": {
      "admin": "Admin",
      "dashboard": "Dashboard",
      "labels": "Labels",
      "logOut": "Log Out",
      "loggedInAs": "Logged in as: {{email}}",
      "products": "Products",
      "userSettings": "User Settings"
    }
  },
  "errors": {
    "fileType": {
      "invalidTitle": "Invalid file types:"
    },
    "labels": {
      "errorOccurred": "An error occurred",
      "loadFailed": "Failed to load labels",
      "loadFailedRetry": "Failed to load labels. Please try again."
    }
  },
  "labels": {
    "common": {
      "aria": {
        "clearSelection": "Clear selection"
      },
      "button": {
        "cancel": "Cancel"
      },
      "loading": "Loading linked product...",
      "noBrand": "No Brand",
      "processing": "Processing...",
      "unnamedProduct": "Unnamed Product"
    },
    "dashboard": {
      "completed": "Completed",
      "createNewLabel": "Create New Label",
      "createNewLabelDescription": "Upload and process a new label",
      "inProgress": "In Progress",
      "manageProducts": "Manage Products",
      "manageProductsDescription": "View and edit products",
      "notStarted": "Not Started",
      "overview": "Overview",
      "quickActions": "Quick Actions",
      "title": "Dashboard - Label Inspection",
      "totalLabels": "Total Labels",
      "totalProducts": "Total Products",
      "unlinkedLabels": "Unlinked Labels",
      "unlinkedLabelsDescription": "Labels not associated with products",
      "viewAllLabels": "View All Labels",
      "viewAllLabelsDescription": "Browse and manage all labels"
    },
    "data": {
      "compliance": "Compliance",
      "complianceApplicabilityCondition": "Applicability condition",
      "complianceClear": "Clear",
      "complianceCleared": "Compliance result cleared",
      "complianceEvaluationPlaceholder": "Requirement list and evaluation will appear here.",
      "complianceExemptions": "Exemptions",
      "complianceExplanationLabel": "Explanation",
      "complianceExplanationPlaceholder": "Enter explanation",
      "complianceGlobalExemptions": "General exemptions",
      "complianceNoUnsavedChanges": "No unsaved changes",
      "compliancePageTitle": "Compliance - Label Inspection",
      "compliancePrerequisiteNotMet": "Prerequisite not met: complete label data extraction first",
      "complianceRequirement": "Requirement",
      "complianceRunAll": "Run evaluation",
      "complianceRunLegislation": "Evaluate all",
      "complianceRunRequirement": "Evaluate",
      "complianceStatusCompliant": "Compliant",
      "complianceStatusInconclusive": "Inconclusive",
      "complianceStatusLabel": "Status",
      "complianceStatusNonCompliant": "Non-compliant",
      "complianceStatusNotApplicable": "Not applicable",
      "complianceStatusPlaceholder": "Select status",
      "complianceTitle": "Compliance",
      "complianceUnsavedWarning": "You have unsaved compliance results. Are you sure you want to leave?",
      "contacts": {
        "addContact": "Add Contact",
        "address": "Address",
        "contactNumber": "Contact {{number}}",
        "email": "Email",
        "name": "Name",
        "noContacts": "No contacts added",
        "phone": "Phone",
        "type": "Type",
        "types": {
          "distributor": "Distributor",
          "importer": "Importer",
          "manufacturer": "Manufacturer",
          "notSpecified": "Not specified"
        },
        "website": "Website"
      },
      "continueReview": "Continue Review",
      "editUnsavedWarning": "You have unsaved label data. Are you sure you want to leave?",
      "extractAllBasic": "Extract All Basic Fields",
      "extractAllFields": "Extract All Fields",
      "extractAllGuaranteed": "Extract All Guaranteed Analysis",
      "extractAllIngredients": "Extract All Ingredients",
      "extractAllNPK": "Extract All NPK Fields",
      "extractAllStatements": "Extract All Statements",
      "extractField": "Extract with AI",
      "extractionAllSuccess": "All fields extracted successfully",
      "extractionComplete": "Extraction complete",
      "extractionFailed": "Extraction failed. Please try again.",
      "extractionNoImages": "No images available for extraction",
      "extractionNoValue": "No value was extracted for this field",
      "extractionOnlyFertilizer": "Extraction is only available for fertilizer labels",
      "extractionPartialSuccess": "Extracted {{success}} of {{total}} sections",
      "extractionSuccess": "Field extracted successfully",
      "fields": {
        "brandNameEn": "Brand Name (English)",
        "brandNameFr": "Brand Name (French)",
        "contacts": "Contacts",
        "countryOfOrigin": "Country of origin",
        "exemptionClaimEn": "Exemption claim (EN)",
        "exemptionClaimFr": "Exemption claim (FR)",
        "guaranteedAnalysis": "Guaranteed Analysis",
        "ingredients": "Ingredient List",
        "k": "Potassium (K)",
        "lotNumber": "Lot Number",
        "n": "Nitrogen (N)",
        "netWeight": "Net Weight",
        "p": "Phosphorus (P)",
        "productClassification": {
          "fertilizer": "Fertilizer",
          "growing_medium": "Growing medium",
          "supplement": "Supplement",
          "treated_seed": "Treated seed"
        },
        "productClassificationLabel": "Product classification",
        "productClassificationNone": "None",
        "productNameEn": "Product Name (English)",
        "productNameFr": "Product Name (French)",
        "registrationClaimEn": "Registration claim (EN)",
        "registrationClaimFr": "Registration claim (FR)",
        "registrationNumber": "Registration Number",
        "volume": "Volume"
      },
      "flagForReview": "Flag for review",
      "guaranteedAnalysis": {
        "addNutrient": "Add Nutrient",
        "isMinimum": "Is Minimum",
        "nameEn": "Name (English)",
        "nameFr": "Name (French)",
        "noNutrients": "No nutrients added",
        "titleEn": "Title (English)",
        "titleFr": "Title (French)",
        "unit": "Unit",
        "value": "Value"
      },
      "helperText": {
        "brandNameEn": "Enter the brand name as it appears on the label",
        "brandNameFr": "Enter the brand name as it appears on the label",
        "contacts": "Enter contact information for manufacturer, distributor, or importer",
        "countryOfOrigin": "Country where manufactured or imported from",
        "exemptionClaim": "Verbatim exemption claim",
        "guaranteedAnalysis": "Enter guaranteed analysis with title, nutrients, values and units",
        "ingredients": "Enter ingredients with bilingual names, values and units",
        "k": "Enter potassium percentage",
        "lotNumber": "Enter the lot or batch number",
        "n": "Enter nitrogen percentage",
        "netWeight": "Enter net weight with unit (e.g., 5 kg, 10 lbs)",
        "p": "Enter phosphorus percentage",
        "productNameEn": "Enter the product name as it appears on the label",
        "productNameFr": "Enter the product name as it appears on the label",
        "registrationClaim": "Verbatim registration claim text",
        "registrationNumber": "Enter the product registration number",
        "volume": "Enter volume with unit (e.g., 1 L, 500 ml)"
      },
      "ingredients": {
        "addIngredient": "Add Ingredient",
        "nameEn": "Name (English)",
        "nameFr": "Name (French)",
        "noIngredients": "No ingredients added",
        "registrationNumber": "Registration number",
        "unit": "Unit",
        "value": "Value"
      },
      "markComplete": "Mark Complete",
      "pageTitle": "Edit Label - Label Inspection",
      "removeReviewFlag": "Remove review flag",
      "save": "Save",
      "saved": "Changes saved successfully",
      "sections": {
        "association": {
          "associate": "Associate",
          "createAndAssociate": "Create & Associate",
          "createAndLinkSuccess": "Product created and associated successfully",
          "createSuccess": "Product created successfully",
          "creationDraft": "Create New Product Entry",
          "creationHelp": "We can create a new product entry using the data extracted from this label.",
          "linkSuccess": "Product associated successfully",
          "linked": "Product associated",
          "linkedMessage": "This label is linked to a product entry.",
          "linkedProduct": "Linked Product",
          "matchesFound_one": "{{count}} potential matches found",
          "matchesFound_other": "{{count}} potential matches found",
          "missingCriteria": "At least one product attribute required for search",
          "noMatch": "No matching product found",
          "title": "Product Association",
          "unlink": "Unlink Product",
          "unlinkSuccess": "Product unlinked successfully"
        },
        "basic": "Basic Information",
        "brand": "Brand",
        "guaranteed": "Guaranteed Analysis",
        "ingredients": "Ingredients",
        "npk": "NPK Analysis",
        "product": "Product",
        "registrationNumber": "Registration Number",
        "safety": "Safety Information",
        "statements": "Statements and Claims"
      },
      "statements": {
        "add": "Add",
        "customer_formula_statements": "Customer formula statements",
        "directions_for_use_statements": "Directions for use",
        "empty": {
          "customer_formula_statements": "No customer formula statements",
          "directions_for_use_statements": "No directions for use",
          "experimental_statements": "No experimental statements",
          "export_statements": "No export statements",
          "intended_use_statements": "No intended use statements",
          "precaution_statements": "No precaution statements",
          "processing_instruction_statements": "No processing instructions"
        },
        "en": "English",
        "experimental_statements": "Experimental statements",
        "export_statements": "Export statements",
        "fr": "French",
        "intended_use_statements": "Intended use statements",
        "precaution_statements": "Precaution statements",
        "processing_instruction_statements": "Processing instructions"
      },
      "title": "Edit Label",
      "validation": {
        "missingLabelData": "Label data must be created before marking review as complete",
        "missingRegistrationNumber": "Registration number is required to mark review as complete",
        "registrationNumberInvalidFormat": "Must be 7 digits followed by 1 letter (e.g. 1234567F) or empty"
      }
    },
    "empty": {
      "noLabels": "No labels found",
      "noLabelsDescription": "Labels you upload will appear here.",
      "noMatches": "No labels match your current filters",
      "noMatchesDescription": "Try adjusting your filters to see more results."
    },
    "errors": {
      "fileType": {
        "invalid": "{{fileName}}: Not added - must be PNG, JPEG or WebP"
      }
    },
    "files": {
      "editLabel": "Edit Label",
      "pageTitle": "Label Files - Label Inspection",
      "title_one": "Label Image: {{count}} (max {{max}})",
      "title_other": "Label Images: {{count}} (max {{max}})"
    },
    "filter": {
      "completed": "Completed",
      "inProgress": "In Progress",
      "notStarted": "Not Started",
      "reviewStatus": "Review Status",
      "title": "Filter list",
      "unlinked": "Unlinked"
    },
    "image": {
      "delete": "Delete",
      "deleteDialog": {
        "description": "Are you sure you want to delete \"{{filename}}\"? This action cannot be undone and will permanently delete the image file.",
        "title": "Delete image"
      },
      "deleteError": "Failed to delete image. Please try again.",
      "deleteSuccess": "Image deleted successfully",
      "notAvailable": "Image not available",
      "sequence": "Sequence: {{order}}",
      "slideAlt": "Slide {{number}}"
    },
    "labels": {
      "bulkActions": {
        "delete": "Delete",
        "deleteDialog": {
          "description_one": "Are you sure you want to delete {{count}} selected label? This action cannot be undone and will permanently delete the label and all associated files.",
          "description_other": "Are you sure you want to delete {{count}} selected labels? This action cannot be undone and will permanently delete the labels and all associated files.",
          "title_one": "Delete {{count}} label?",
          "title_other": "Delete {{count}} labels?"
        },
        "deleteNotImplemented": "Bulk delete functionality not yet implemented",
        "export": "Export",
        "exportNotImplemented": "Export functionality not yet implemented",
        "selected_one": "{{count}} selected",
        "selected_other": "{{count}} selected"
      },
      "create": {
        "description": "Select at least one label image to create a new label",
        "maxFilesWarning_one": "Maximum {{max}} files allowed. Please remove {{count}} file before uploading.",
        "maxFilesWarning_other": "Maximum {{max}} files allowed. Please remove {{count}} files before uploading.",
        "of": "of",
        "pageTitle": "Create New Label - Label Inspection",
        "remove": "Remove",
        "selectFiles": "Select files or drag and drop",
        "selectedFiles": "Selected files",
        "title": "Create New Label"
      },
      "rowActions": {
        "continueEdit": "Continue editing",
        "delete": "Delete",
        "deleteDialog": {
          "description": "Are you sure you want to delete this label? This action cannot be undone and will permanently delete the label and all associated files.",
          "title": "Delete label"
        },
        "deleteNotImplemented": "Delete functionality not yet implemented",
        "editLabel": "Edit label",
        "viewDetails": "View Details"
      },
      "upload": {
        "preparing": "Preparing uploads...",
        "uploaded_one": "{{completed}} of {{total}} file uploaded",
        "uploaded_other": "{{completed}} of {{total}} files uploaded",
        "uploading_one": "Uploading {{current}} of {{total}} file...",
        "uploading_other": "Uploading {{current}} of {{total}} files..."
      }
    },
    "pageTitle": "Labels - Label Inspection",
    "table": {
      "actions": "Actions",
      "brand": "Brand",
      "copyId": "Copy label ID {{id}}",
      "createdAt": "Created At",
      "id": "ID",
      "idCopied": "Label ID copied to clipboard",
      "productName": "Product",
      "reviewStatus": "Review Status",
      "selectAll": "select all labels",
      "sortedAscending": "sorted ascending",
      "sortedDescending": "sorted descending"
    },
    "title": "Labels",
    "upload": {
      "failed_one": "Failed to upload {{failed}} of {{total}} file",
      "failed_other": "Failed to upload {{failed}} of {{total}} files",
      "partial": "Upload complete: {{completed}} succeeded, {{failed}} failed",
      "success_one": "Successfully uploaded {{completed}} of {{total}} file",
      "success_other": "Successfully uploaded {{completed}} of {{total}} files"
    }
  },
  "products": {
    "common": {
      "button": {
        "cancel": "Cancel"
      }
    },
    "detail": {
      "brandEn": "Brand (English)",
      "brandFr": "Brand (French)",
      "nameEn": "Product name (English)",
      "nameFr": "Product name (French)",
      "pageTitle": "Product details - Label Inspection",
      "title": "Product details"
    },
    "empty": {
      "noProducts": "No products found",
      "noProductsDescription": "Products created from labels will appear here."
    },
    "pageTitle": "Products - Label Inspection",
    "products": {
      "rowActions": {
        "delete": "Delete",
        "deleteDialog": {
          "description": "Are you sure you want to delete this product? This action cannot be undone and will permanently delete the product.",
          "title": "Delete product"
        },
        "deleteNotImplemented": "Delete functionality not yet implemented",
        "viewDetails": "View Details"
      }
    },
    "table": {
      "brand": "Brand",
      "copyId": "Copy product ID {{id}}",
      "createdAt": "Created At",
      "id": "ID",
      "idCopied": "Product ID copied to clipboard",
      "name": "Product Name",
      "registrationNumber": "Registration Number",
      "selectAll": "select all products",
      "sortedAscending": "sorted ascending",
      "sortedDescending": "sorted descending"
    },
    "title": "Products"
  }
}

export default Resources;
