// This file is automatically generated by i18next-cli. Do not edit manually.
interface Resources {
  auth: {
    login: {
      email: "Email"
      emailInvalid: "Invalid email address"
      failed: "Login failed"
      forgotPassword: "Forgot Password?"
      noAccount: "Don't have an account?"
      password: "Password"
      signUp: "Sign Up"
      submit: "Log In"
      submitting: "Logging in..."
      title: "Login"
      usernameRequired: "Username is required"
    }
    recoverPassword: {
      description: "A password recovery email will be sent to the registered account."
      email: "Email"
      emailInvalid: "Invalid email address"
      emailRequired: "Email is required"
      submit: "Continue"
      submitting: "Sending..."
      success: "Password recovery email sent successfully."
      title: "Password Recovery"
    }
    resetPassword: {
      confirmPassword: "Confirm Password"
      description: "Please enter your new password and confirm it to reset your password."
      newPassword: "New Password"
      submit: "Reset Password"
      success: "Password updated successfully."
      title: "Reset Password"
    }
    signup: {
      confirmPassword: "Confirm Password"
      confirmPasswordRequired: "Password confirmation is required"
      email: "Email"
      emailInvalid: "Invalid email address"
      emailRequired: "Email is required"
      firstName: "First Name"
      firstNameRequired: "First Name is required"
      hasAccount: "Already have an account?"
      lastName: "Last Name"
      lastNameRequired: "Last Name is required"
      logIn: "Log In"
      password: "Password"
      passwordMinLength: "Password must be at least 8 characters"
      passwordRequired: "Password is required"
      passwordsDoNotMatch: "The passwords do not match"
      submit: "Sign Up"
      submitting: "Signing up..."
      title: "Sign Up"
    }
    userMenu: {
      logOut: "Log Out"
      myProfile: "My Profile"
    }
  }
  common: {
    admin: {
      addUser: "Add User"
      pageTitle: "Admin - Label Inspection"
      pagination: {
        loading: "Loading..."
        page: "Page {{current}} of {{total}}"
      }
      table: {
        actions: "Actions"
        active: "Active"
        email: "Email"
        fullName: "Full name"
        inactive: "Inactive"
        notAvailable: "N/A"
        role: "Role"
        status: "Status"
        superuser: "Superuser"
        user: "User"
        you: "You"
      }
      usersManagement: "Users Management"
    }
    app: {
      title: "Label Inspection"
    }
    aria: {
      navigation: "navigation"
      openDrawer: "open drawer"
    }
    backend: {
      unavailable: "Backend unavailable. Some features may not work. Please try again later."
    }
    button: {
      clearAll: "Clear All"
      dismiss: "Dismiss"
      goBack: "Go Back"
      label: "Label"
      next: "Next"
      previous: "Previous"
      retry: "Retry"
      upload: "Upload Files"
      uploading: "Uploading..."
      viewAll: "View All"
    }
    language: {
      en: {
        ariaLabel: "Switch to English"
      }
      fr: {
        ariaLabel: "Switch to French"
      }
      switcher: {
        ariaLabel: "Language switcher"
      }
    }
    notFound: {
      message: "The page you are looking for was not found."
      title: "Oops!"
    }
    products: {
      pageTitle: "Products - Label Inspection"
      title: "Products"
    }
    settings: {
      pageTitle: "Settings - Label Inspection"
      sections: {
        appearance: "Appearance"
        changePassword: "Change Password"
        deleteAccount: "Delete Account"
        userInformation: "User Information"
      }
      tabs: {
        appearance: "Appearance"
        dangerZone: "Danger zone"
        myProfile: "My profile"
        password: "Password"
      }
      title: "User Settings"
    }
    sidebar: {
      admin: "Admin"
      dashboard: "Dashboard"
      labels: "Labels"
      logOut: "Log Out"
      loggedInAs: "Logged in as: {{email}}"
      products: "Products"
      userSettings: "User Settings"
    }
  }
  errors: {
    fileType: {
      invalidTitle: "Invalid file types:"
    }
    labels: {
      errorOccurred: "An error occurred"
      loadFailed: "Failed to load labels"
      loadFailedRetry: "Failed to load labels. Please try again."
    }
  }
  labels: {
    common: {
      aria: {
        clearSelection: "Clear selection"
      }
      button: {
        cancel: "Cancel"
      }
    }
    dashboard: {
      completed: "dashboard.completed"
      createNewLabel: "Create New Label"
      createNewLabelDescription: "Upload and process a new label"
      inProgress: "dashboard.inProgress"
      manageProducts: "Manage Products"
      manageProductsDescription: "View and edit products"
      notStarted: "dashboard.notStarted"
      overview: "Overview"
      quickActions: "Quick Actions"
      title: "Dashboard - Label Inspection"
      totalLabels: "Total Labels"
      totalProducts: "Total Products"
      unlinkedLabels: "Unlinked Labels"
      unlinkedLabelsDescription: "Labels not associated with products"
      verifyLabels: "Verify Labels"
      verifyLabelsDescription: "Review labels ready for verification"
      verifyPageTitle: "Verify Labels - Label Inspection"
      viewAllLabels: "View All Labels"
      viewAllLabelsDescription: "Browse and manage all labels"
    }
    data: {
      contacts: {
        addContact: "Add Contact"
        address: "Address"
        contactNumber: "Contact {{number}}"
        email: "Email"
        name: "Name"
        noContacts: "No contacts added"
        phone: "Phone"
        type: "Type"
        types: {
          distributor: "Distributor"
          importer: "Importer"
          manufacturer: "Manufacturer"
          notSpecified: "Not specified"
        }
        website: "Website"
      }
      continueEditing: "Continue Editing"
      extractAllFields: "Extract All Fields"
      extractField: "Extract with AI"
      extractionAllSuccess: "All fields extracted successfully"
      extractionFailed: "Extraction failed. Please try again."
      extractionNoImages: "No images available for extraction"
      extractionNoValue: "No value was extracted for this field"
      extractionOnlyFertilizer: "Extraction is only available for fertilizer labels"
      extractionSuccess: "Field extracted successfully"
      fields: {
        brandNameEn: "Brand Name (English)"
        brandNameFr: "Brand Name (French)"
        cautionEn: "Caution (English)"
        cautionFr: "Caution (French)"
        contacts: "Contacts"
        guaranteedAnalysis: "Guaranteed Analysis"
        ingredients: "Ingredient List"
        instructionsEn: "Instructions (English)"
        instructionsFr: "Instructions (French)"
        k: "Potassium (K)"
        lotNumber: "Lot Number"
        n: "Nitrogen (N)"
        netWeight: "Net Weight"
        p: "Phosphorus (P)"
        productNameEn: "Product Name (English)"
        productNameFr: "Product Name (French)"
        registrationNumber: "Registration Number"
        volume: "Volume"
      }
      flagForReview: "Flag for review"
      guaranteedAnalysis: {
        addNutrient: "Add Nutrient"
        isMinimum: "Is Minimum"
        nameEn: "Name (English)"
        nameFr: "Name (French)"
        noNutrients: "No nutrients added"
        titleEn: "Title (English)"
        titleFr: "Title (French)"
        unit: "Unit"
        value: "Value"
      }
      helperText: {
        brandNameEn: "Enter the brand name as it appears on the label"
        brandNameFr: "Enter the brand name as it appears on the label"
        cautionEn: "Enter caution statements as they appear on the label"
        cautionFr: "Enter caution statements as they appear on the label"
        contacts: "Enter contact information for manufacturer, distributor, or importer"
        guaranteedAnalysis: "Enter guaranteed analysis with title, nutrients, values and units"
        ingredients: "Enter ingredients with bilingual names, values and units"
        instructionsEn: "Enter usage instructions as they appear on the label"
        instructionsFr: "Enter usage instructions as they appear on the label"
        k: "Enter potassium percentage"
        lotNumber: "Enter the lot or batch number"
        n: "Enter nitrogen percentage"
        netWeight: "Enter net weight with unit (e.g., 5 kg, 10 lbs)"
        p: "Enter phosphorus percentage"
        productNameEn: "Enter the product name as it appears on the label"
        productNameFr: "Enter the product name as it appears on the label"
        registrationNumber: "Enter the product registration number"
        volume: "Enter volume with unit (e.g., 1 L, 500 ml)"
      }
      ingredients: {
        addIngredient: "Add Ingredient"
        ingredientNumber: "Ingredient {{number}}"
        nameEn: "Name (English)"
        nameFr: "Name (French)"
        noIngredients: "No ingredients added"
        unit: "Unit"
        value: "Value"
      }
      markComplete: "Mark Complete"
      removeReviewFlag: "Remove review flag"
      save: "Save"
      saved: "Changes saved successfully"
      sections: {
        basic: "Basic Information"
        guaranteed: "Guaranteed Analysis"
        ingredients: "Ingredients"
        npk: "NPK Analysis"
        safety: "Safety Information"
      }
    }
    empty: {
      noLabels: "No labels found"
      noLabelsDescription: "Labels you upload will appear here."
      noMatches: "No labels match your current filters"
      noMatchesDescription: "Try adjusting your filters to see more results."
    }
    errors: {
      fileType: {
        invalid: "{{fileName}}: Not added - must be PNG, JPEG or WebP"
      }
    }
    files: {
      pageTitle: "Label Files - Label Inspection"
      title_one: "Label Image: {{count}} (max {{max}})"
      title_other: "Label Images: {{count}} (max {{max}})"
    }
    filter: {
      completed: "Completed"
      inProgress: "In Progress"
      notStarted: "Not Started"
      reviewStatus: "filter.reviewStatus"
      title: "Filter list"
      unlinked: "Unlinked"
    }
    image: {
      notAvailable: "Image not available"
      sequence: "Sequence: {{order}}"
      slideAlt: "Slide {{number}}"
    }
    labels: {
      bulkActions: {
        delete: "Delete"
        deleteDialog: {
          description_one: "Are you sure you want to delete {{count}} selected label? This action cannot be undone and will permanently delete the label and all associated files."
          description_other: "Are you sure you want to delete {{count}} selected labels? This action cannot be undone and will permanently delete the labels and all associated files."
          title_one: "Delete {{count}} label?"
          title_other: "Delete {{count}} labels?"
        }
        deleteNotImplemented: "Bulk delete functionality not yet implemented"
        export: "Export"
        exportNotImplemented: "Export functionality not yet implemented"
        selected_one: "{{count}} selected"
        selected_other: "{{count}} selected"
      }
      create: {
        description: "Select at least one label image to create a new label"
        maxFilesWarning_one: "Maximum {{max}} files allowed. Please remove {{count}} file before uploading."
        maxFilesWarning_other: "Maximum {{max}} files allowed. Please remove {{count}} files before uploading."
        of: "of"
        pageTitle: "Create New Label - Label Inspection"
        remove: "Remove"
        selectFiles: "Select files or drag and drop"
        selectedFiles: "Selected files"
        title: "Create New Label"
      }
      rowActions: {
        actionsForLabel: "Actions for label {{id}}"
        delete: "Delete"
        deleteDialog: {
          description: "Are you sure you want to delete this label? This action cannot be undone and will permanently delete the label and all associated files."
          title: "Delete label"
        }
        deleteNotImplemented: "Delete functionality not yet implemented"
        viewDetails: "View Details"
      }
      upload: {
        preparing: "Preparing uploads..."
        uploaded_one: "{{completed}} of {{total}} file uploaded"
        uploaded_other: "{{completed}} of {{total}} files uploaded"
        uploading_one: "Uploading {{current}} of {{total}} file..."
        uploading_other: "Uploading {{current}} of {{total}} files..."
      }
    }
    pageTitle: "Labels - Label Inspection"
    table: {
      actions: "Actions"
      copyId: "Copy label ID {{id}}"
      createdAt: "Created At"
      id: "ID"
      idCopied: "Label ID copied to clipboard"
      productName: "Product Name"
      reviewStatus: "table.reviewStatus"
      selectAll: "select all labels"
      sortedAscending: "sorted ascending"
      sortedDescending: "sorted descending"
    }
    title: "Labels"
    upload: {
      failed_one: "Failed to upload {{failed}} of {{total}} file"
      failed_other: "Failed to upload {{failed}} of {{total}} files"
      partial: "Upload complete: {{completed}} succeeded, {{failed}} failed"
      success_one: "Successfully uploaded {{completed}} of {{total}} file"
      success_other: "Successfully uploaded {{completed}} of {{total}} files"
    }
  }
}

export default Resources
