/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as RecoverPasswordRouteImport } from './routes/recover-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LayoutRouteImport } from './routes/_layout'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LayoutSettingsRouteImport } from './routes/_layout/settings'
import { Route as LayoutAdminRouteImport } from './routes/_layout/admin'
import { Route as LayoutProductTypeRouteImport } from './routes/_layout/$productType'
import { Route as LayoutProductTypeIndexRouteImport } from './routes/_layout/$productType/index'
import { Route as LayoutProductTypeProductsIndexRouteImport } from './routes/_layout/$productType/products/index'
import { Route as LayoutProductTypeLabelsIndexRouteImport } from './routes/_layout/$productType/labels/index'
import { Route as LayoutProductTypeProductsNewRouteImport } from './routes/_layout/$productType/products/new'
import { Route as LayoutProductTypeProductsProductIdRouteImport } from './routes/_layout/$productType/products/$productId'
import { Route as LayoutProductTypeLabelsNewRouteImport } from './routes/_layout/$productType/labels/new'
import { Route as LayoutProductTypeLabelsLabelIdRouteImport } from './routes/_layout/$productType/labels/$labelId'
import { Route as LayoutProductTypeLabelsLabelIdFilesRouteImport } from './routes/_layout/$productType/labels/$labelId/files'
import { Route as LayoutProductTypeLabelsLabelIdEditRouteImport } from './routes/_layout/$productType/labels/$labelId/edit'
import { Route as LayoutProductTypeLabelsLabelIdComplianceRouteImport } from './routes/_layout/$productType/labels/$labelId/compliance'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RecoverPasswordRoute = RecoverPasswordRouteImport.update({
  id: '/recover-password',
  path: '/recover-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutRoute = LayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutSettingsRoute = LayoutSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutAdminRoute = LayoutAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutProductTypeRoute = LayoutProductTypeRouteImport.update({
  id: '/$productType',
  path: '/$productType',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutProductTypeIndexRoute = LayoutProductTypeIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LayoutProductTypeRoute,
} as any)
const LayoutProductTypeProductsIndexRoute =
  LayoutProductTypeProductsIndexRouteImport.update({
    id: '/products/',
    path: '/products/',
    getParentRoute: () => LayoutProductTypeRoute,
  } as any)
const LayoutProductTypeLabelsIndexRoute =
  LayoutProductTypeLabelsIndexRouteImport.update({
    id: '/labels/',
    path: '/labels/',
    getParentRoute: () => LayoutProductTypeRoute,
  } as any)
const LayoutProductTypeProductsNewRoute =
  LayoutProductTypeProductsNewRouteImport.update({
    id: '/products/new',
    path: '/products/new',
    getParentRoute: () => LayoutProductTypeRoute,
  } as any)
const LayoutProductTypeProductsProductIdRoute =
  LayoutProductTypeProductsProductIdRouteImport.update({
    id: '/products/$productId',
    path: '/products/$productId',
    getParentRoute: () => LayoutProductTypeRoute,
  } as any)
const LayoutProductTypeLabelsNewRoute =
  LayoutProductTypeLabelsNewRouteImport.update({
    id: '/labels/new',
    path: '/labels/new',
    getParentRoute: () => LayoutProductTypeRoute,
  } as any)
const LayoutProductTypeLabelsLabelIdRoute =
  LayoutProductTypeLabelsLabelIdRouteImport.update({
    id: '/labels/$labelId',
    path: '/labels/$labelId',
    getParentRoute: () => LayoutProductTypeRoute,
  } as any)
const LayoutProductTypeLabelsLabelIdFilesRoute =
  LayoutProductTypeLabelsLabelIdFilesRouteImport.update({
    id: '/files',
    path: '/files',
    getParentRoute: () => LayoutProductTypeLabelsLabelIdRoute,
  } as any)
const LayoutProductTypeLabelsLabelIdEditRoute =
  LayoutProductTypeLabelsLabelIdEditRouteImport.update({
    id: '/edit',
    path: '/edit',
    getParentRoute: () => LayoutProductTypeLabelsLabelIdRoute,
  } as any)
const LayoutProductTypeLabelsLabelIdComplianceRoute =
  LayoutProductTypeLabelsLabelIdComplianceRouteImport.update({
    id: '/compliance',
    path: '/compliance',
    getParentRoute: () => LayoutProductTypeLabelsLabelIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/recover-password': typeof RecoverPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/$productType': typeof LayoutProductTypeRouteWithChildren
  '/admin': typeof LayoutAdminRoute
  '/settings': typeof LayoutSettingsRoute
  '/$productType/': typeof LayoutProductTypeIndexRoute
  '/$productType/labels/$labelId': typeof LayoutProductTypeLabelsLabelIdRouteWithChildren
  '/$productType/labels/new': typeof LayoutProductTypeLabelsNewRoute
  '/$productType/products/$productId': typeof LayoutProductTypeProductsProductIdRoute
  '/$productType/products/new': typeof LayoutProductTypeProductsNewRoute
  '/$productType/labels/': typeof LayoutProductTypeLabelsIndexRoute
  '/$productType/products/': typeof LayoutProductTypeProductsIndexRoute
  '/$productType/labels/$labelId/compliance': typeof LayoutProductTypeLabelsLabelIdComplianceRoute
  '/$productType/labels/$labelId/edit': typeof LayoutProductTypeLabelsLabelIdEditRoute
  '/$productType/labels/$labelId/files': typeof LayoutProductTypeLabelsLabelIdFilesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/recover-password': typeof RecoverPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/admin': typeof LayoutAdminRoute
  '/settings': typeof LayoutSettingsRoute
  '/$productType': typeof LayoutProductTypeIndexRoute
  '/$productType/labels/$labelId': typeof LayoutProductTypeLabelsLabelIdRouteWithChildren
  '/$productType/labels/new': typeof LayoutProductTypeLabelsNewRoute
  '/$productType/products/$productId': typeof LayoutProductTypeProductsProductIdRoute
  '/$productType/products/new': typeof LayoutProductTypeProductsNewRoute
  '/$productType/labels': typeof LayoutProductTypeLabelsIndexRoute
  '/$productType/products': typeof LayoutProductTypeProductsIndexRoute
  '/$productType/labels/$labelId/compliance': typeof LayoutProductTypeLabelsLabelIdComplianceRoute
  '/$productType/labels/$labelId/edit': typeof LayoutProductTypeLabelsLabelIdEditRoute
  '/$productType/labels/$labelId/files': typeof LayoutProductTypeLabelsLabelIdFilesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_layout': typeof LayoutRouteWithChildren
  '/login': typeof LoginRoute
  '/recover-password': typeof RecoverPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/_layout/$productType': typeof LayoutProductTypeRouteWithChildren
  '/_layout/admin': typeof LayoutAdminRoute
  '/_layout/settings': typeof LayoutSettingsRoute
  '/_layout/$productType/': typeof LayoutProductTypeIndexRoute
  '/_layout/$productType/labels/$labelId': typeof LayoutProductTypeLabelsLabelIdRouteWithChildren
  '/_layout/$productType/labels/new': typeof LayoutProductTypeLabelsNewRoute
  '/_layout/$productType/products/$productId': typeof LayoutProductTypeProductsProductIdRoute
  '/_layout/$productType/products/new': typeof LayoutProductTypeProductsNewRoute
  '/_layout/$productType/labels/': typeof LayoutProductTypeLabelsIndexRoute
  '/_layout/$productType/products/': typeof LayoutProductTypeProductsIndexRoute
  '/_layout/$productType/labels/$labelId/compliance': typeof LayoutProductTypeLabelsLabelIdComplianceRoute
  '/_layout/$productType/labels/$labelId/edit': typeof LayoutProductTypeLabelsLabelIdEditRoute
  '/_layout/$productType/labels/$labelId/files': typeof LayoutProductTypeLabelsLabelIdFilesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/recover-password'
    | '/reset-password'
    | '/signup'
    | '/$productType'
    | '/admin'
    | '/settings'
    | '/$productType/'
    | '/$productType/labels/$labelId'
    | '/$productType/labels/new'
    | '/$productType/products/$productId'
    | '/$productType/products/new'
    | '/$productType/labels/'
    | '/$productType/products/'
    | '/$productType/labels/$labelId/compliance'
    | '/$productType/labels/$labelId/edit'
    | '/$productType/labels/$labelId/files'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/recover-password'
    | '/reset-password'
    | '/signup'
    | '/admin'
    | '/settings'
    | '/$productType'
    | '/$productType/labels/$labelId'
    | '/$productType/labels/new'
    | '/$productType/products/$productId'
    | '/$productType/products/new'
    | '/$productType/labels'
    | '/$productType/products'
    | '/$productType/labels/$labelId/compliance'
    | '/$productType/labels/$labelId/edit'
    | '/$productType/labels/$labelId/files'
  id:
    | '__root__'
    | '/'
    | '/_layout'
    | '/login'
    | '/recover-password'
    | '/reset-password'
    | '/signup'
    | '/_layout/$productType'
    | '/_layout/admin'
    | '/_layout/settings'
    | '/_layout/$productType/'
    | '/_layout/$productType/labels/$labelId'
    | '/_layout/$productType/labels/new'
    | '/_layout/$productType/products/$productId'
    | '/_layout/$productType/products/new'
    | '/_layout/$productType/labels/'
    | '/_layout/$productType/products/'
    | '/_layout/$productType/labels/$labelId/compliance'
    | '/_layout/$productType/labels/$labelId/edit'
    | '/_layout/$productType/labels/$labelId/files'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LayoutRoute: typeof LayoutRouteWithChildren
  LoginRoute: typeof LoginRoute
  RecoverPasswordRoute: typeof RecoverPasswordRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SignupRoute: typeof SignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recover-password': {
      id: '/recover-password'
      path: '/recover-password'
      fullPath: '/recover-password'
      preLoaderRoute: typeof RecoverPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof LayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout/settings': {
      id: '/_layout/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof LayoutSettingsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/admin': {
      id: '/_layout/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof LayoutAdminRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/$productType': {
      id: '/_layout/$productType'
      path: '/$productType'
      fullPath: '/$productType'
      preLoaderRoute: typeof LayoutProductTypeRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/$productType/': {
      id: '/_layout/$productType/'
      path: '/'
      fullPath: '/$productType/'
      preLoaderRoute: typeof LayoutProductTypeIndexRouteImport
      parentRoute: typeof LayoutProductTypeRoute
    }
    '/_layout/$productType/products/': {
      id: '/_layout/$productType/products/'
      path: '/products'
      fullPath: '/$productType/products/'
      preLoaderRoute: typeof LayoutProductTypeProductsIndexRouteImport
      parentRoute: typeof LayoutProductTypeRoute
    }
    '/_layout/$productType/labels/': {
      id: '/_layout/$productType/labels/'
      path: '/labels'
      fullPath: '/$productType/labels/'
      preLoaderRoute: typeof LayoutProductTypeLabelsIndexRouteImport
      parentRoute: typeof LayoutProductTypeRoute
    }
    '/_layout/$productType/products/new': {
      id: '/_layout/$productType/products/new'
      path: '/products/new'
      fullPath: '/$productType/products/new'
      preLoaderRoute: typeof LayoutProductTypeProductsNewRouteImport
      parentRoute: typeof LayoutProductTypeRoute
    }
    '/_layout/$productType/products/$productId': {
      id: '/_layout/$productType/products/$productId'
      path: '/products/$productId'
      fullPath: '/$productType/products/$productId'
      preLoaderRoute: typeof LayoutProductTypeProductsProductIdRouteImport
      parentRoute: typeof LayoutProductTypeRoute
    }
    '/_layout/$productType/labels/new': {
      id: '/_layout/$productType/labels/new'
      path: '/labels/new'
      fullPath: '/$productType/labels/new'
      preLoaderRoute: typeof LayoutProductTypeLabelsNewRouteImport
      parentRoute: typeof LayoutProductTypeRoute
    }
    '/_layout/$productType/labels/$labelId': {
      id: '/_layout/$productType/labels/$labelId'
      path: '/labels/$labelId'
      fullPath: '/$productType/labels/$labelId'
      preLoaderRoute: typeof LayoutProductTypeLabelsLabelIdRouteImport
      parentRoute: typeof LayoutProductTypeRoute
    }
    '/_layout/$productType/labels/$labelId/files': {
      id: '/_layout/$productType/labels/$labelId/files'
      path: '/files'
      fullPath: '/$productType/labels/$labelId/files'
      preLoaderRoute: typeof LayoutProductTypeLabelsLabelIdFilesRouteImport
      parentRoute: typeof LayoutProductTypeLabelsLabelIdRoute
    }
    '/_layout/$productType/labels/$labelId/edit': {
      id: '/_layout/$productType/labels/$labelId/edit'
      path: '/edit'
      fullPath: '/$productType/labels/$labelId/edit'
      preLoaderRoute: typeof LayoutProductTypeLabelsLabelIdEditRouteImport
      parentRoute: typeof LayoutProductTypeLabelsLabelIdRoute
    }
    '/_layout/$productType/labels/$labelId/compliance': {
      id: '/_layout/$productType/labels/$labelId/compliance'
      path: '/compliance'
      fullPath: '/$productType/labels/$labelId/compliance'
      preLoaderRoute: typeof LayoutProductTypeLabelsLabelIdComplianceRouteImport
      parentRoute: typeof LayoutProductTypeLabelsLabelIdRoute
    }
  }
}

interface LayoutProductTypeLabelsLabelIdRouteChildren {
  LayoutProductTypeLabelsLabelIdComplianceRoute: typeof LayoutProductTypeLabelsLabelIdComplianceRoute
  LayoutProductTypeLabelsLabelIdEditRoute: typeof LayoutProductTypeLabelsLabelIdEditRoute
  LayoutProductTypeLabelsLabelIdFilesRoute: typeof LayoutProductTypeLabelsLabelIdFilesRoute
}

const LayoutProductTypeLabelsLabelIdRouteChildren: LayoutProductTypeLabelsLabelIdRouteChildren =
  {
    LayoutProductTypeLabelsLabelIdComplianceRoute:
      LayoutProductTypeLabelsLabelIdComplianceRoute,
    LayoutProductTypeLabelsLabelIdEditRoute:
      LayoutProductTypeLabelsLabelIdEditRoute,
    LayoutProductTypeLabelsLabelIdFilesRoute:
      LayoutProductTypeLabelsLabelIdFilesRoute,
  }

const LayoutProductTypeLabelsLabelIdRouteWithChildren =
  LayoutProductTypeLabelsLabelIdRoute._addFileChildren(
    LayoutProductTypeLabelsLabelIdRouteChildren,
  )

interface LayoutProductTypeRouteChildren {
  LayoutProductTypeIndexRoute: typeof LayoutProductTypeIndexRoute
  LayoutProductTypeLabelsLabelIdRoute: typeof LayoutProductTypeLabelsLabelIdRouteWithChildren
  LayoutProductTypeLabelsNewRoute: typeof LayoutProductTypeLabelsNewRoute
  LayoutProductTypeProductsProductIdRoute: typeof LayoutProductTypeProductsProductIdRoute
  LayoutProductTypeProductsNewRoute: typeof LayoutProductTypeProductsNewRoute
  LayoutProductTypeLabelsIndexRoute: typeof LayoutProductTypeLabelsIndexRoute
  LayoutProductTypeProductsIndexRoute: typeof LayoutProductTypeProductsIndexRoute
}

const LayoutProductTypeRouteChildren: LayoutProductTypeRouteChildren = {
  LayoutProductTypeIndexRoute: LayoutProductTypeIndexRoute,
  LayoutProductTypeLabelsLabelIdRoute:
    LayoutProductTypeLabelsLabelIdRouteWithChildren,
  LayoutProductTypeLabelsNewRoute: LayoutProductTypeLabelsNewRoute,
  LayoutProductTypeProductsProductIdRoute:
    LayoutProductTypeProductsProductIdRoute,
  LayoutProductTypeProductsNewRoute: LayoutProductTypeProductsNewRoute,
  LayoutProductTypeLabelsIndexRoute: LayoutProductTypeLabelsIndexRoute,
  LayoutProductTypeProductsIndexRoute: LayoutProductTypeProductsIndexRoute,
}

const LayoutProductTypeRouteWithChildren =
  LayoutProductTypeRoute._addFileChildren(LayoutProductTypeRouteChildren)

interface LayoutRouteChildren {
  LayoutProductTypeRoute: typeof LayoutProductTypeRouteWithChildren
  LayoutAdminRoute: typeof LayoutAdminRoute
  LayoutSettingsRoute: typeof LayoutSettingsRoute
}

const LayoutRouteChildren: LayoutRouteChildren = {
  LayoutProductTypeRoute: LayoutProductTypeRouteWithChildren,
  LayoutAdminRoute: LayoutAdminRoute,
  LayoutSettingsRoute: LayoutSettingsRoute,
}

const LayoutRouteWithChildren =
  LayoutRoute._addFileChildren(LayoutRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LayoutRoute: LayoutRouteWithChildren,
  LoginRoute: LoginRoute,
  RecoverPasswordRoute: RecoverPasswordRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SignupRoute: SignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
