# Validates repo standards and checks markdown.
# Called by ci.yml
name: Repo Standard

on:
  workflow_call:

jobs:
  validate:
    name: Validate
    uses: ai-cfia/github-workflows/.github/workflows/workflow-repo-standards-validation.yml@main
    secrets: inherit

  markdown-check:
    name: Markdown Check
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - uses: actions/checkout@v6
      - uses: DavidAnson/markdownlint-cli2-action@6b51ade7a9e4a75a7ad929842dd298a3804ebe8b # v23
        with:
          globs: "**/*.md"
      - uses: tcort/github-action-markdown-link-check@v1
