# Scans for secrets.
# Called by ci.yml
name: Secrets Scan

on:
  workflow_call:

jobs:
  scan:
    name: Scan
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: trufflesecurity/trufflehog@6171fa9f6676edf21e15bba41f049b18399d7372
        with:
          base: ""
          head: ${{ github.ref_name }}
          extra_args: --results=verified,unknown
