# Scans for secrets.
# Called by ci.yml for PRs, runs directly on push to main.
name: Secrets Scan

on:
  workflow_call:
  push:
    branches: [main]

jobs:
  scan:
    name: Scan
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: trufflesecurity/trufflehog@d17df4845197a68cbc37d33ad0e7f325b45c0033
        with:
          base: ""
          head: ${{ github.ref_name }}
          extra_args: --results=verified,unknown
