# Scans for secrets.
# Called by ci.yml for PRs, runs directly on push to main.
name: Secrets Scan

on:
  workflow_call:
  push:
    branches: [main]

jobs:
  scan:
    name: Scan
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: trufflesecurity/trufflehog@6c64db94d5b2e09d7e0948fb6bd3166cc6fffbc7
        with:
          base: ""
          head: ${{ github.ref_name }}
          extra_args: --results=verified,unknown
